# Introducción {#Introducción}

Algunas consideraciones generales sobre las Ciencias Sociales y, en particular, sobre la Ciencia Política.

En el texto "Teoría de la Organización", Giorgio Freddi^[Note: Ver DICCIONARIO DE POLITICA de N. Bobbio et al. - México -Ed. Siglo XXI - 1986 - pg. 1150.] construye un argumento de suma reelevancia que puede ser aplicado en todo campo científico social: 

> "(...) en el presente contexto entendemos más bien por teoría un esquema conceptual o, mejor aún, un conjunto de esquemas conceptuales (que pueden ser complementarios o si no alternativos) cuyo objetivo (no necesariamente conseguido) es el de permitirnos describir, interpretar, posiblemente prever y eventualmente controlar fenómenos organizativos (...)".

Giorgio deja en claro la imprecisión con que estamos acostumbrados a usar la palabra "Teoría" en el campo de las ciencias sociales: en sentido estricto o en sentido amplio; como principio abstracto o como "lección de la historia"; como meta o como etapa del camino científico; o como ese mismo camino, cualquiera sea el modo y medida en que se lo haya recorrido. Al mencionar el "camino científico" estamos aludiendo a un tema fundamental: las cuestiones metodológicas. Respecto de ellas creemos valioso exponer un resumen y comentar las ideas de Eugène J. Meehan^[Note: Ver "La Ciencia - Minotauro o Mesías" en Eugène J. Meehan: PEN- SAMIENTO POLITICO CONTEMPORANEO - Madrid - Rev. de Occidente - 1973 pg. 55 y ss.].

Todo estudioso serio tiene que interesarse en metodología. Introducirse en el estudio de la Teoría Política, por ejemplo, es introducirse en los problemas metodológicos de la Ciencia Política y en la discusión sobre cómo han sido resueltos. El problema de los métodos siempre ha motivado diferencias de opinión. La etapa contemporánea de esta discusión comenzó con la fragmentación de la gran "mater scientia", la Filosofía, a principios de la Edad Moderna.

La expansión del conocimiento científico se produjo tras una ruptura revolucionaria: el razonamiento deductivo a partir de principios a priori y la apelación a la autoridad fueron reemplazados por el razonamiento inductivo a partir de observaciones empíricas y por el cuestionamiento de toda autoridad. Dentro de este contexto, se pretendió que las ciencias sociales y hasta las humanidades imitaran a las ciencias físicas. A decir verdad, los resultados fueron deplorables. Finalmente, las ciencias físicas experimentaron una revolución conceptual profunda a principios del siglo XX, con la aparición de la Teoría de la Relatividad y la Mecánica Cuántica.Aún en ese campo, de las "ciencias duras", las relaciones absolutas fueron reemplazadas por relaciones probabilísticas (semejantes a las obtenibles en ciencias sociales) y se dejó de creer que la ciencia física produjera un conocimiento objetivo del mundo. El gran científico inglés Eddington concluyó su clásica obra sobre Física preguntándose si al mundo físico lo descubrimos o lo inventamos...

La actividad científica newtoniana era algo así como explorar una compleja máquina, para descubrir lo que ya estaba allí. Esta idea es en buena parte responsable de las simplificaciones y de los dogmatismos de los positivistas del siglo XIX. Hasta un sociólogo de la talla de Emile Durkheim sostenía que no eran necesarios los estudios comparados porque creía que una investigación bien planteada descubriría el "mecanismo básico", de vigencia universal. La búsqueda de regularidades sociales que pudieran expresarse como leyes se abordó en términos newtonianos,pero esta concepción no resistió los embates teóricos, en especial los de la Antropología Comparada; se acumularon demasiadas anomalías y falló finalmente la analogía mecánica. Se produjo así la gran revolución intelectual moderna, cuyas consecuencias aún hoy continúan.

Dos principios han emergido de este proceso, de especial interés para las ciencias sociales:

- La ciencia no se ocupa de la naturaleza de la realidad. Nada esencial puede decir de la realidad. La ciencia es un procedimiento para ordenar y relacionar sistemáticamente los elementos de la experiencia humana, para anticipar experiencias ulteriores a la luz de las relaciones establecidas. La ciencia es una tarea específicamente humana: es lo que el hombre puede hacer por el hombre guiándose por la experiencia del hombre.

- Todas las proposiciones científicas son relativas, condicionales y no absolutas. Son enunciados de probabilidad y no relaciones invariantes. Aunque el lenguaje científico no siempre lo exprese con claridad, las leyes científicas son siempre condicionales porque son inducciones, y no puede haber generalizaciones inductivas absolutas.

Con respecto a los supuestos metodológicos de la ciencia, cabe decir, en primer lugar, que la medición es súmamente deseable. En el campo social la medición es muy difícil, a veces casi imposible, sobre todo por la falta de verdaderas unidades de medida. Hay que admitir esa dificultad; hay que aceptar (transitoriamente, al menos) esa imposibilidad. También es cierto que la medición no es todo: hay aspectos del fenómeno que la medición no capta, pero no hay que confundir lo posible con lo deseable: poder medir sigue siendo deseable, aunque no podamos hacerlo.

En segundo lugar, pero no menos importante como actitud básica para la investigación, está el principio de que el conocimiento científico se define en términos de percepción y experiencia humana; no en términos de "realidad", "verdad" o "absoluto". A su vez, el concepto de EXPERIENCIA debe ser precisado. En este campo no se trata de la experiencia personal, subjetiva, única e irrepetible. La experiencia científica ha de ser pública, plural, abierta a la verificación o falsación por otros.

En principio, la finalidad de la ciencia es la explicación de los fenómenos observados. También abarca la organización de las observaciones y experiencias en generalizaciones y teorías que permitan predecir acontecimientos futuros. Cabe hacer notar, sin embargo, que la predicción no es un requisito indispensable del conocimiento científico, y que actualmente tiende a ser abandonada como actividad científica para ser vista más bien como una aplicación técnica.

La ciencia requiere que sus afirmaciones sean confirmadas por cotejo con los hechos, por observación sistemática y experiencia, si es posible hacerla, pero cabe aquí hacer notar que a medida que las estructuras explicativas se hacen más complejas, aparecen muchos niveles de generalización como intermediadores entre los observables y la teoría, con lo cual la comprobación (o falsación) empírica se hace cada vez más difícil. Esto es particularmente cierto en el caso de las llamadas TEORIAS GENERALES, que transitan por niveles de abstracción muy elevados, muy por encima de los hechos que serían en última instancia su base empírica.

En el campo científico, como es sabido, no corresponde enunciar valores de tipo moral. La ciencia es axiológicamente neutra, lo que no significa que los valores no existan, o que el científico, en cuanto hombre, no los tenga. Simplemente significa que esos valores caen fuera de la esfera de acción propia de la ciencia.

La ciencia se apoya en el empirismo; su camino es la observación, medición, conceptualización y generalización. No le basta la coherencia interna del pensamiento: necesita verificar la conexión entre los conceptos y los fenómenos concretos. La ciencia, por ejemplo, no puede negar validez al postulado idealista de la posibilidad afirmativa de captar las esencias, o a la afirmación cristiana que ve la mano de Dios en la historia del hombre. Sencillamente, no tiene lugar en sí misma para tales afirmaciones, que no pueden verificarse empíricamente, en los términos de la verificación empírica científica.

Tales son algunas de las grandezas y limitaciones de la ciencia como construcción del espíritu humano. Es importante hoy despojarla de los mitos consagratorios y de las condenaciones fulminantes para verla con serenidad en su real dimensión humana. El siglo XIX fué un siglo ilusionado con la ciencia. El siglo XX es un siglo decepcionado. Para una comprensión más real del tema, puede ser útil repasar las actitudes críticas que ha inspirado la ciencia moderna. Según Eugène Meehan hay tres grupos críticos principales:

- Los esencialistas y teleologistas.
- Los dualistas.
- Los cultores de la "Verstehende Soziologie".

Los críticos más duros de la actual metodología científica son los neoplatónicos, los aristotélico-tomistas y los idealistas hegelianos. Otra fuente de anticientificismo es el existencialismo, tanto en su versión teísta como en su versión secular, a causa de su vinculación con la Fenomenología de Husserl y el vitalismo de Bergson. Ambos niegan sentido a la realidad objetiva y postulan la existencia de un "sentido interno esencial" que se manifiesta únicamente en el proceso de "experimentar la existencia".

El anticientificismo más extremo, sin embargo, no se encuentra en la Filosofía sino en la literatura moderna, que en muchos casos tiende a valorar casi exclusivamente los aspectos subjetivos de la existencia y a aproximarse al nihilismo. Desde Franz Kafka hasta el movimiento dadaísta (con su renuncia a toda comunicación racional) o hasta los místicos del tipo de Simone Weil; a Ernest Hemingway, con su rechazo al pensamiento abstracto y su preferencia por la acción, hasta el mismo Sartre, que propone la "acción sobre el medio" como escape a la absurdidad de la existencia, son todos ejemplos de este anticientificismo, en un contexto en el que "saber" significa "hacer".

Los anticientíficos más adversos ven en la ciencia, no una estrategia equivocada sino un auténtico mal, un desvío, un peligro moral. La ciencia es vista como una práctica que priva a la vida de su misterio, de su pasión y su grandeza. Sören Kierkegaard, por ejemplo, afirma que todo conocimiento esencial gira en torno a la existencia, y que es verdad lo que el hombre cree apasionadamente. En esa visión, la ciencia es una distracción. Gabriel Marcel escribió páginas amargamente críticas (y lúcidas) contra la sociedad de masas, producto directo del cientificismo y la tecnocracia. Leo Strauss afirmó que el intento de crear una ciencia social "científica" ha llevado a una crisis filosófica total, porque hecho y valor constituyen una unidad que la ciencia, desgraciadamente, ha roto.

El segundo grupo mencionado por Eugène Meehan es el de los dualistas. Son los críticos más moderados de la ciencia, porque reconocen su valor en ciertos campos pero consideran que otros le son inaccesibles. Karl Jaspers, por ejemplo, concibe a la existencia dividida en tres sectores: la existencia empírica, la conciencia y el espíritu. Cada uno de ellos tiene su propia verdad. De tal modo, ciencia y filosofía ocupan esferas separadas,si bien mantienen contactos entre sí. Jacques Maritain, eminente tomista, también da una solución dualista al problema de la investigación científica, porque acepta el valor de la ciencia positiva en su propio encuadre, pero considera que en el campo ontológico el conocimiento se obtiene por percepción interna, no sujeta a la observación y verificación científicas. Similares opiniones sustentan autores como Ortega y Gasset, Reinhold, etc. En general, la posición dualista no se opone frontalmente a la ciencia sino que intenta sustraerle un amplio sector de fenómenos naturales y, sobre todo, culturales y sociales.

El tercer grupo mencionado por Meehan es el de los partidarios de la "Verstehende Soziologie". Estos constituyen un grupo muy diferente de los anteriores: los esencialistas y teleologistas rechazan por entero la ciencia tal como la entendemos; los dualistas tratan de restringirla a determinados campos; mientras que estos partidarios de la "sociología de la comprensión (o simpatía)" rechazan el método científico como inapropiado para el estudio de los fenómenos sociales, y proponen una vía alternativa: la "comprensión". Este concepto fué usado por Wilhem Dilthey en historia y por Max Weber en sociología y economía. Dilthey sostenía que las relaciones humanas contienen una "cualidad significativa", y que para captarla el investigador debe necesariamente hacer referencia a su propia experiencia humana, a su propia "humanidad".

Todo hecho o acto humano va siempre acompañado de una representación interna de su valor. La intencionalidad y el significado más profundo del acto emerge de esa representación, que no es observable desde el exterior y que solo puede captarse por simpatía o comprensión, en un contexto de interacción humana y de compromiso en la acción. La COMPRENSION es, pues, consecuencia de una visión interna de la condición humana, común a todos los hombres más allá de las pautas culturales particulares. Dilthey veía en la comprensión el fin mismo de toda investigación. Para Weber, ello no bastaba: la comprensión tenía que ser sometida a comprobación empírica.

El concepto de "Verstehen", que traducimos aproximadamente por "comprensión" es muy difícil de definir: visión en profundidad de las relaciones sociales; percepción afectiva de los motivos de la conducta humana; conocimiento interno, logrado por participación en los acontecimientos, etc. De todos modos, es siempre una forma de conocimiento lograda mediante la acción.

La "Verstehende Soziologie" plantea sus objeciones a las prácticas científicas corrientes por medio de postulados que, en nuestra opinión, contienen su parte de verdad, pero que llevados al extremo merecen a su vez serios reparos. Por ejemplo, su oposición a todo intento de generalización en la explicación de los hechos humanos. Sostiene ésto, en primer lugar, en base a la singularidad de los hechos. En toda la Historia -dicen- no hay dos hechos iguales, de modo que no pueden explicarse hechos mediante generalizaciones, que serían relaciones entre dos o más clases de eventos. Ahora bien,las clases de eventos se establecen, no en base a un criterio de igualdad sino a un criterio de semejanza, y todos sabemos que no existen hechos iguales pero sí hechos semejantes, por lo que esta objeción no nos parece válida. Otra razón que esgrimen se basa en la individualidad de los hechos. Sostienen algo muy cierto: los fenómenos sociales son totalidades, entidades indivisibles, cuyas partes no pueden analizarse sin alterar cualidades esenciales del todo. Esto es cierto, pero es necesario diferenciar las partes de un todo de sus rasgos, que sí pueden analizarse sin que el todo pierda sus cualidades propias.

Otra objeción de la "Verstehende Soziologie" se basa en la dosis de subjetivismo y de libre voluntad que contienen las acciones humanas. Toda acción humana -dicen- consta de dos partes: una subjetiva (no observable) y otra objetiva (observable). Una explicación adecuada de la conducta debe incluir ambos aspectos, lo que plantea el problema de los motivos de la conducta objetiva, que efectivamente son muy difíciles de determinar en forma certera. Esto es cierto, pero cabe observar que una buena parte de la conducta humana puede explicarse sin referencia a motivos subjetivos, o infiriéndolos hipotéticamente, en especial si esa conducta se produce en el contexto de situaciones muy estructuradas, como ocurre en el campo po- lítico. Por su parte, el argumento de la libre voluntad pierde buena parte de su eficacia si se recuerda que las generalizaciones (y más ampliamente, los enunciados científicos) tienen un significado probabilístico, tendencial, que deja márgen para comportamientos individuales fuera de norma. La experiencia ha evidenciado una notable regularidad de las conductas humanas, aún en períodos de cambio; y el carácter marginal de los comportamientos inesperados, si se trabaja con grandes números de relaciones.

A ésto se podría agregar la crítica que hace Habermas en su teoría de los intereses constitutivos de saberes, a las ciencias hermenéuticas, interpretativas, basadas en métodos de Verstehen. Estas ciencias están inspiradas en un interés práctico; producen un saber de entendimiento significativo, capaz de guiar el juicio práctico. Pero no son, según Habermas, una base adecuada para las ciencias sociales porque, si bien captan el significado subjetivo de los hechos objetivos, no descubren el modo en que ese significado subjetivo está condicionado o distorsionado por las condiciones sociales, culturales y políticas imperantes. Ese logro está, según Habermas, reservado para la ciencia social crítica, inspirada en un interés emancipatorio. Esto a su vez ha sido criticado, porque Habermas no proporciona claramente la base epistemológica, los criterios de racionalidad, que le permitan convalidar el "saber emancipador"que surgiría de ella.

Ante este panorama cuestionador de la ciencia, Eugène Meehan concluye diciendo que la idea de que las reglas de la investigación científica no son aplicables al campo humano y social es ciertamente exagerada y no puede aceptarse, pero hay que tomar en cuenta la parte de verdad que contiene: la investigación científica social afronta problemas muy específicos, sobre todo en relación con las significaciones atribuíbles a los hechos.

La aplicación del método científico al campo social fué recibida con hostilidad por las tradiciones y los intereses establecidos, pero también fué cuestionada por los críticos sociales, que en general la vieron como una estrategia inadecuada para el conocimiento y la solución de los problemas sociales. Las principales influencias intelectuales reconocidas por los críticos sociales son:

- El marxismo, en especial el denominado "humanismo marxista" derivado de los escritos del Marx jóven sobre la alienación del trabajador respecto de su producto, etc.
- La teoría psicoanalítica,en especial esa derivación llamada (bastante impropiamente) "neofreudismo", que quizás por influencia del ideario socialista de Alfred Adler, prácticamente invierte las concepciones sociales de Freud.
- La filosofía de Hegel, en particular su enfoque metodológico.

Los críticos sociales en general cuestionan la ciencia,tienden al relativismo y opinan que el hombre ha de estar comprometido en la acción, y que el conocimiento se alcanza por participación. En IDEOLOGIA Y UTOPIA, de Karl Mannheim^[Note: Ver Karl Mannheim: IDEOLOGIA Y UTOPIA - Madrid - Aguilar - 1973.], encontramos un buen resumen de los cuestionamientos metodológicos de este grupo, en el que aproximadamente pueden incluírse autores como Barrington Moore, Irving Louis Horowitz, Maurice Stein, Arthur Vidich, Erich Fromm, Harry Stack Sullivan, Karen Horney, David Riesman, Norman Brown, Herbert Marcuse, etc. Entre sus argumentos básicos se destacan los tres puntos siguientes:

- La afirmación de que todo conocimiento es relativo a la situación social, y especialmente a la situación de clase;
- La tendencia a concentrarse en la fuente del conocimiento o en los medios para adquirirlo más que en los procedimientos de verificación;
- La estrecha relación que -se supone- existe entre crítica social y participación.

Para Mannheim (que lo toma de Marx) el observador social es un partícipe necesario de los procesos que observa. La teoría surge de un impulso social y clarifica la situación en que el impulso surgió. En ese proceso de clarificación,la teoría sirve para modificar la situación, y de ese cambio surge la exigencia de una nueva teoría. Es un interesante empleo de la dialéctica hegeliana, que niega la existencia de "teorías puras" y afirma que "toda forma de pensamiento histórico y político está esencialmente condicionada por la situación vital del pensador y su grupo". La teoría, pues, no puede separarse de la acción. Este enfoque podría llevar a un relativismo total y a un activismo devoto, situación que Mannheim intenta evitar, destacando por una parte que el pensamiento se ilumina "no solo mediante la acción sino también mediante la reflexión que ha de acompañarla; y recurriendo, por otra parte, como tipo ideal de investigador al"intelectual desarraigado", de tenues vínculos de clase, poco condicionado por la ideología de su grupo y por ende, menos parcial.

Aún así, la posición de Mannheim permanece demasiado adscripta a un subjetivismo activista, que abre las puertas a interminables discusiones sobre la parcialidad subyacente en las explicaciones científicas de la política. En opinión de Meehan "...desde el punto de vista metodológico, la doctrina (de Mannheim) simplemente no funciona".

Meehan concluye su tratamiento del tema recordando unas palabras de Anatol Rapoport^[Note: Anatol Rapoport:"The Scientific Relevance of C. Wright Mills" en Horowitz I.: THE NEW SOCIOLOGY pg. 107.]: "La ciencia, con su actitud de desinterés, es el único modo de conocimiento de que disponemos que permite hacer productivos los choques entre opiniones incompatibles y que permite poner de manifiesto el grado de incompatibilidad entre opiniones distintas. De aquí que no se pueda prescindir del análisis lógico, la extensión de los conceptos, la comprobación de las hipótesis y todo lo demás si deseamos que el choque entre pensadores serios engendre luz además de calor".

Nos ha parecido necesario hacer estas consideraciones introductorias al tema de la Teoría Política, para que se comprenda claramente el panorama que presenta en la actualidad el campo científico social, y particularmente el político, que es dentro del cual se van a inscribir todos los desarrollos posteriores. Comenzamos haciendo notar la amplitud de uso del vocablo TEORIA en este campo, y su relación con los problemas metodológicos.

Tres ideas emergen de allí con claridad:

- La independencia de la ciencia respecto del problema de la "verdad", en sentido religioso o filosófico;
- Su sentido y valor como ordenador de la experiencia humana concreta en el mundo;
- Su carácter relativo y condicional, por estar construída con generalizaciones inductivas.

En una expresión aún más sintética, podemos decir que la ciencia es una tarea humana que construye un "sistema abierto de conocimientos". Esta tarea ha recibido críticas. Algunas de ellas, en nuestra opinión, deben ser desechadas porque la critican o la niegan queriendo que la ciencia sea lo que no es. Otras sí deben ser tenidas en cuenta porque expresan dimensiones que pueden mejorarse en la actual y futura construcción y reconstrucción de la ciencia. En particular, dos enfoques aparecen claramente como valiosos:

- La comprensión ("Verstehen") de la representación interior del valor de los actos humanos como complemento insoslayable de la observación sistemática de su manifestación interna.
- El compromiso con la acción, superadora de la situación social que la teoría clarifica, pero sin perder la "actitud de desinterés" que diferencia a la ciencia de la ideología.

Este enfoque sobre las características y el valor humano de la Ciencia y la Teoría intenta ser amplio y realista a la vez. En nuestra opinión, él explica el criterio que ha presidido la construcción del "panorama general de la Teoría Política" que pretendemos presentar en los próximos capítulos. Hemos delimitado un vasto campo: colinda por una parte con la Filosofía Política y por otra con la política práctica; tiene otro límite en la ideología y el restante en las ciencias del hombre. Tiene, además, amplias franjas de interacción en todos esos rumbos.

Dentro de él hay lugar para muchas "lecturas científicas" de la realidad política; en él se han levantado muchos edificios teóricos sobre diferentes fundamentos metodológicos y cosmovisionales.

Esa "ciudad de la Política pensada", construida pacientemente por los hombres de muchos lugares a lo largo de muchas centurias, es lo que intentaremos describir aquí, posando una mirada comprensiva y -si se nos permite- afectuosa sobre el esfuerzo pensante de tantas generaciones. Por eso aquí están los planteos estructural-funcionalistas y sistémicos de la Teoría Política occidental; los enfoques crítico-dialécticos, en la amplia gama de sus manifestaciones teórico-prácticas; y los estudios normativos, desde Sun Zi hasta Platón, desde Aristóteles hasta Maquiavelo, desde Santo Tomás hasta Bertrand de Jouvenel.

Todos tienen algo que decirnos, algo que enseñarnos, y merecen nuestro respeto aunque nos parezcan equivocados.

La Ciencia,en su sentido más amplio y profundo, no es solo saber sino también comprender; no es solo conocimiento sino también sabiduría y aunque no es una mera receta técnica ni su finalidad se agota en la aplicación práctica, también ilumina el camino y orienta las acciones en la "ciudad de la política vivida".