# Las teorías normativas  {#Lasteoríasnormativas}

```{r, eval=knitr::opts_knit$get("rmarkdown.pandoc.to") == "html", results='asis', echo=FALSE}
cat('<hr style="background-color:#03193b;height:2px">')
```

Primera parte: 

- Rasgos generales: Condiciones históricas y trasfondos ideológicos 
- Clasificación de las teorías normativas 
- Raíces intelectuales 
- Fundamentos 
- Finalidad
- Relaciones 
- Metodología.

Segunda parte:

- Teorías políticas normativas clásicas: chinas, hindúes, judías, islámicas, griegas, romanas, medievales y modernas.

Tercera parte:

- Teorías políticas normativas contemporáneas: El asalto al absolutismo 
- Las consecuencias de la Revolución Francesa 
- Socialismos y nacionalismos 
- Las teorías normativas actuales.

Cuarta parte:

- Enfoques metodológicos usuales: Métodos: histórico, analógico, práctico, tópico, pedagógico. 
- El pragmatismo metodológico.

## Primera parte {-}

### Rasgos generales {-}

En general puede decirse que las obras de la gran corriente teórica normativa intentan, como toda teoría, describir y explicar los fenómenos de la vida política, pero ellas lo hacen poniendo el acento en lo que la política puede o debe ser, razón por la cual se aproximan fuertemente a la Filosofía Política, hasta confundirse con ella en algunas ocasiones. En todo teoría de esta corriente siempre subyacen preguntas tales como: Cuál es el mejor régimen político? o Cuál es el mejor régimen político posible? Estas teorías están siempre en relación con lo que se piensa que puede esperarse de la convivencia humana; y con el sentido de la vida que tenga cada autor y cada época según su particular cosmovisión. Transitamos, como puede verse, por un ámbito de fuerte vocación filosófica.

Las teorías de todo tipo son siempre producto del trabajo intelectual humano, en el marco de condiciones históricas objetivas y de trasfondos cosmovisionales de naturaleza fundamentalmente ideológica. Esto es particularmente visible en el caso de las teorías normativas, a tal punto que su mejor clasificación la proporciona la Historia de las Ideas Políticas. Podemos hablar así de teorías políticas normativas clásicas y de teorías contemporáneas. Las clásicas abarcan la producción de la Antigüedad (Grecia, Roma y Edad Media, en Occidente) y de la Modernidad (siglos XV a XVIII). Las contemporáneas son las originadas a partir del siglo XVIII. Todo esto se refiere al marco de la cultura occidental. Algo similar, con algunas diferencias, encontramos en el pensamiento político chino e hindú, como veremos más adelante.

Las teorías políticas clásicas antiguas abarcan el período mencionado porque en el pensamiento político hay continuidad y no ruptura entre el mundo greco-romano y el medieval. En cambio, sí hay marcadas diferencias entre aquellas obras y las que se producen en Occidente en la Edad Moderna, o sea desde el surgimiento de las naciones-estado (siglo XV).

Otro cambio importante encontramos en las obras de los siglos XVIII a XX, tras ese profundo cambio del principio de legitimidad que trajo consigo la difusión del ideario antiabsolutista.

En definitiva, creemos que podemos esquematizar el siguiente cuadro de clasificación de las teorías normativas: CLÁSICAS ANTIGUAS MODERNAS CONTEMPORÁNEAS ASALTO AL ABSOLUTISMO CONSECUENCIA DE LA REVOLUCIÓN FRANCESA SOCIALISMOS Y NACIONALISMOS ACTUALES Las teorías políticas antiguas se presentan como expresiones de filosofía práctica, en las que se entrecruzan las especulaciones racionales con las observaciones de la experiencia histórica y del devenir cotidiano. Procuran configurar doctrinas de la vida justa y buena, muy vinculadas a la Ética. En general entienden que la Ética es la visión estática y la Política es la visión dinámica del mismo objeto. Estas teorías se refieren a fenómenos que no son del "episteme", o sea de los determinismos naturales, sino del campo de las opciones conscientes de los hombres, en las que lo esencial es lograr la "phronesis", es decir, la cabal comprensión de la situación para actuar con lucidez y mesura, algo que también expresa el significado latino originario de la "prudentia".

Entre los saberes humanos, la Política ocupa el lugar más prominente en el pensamiento clásico, como ciencia práctica, ciencia del hacer ("prattein"), no de la especulación teórica ("theorein") como la Lógica y la Matemática, ni de la creación ("poiëin") como la Retórica, la Música o la Poesía.

El objetivo del saber político clásico no es solo el logro de la supervivencia sino la búsqueda de la seguridad de una vida buena,en libertad y virtud. No la hacían extensiva a todos, por supuesto (consideraban, por ejemplo, que la esclavitud era algo natural) pero ello no debe extrañarnos: siempre los hombres han racionalizado sus necesidades...

Con el agregado del mensaje escatológico cristiano, esta tendencia se prolonga en el pensamiento político medieval, para el que el objetivo final de la comunidad política es permitir la marcha de la vida tras la virtud; en definitiva, es una larga meditación sobre las condiciones del bien común, entendido como conjunto de las condiciones socio-políticas que coadyuvan a la realización de la finalidad transpolítica del hombre: la salvación de su alma. Este esquema, con variantes individuales, es una constante en el pensamiento político antiguo.

A fines de la Edad Media y principios de la Edad Moderna se produjo una variación fundamental. La emergencia de los estados-naciones estuvo signada por cruentas guerras civiles, y en el pensamiento político el sistema de fines suprapolíticos fue sustituido por un sistema de supervivencia. El máximo objetivo político pensable parecía ser la simple seguridad de la existencia. Se produjo entonces una marcada separación entre Política y Ética, y se realiza con Maquiavelo una acabada exploración de las posibilidades técnicas de mantener una comunidad política, proceso que culmina en la formulación de la teoría de la razón de Estado, respaldo poderoso del absolutismo.

La etapa de las teorías políticas contemporáneas comienza con el asalto ideológico al absolutismo, obra principalmente del pensamiento político racionalista liberal. Es común denominador de estas primeras obras la reflexión sobre el equilibrio del poder y la libertad, y sobre el encauzamiento de la participación política acrecentada. El hecho culminante originado en este pensamiento fué la Revolución Francesa que al cumplirse originó obras de ampliación y esclarecimiento, y también obras de reacción crítica.

La segunda mitad del siglo XIX y los primeros años del siglo XX se caracterizan por obras que marcan la emergencia de los socialismos y los nacionalismos, en una atmósfera ideológica en general opuesta, por diversos motivos, a las ideas de 1789.

La experiencia socio-política emergente de la crisis económica de 1929, el surgimiento de los totalitarismos de derecha e izquierda y la Segunda Guerra Mundial configuran el marco fáctico originario de las obras normativas "actuales". Son éstas las que más nos interesan aquí, por su vigencia y por reflejar las condiciones de nuestro tiempo. Siguiendo en esto a von Beyme^[Klaus von Beyme: op. cit.] vamos a sintetizar así sus principales características comunes: * Raíces intelectuales: La mayoría intenta restaurar la clásica teoría aristotélica de la política, en una nueva lectura influida por el relativismo de los valores, la quiebra de las antiguas democracias y la aparición de las dictaduras totalitarias del siglo XX. Tienen un fuerte interés en los estudios de historia de las ideas políticas. Destacan los valores supratemporales de las antiguas teorías políticas y procuran basarse en ellas. Están evidentemente dominadas por el "realismo conceptual" y la pasión hermenéutica, y revelan un cierto conservadurismo en su apego al significado originario de los conceptos y su rechazo a los neologismos.

- Fundamentos filosóficos: Son sumamente variados. Van desde el tomismo hasta el conservadurismo escéptico. Después de la Segunda Guerra Mundial no han aparecido teorías normativas con fundamento religioso.

La mayor parte de estas teorías basan sus desarrollos en alguna ontología. Avanzan por medio de conceptos hacia la construcción de una visión sistematizada, basándose en alguna ontología deductiva, de inspiración humanística teocéntrica o antropocéntrica. En general aceptan la hipótesis de la "verdad objetiva", aunque discrepen en los métodos para acercarse a ella o reconocerla.

- Finalidad: Su finalidad cognoscitiva es la acción, no el conocimiento en sí mismo. La Teoría Política Normativa, como ciencia práctica, apunta a perfeccionar la gestión política. Los autores que militan en esta corriente se oponen a la separación positivista y neokantiana entre el ser y el deber ser de la Política. Atribuyen a esa separación la falta de educación política y la generalización de la inmadurez política de gobernantes y gobernados.

Estas teorías acentúan la importancia de las teorías del gobierno y de la administración, en detrimento de los temas relacionados con la participación pública. A veces manifiestan una tendencia a la evasión hacia el esteticismo, tendencia que, por otra parte, comparten con muchos teóricos dialécticos de izquierda, desde Adorno hasta Marcuse.

- Relación con otros enfoques: Muchos teóricos normativistas conciben a la Teoría Política clásica como un medio para liberarse "del rigor de los juristas, la brutalidad de los técnicos, la vaguedad de los visionarios y la vulgaridad de los oportunistas" (Leo Strauss).

Estas teorías en general alientan un fuerte escepticismo sobre el valor real que pueda tener la acumulación de datos pormenorizados, al estilo positivista o empirista. Tienen, en cambio, algunos puntos en común con los enfoques críticos de la nueva izquierda: la oposición al neopositivismo, la finalidad del conocimiento orientada a la acción, etc. Por su parte, suelen recibir desde la izquierda el reproche de que pretenden construir una teoría finalista pero que no define su finalidad, y que termina adhiriendo en la práctica al sistema vigente y al statu-quo.

- Metodología: Las teorías normativas han aportado poco a la investigación empírica. Su enfoque metodológico no es semejante al de las ciencias naturales (medición, explicación causal, generalización) sino similar al de las ciencias prácticas, como la jurisprudencia, la terapéutica o la educación, que parten de problemas individualizados, o sea de la casuística, y tratan de resolverlos en base a reglas generales y precedentes. Son muy escépticas respecto del valor de los modelos abstractos y las teorías de alcance medio, y en especial de la teoría sistémica. Prefieren las teorías históricas (genésicas), los estudios de casos y las monografías prescriptivas. Frente a los intentos de reducción de los procesos políticos a otros tipos de variables, tales como las clases sociales, las condiciones tecnológicas o de producción, etc., son decididas partidarias de la autonomía de la política y de la "política pura".

En cuanto al lenguaje, los autores de esta corriente mantienen una relación estético-normativa con el idioma. En general escriben con un estilo depurado, elegante, consumado; y rechazan el vocabulario tecnicista de los neopositivistas.

En síntesis, podemos decir que las teorías normativas han promovido el estudio de las ideas políticas; que han hecho sugerencias valiosas sobre temas significativos para la investigación empírica; y que su aporte es muy importante para neutralizar la irracionalidad en los planteos del deber ser.

Pese a sus limitaciones, aún en medio de la polémica con los empiristas, la originalidad y erudición de los normativistas es siempre digna de respeto, ya que en ocasiones alcanzan niveles de "sabiduría política", de innegable valor.

No disponemos en esta obra de espacio para un tratamiento exhaustivo del tema. El lector interesado puede consultar la buena bibliografía existente sobre Historia de las Ideas Políticas^[Ver, por ejemplo: G.H. Sabine: HISTORIA DE LA TEORIA POLITICA - México - FCE- 1984 J.J. Chevalier: LOS GRANDES TEXTOS POLITICOS - DESDE MAQUIAVELO HASTA NUESTROS DIAS - Madrid - Aguilar - 1979; y muy especialmente: F.Chatelet, O.Duhamel y E.Pisier: DICTIONNAIRE DES OEUVRES POLITIQUES - Paris - PUF - 1989.].

### Teorías políticas normativas clásicas {-}

El pensamiento político clásico se caracterizó siempre por una intensa combinación de elementos de orígen filosófico especulativo y elementos de observación empírica provenientes de la experiencia vivida por los pueblos a través de la historia. De allí proviene el tono sorprendentemente moderno y hasta científico, en el sentido actual del término,que encontramos en tantas obras del pensamiento político, en el que también podemos abrevar algo que muchas veces echamos de menos en las creaciones del genio científico contemporáneo: la sabiduría y la comprensión de la política.

Este no es, desde luego, un libro de historia del pensamiento político. Las exigencias del espacio nos obligan, pues, a un programa suscinto: una ennumeración de las obras principales y el comentario más detallado de algunas obras especialmente representativas de los diversos períodos. Vamos a comentar, eso sí, algunas obras poco citadas en la bibliografía especializada, para hacer un aporte que no sea reiterativo. Asímismo, vamos a tratar de no incurrir en esa centración en Occidente de la que suelen adolecer muchas obras sobre la historia del pensamiento político; incluiremos, pues, consideraciones y referencias al pensamiento político no occidental.

Un listado de obras del pensamiento político universal que responda a dicho programa, debe mencionar al menos las siguientes:

a) Pensamiento político chino: Confucio: TRATADOS MORALES Y POLITICOS (s. V aC); Sun Zi: EL ARTE DE LA GUERRA (s. V aC).

b) Pensamiento político hindú: (Atribuído a Manú): MANAVA DHARMASASTRA (?); Kautilya: ARTHASASHA (?).

c) Pensamiento político judío clásico: (Atribuído a Moisés): PENTATEUCO (?) Maimónides: GUIA DE LOS EXTRAVIADOS -- COMENTARIO SOBRE LA MISHNAH -- MISHNEH TORAH -- (1200 dC) d) Pensamiento político islámico clásico: Mahoma: CORAN (610-632); Ibn Taymiqya: TRATADO DE POLITICA JURIDICA (1311-1315); Ibn Khaldun: PROLEGOMENOS A LA HISTORIA UNIVERSAL (1375-1379).

e) Pensamiento político griego clásico: Tucídides: HISTORIA DE LA GUERRA DEL PELOPONESO (s. V aC); Platón: LA REPUBLICA - LAS LEYES- EL POLITICO (s. IV aC); Aristóteles: POLITICA (s. IV aC).

f) Pensamiento político romano clásico: Cicerón: DE LA REPUBLICA (55aC); Séneca: CARTAS A LUCILIUS (65aC).

g) Pensamiento político medieval: San Pablo: EPISTOLAS (65dC); San Agustín: LA CIUDAD DE DIOS (413-426dC); Santo Tomás de Aquino: SUMA TEOLOGICA (1266-1273); Dante Alighieri: DE MONARQUIA (1310); Marsilio de Padua: EL DEFENSOR DE LA PAZ (1324); Guillermo de Ockham: LA MONARQUIA DEL SACRO IMPERIO ROMANO (1349); Jan Hus: DE ECCLESIA (1415).

h) Pensamiento político moderno: N.Maquiavelo: EL PRINCIPE (1513); DISCURSOS SOBRE LA PRIMERA DECADA DE TITO LIVIO (1513-1519); T. Moro: UTOPIA (1516); M. Lutero: A LA NOBLEZA CRISTIANA DE LA NACION ALEMANA SOBRE LA ENMIENDA DEL ESTADO CRISTIANO (1520); J. Calvino: INSTITUCION DE LA RELIGION CRISTIANA (1536); E. de la Boetie: DISCURSO SOBRE LA SERVIDUMBRE VOLUNTARIA (1548); San Ignacio de Loyola: LAS CONSTITUCIONES DE LA COMPAÑIA DE JESUS (1556); T. de Bèze: DEL DERECHO DE LOS MAGISTRADOS (1574); J.Bodin: LOS SEIS LIBROS DE LA REPUBLICA (1576); H. Languet: REIVINDICACIONES CONTRA LOS TIRANOS (1579); T. Campanella: LA CIUDAD DEL SOL (1602); F. Suarez: DEFENSIO FIDEI (1613); Grotius: DERECHO DE LA GUERRA Y DE LA PAZ (1625); A-J. du Plessis, cardenal de Richelieu: TESTAMENTO POLITICO (1632-1639); R.Descartes: CARTAS A LA PRINCESA ISABEL (1643-1649); B.Pascal: PENSAMIENTOS (1662); S. Pufendorf: DERECHO NATURAL Y DE GENTES (1672); G. Leibniz: DEL DERECHO DE SOBERANIA Y DE EMBAJADA DE LOS PRINCIPES DEL IMPERIO (1677); J. Bossuet: LA POLITICA SACADA DE LA SANTA ESCRITURA (1677-1709); F. de Salignac de la Mothe (Fenelon): TELEMACO (1699); G. Vico: EL METODO DE ESTUDIOS DE NUESTRO TIEMPO (1709); Ch. I. Castel, abad de Saint-Pierre: PROYECTO DE PAZ PERPETUA (1713); F. Voltaire: CARTAS FILOSOFICAS (1734); Chr. Wolff: PRINCIPIOS DE DERECHO NATURAL Y DE GENTES (1758).

Como puede verse, el criterio amplio utilizado en esta selección ha hecho incluir en ella obras que admiten más de una lectura. La Torah y el Corán, por ejemplo, tienen contenidos de teoría política normativa, pero son ante todo libros religiosos fundamentales; los libros sobre Derecho Natural son obras filosófico-jurídicas con contenido político, etc. Vayamos ahora a la descripción más detallada de estas corrientes de pensamiento y de sus obras más representativas. 

## Segunda parte {-}

### El pensamiento político chino {-}

No se trata de satisfacer aquí un gusto erudito por la erudición misma. Se trata, por un lado, de romper el esquema intelectual euro-céntrico (algo muy necesario en esta época de comunicación planetaria); y por otro de allegar información necesaria: no se puede, por ejemplo, comprender el marxismo maoísta y sus posteriores evoluciones sin conocer el sustrato cultural sobre el que está construído.

La organización política china clásica estuvo muy influída por el pensamiento filosófico, así como la filosofía china estuvo muy acotada por preocupaciones sociales y políticas, en sus fines y problemas. En el pensamiento político chino clásico encontramos dos corrientes principales y muy diferentes entre sí: el confucianismo (JU-CHIA) y el legalismo (FA-CHIA), que en la praxis política luego se unieron en una curiosa convergencia^[Luigi Pareti et al.: HISTORIA DE LA HUMANIDAD - DESARROLLO CULTURAL Y CIENTIFICO - Tomo II - (Unesco) - Bs.As. - Editorial Sudamericana - 1969.].

Confucio (551-479 aC) se basó en el modelo de la sociedad de su tiempo, de estructura feudal, planteando para ella una política basada en altos principios morales: el "entendimiento de lo justo" y una escala graduada de afecto y respeto que está formada por las "cinco relaciones": afecto entre padre e hijo, respeto entre gobernante y gobernado, amor entre marido y mujer, afecto entre hermano mayor y menor, lealtad entre amigos. Esa escala es la base del Estado, concebido esencialmente como un ente moral.

La elevada conducta moral del gobernante -sostiene Confucio- obliga a los gobernados a comportarse del mismo modo. Un Estado realmente bien organizado no necesita leyes ni policía ni tribunales. Si prevalecen la violencia y el crimen, la culpa es del gobernante que no da un ejemplo elevado. Esa es la diferencia entre el soberano legítimo (WANG) y el tirano (PA). El tirano, en la concepción confuciana, pierde moralmente su derecho a gobernar y el pueblo adquiere el derecho de rebelarse y derrocarlo.

El ideal político confuciano busca su fundamento remontándose míticamente al más remoto y venerable pasado, pero no es una teoría conservadora sino revolucionaria, que rechaza las precariedades y violencias del presente y del pasado próximo y evoca una "edad de oro" idealmente reconstruída y proyectada hacia el futuro.

Estos elevados principios chocaron muy frecuentemente con la dura realidad de las convulsiones sociales y la violencia de los estados feudales guerreros. El confucianismo intentó entonces ciertas formas de adaptación. Esa fué la obra de Hsün-Tzu (s.IIIaC) quien partió de la idea de la maldad intrínseca de la naturaleza humana para afirmar la necesidad de formular normas de conducta (LI), las que no son, de todos modos, leyes positivas coactivas sino un código de conducta, de cumplimiento obligado por el conformismo social pero sin sanción penal.

En el siglo IIIaC, por obra de Han-Fei-Tzu, surgió otra escuela de pensamiento político: el legalismo (FA-CHIA), muy opuesta a la anterior. Considera que la naturaleza humana es mala y que el hombre actúa bien solo bajo el acicate de la recompensa y la amenaza del castigo. Por su parte, afirma que las tradiciones del pasado carecen de valor porque "a medida que las condiciones del mundo cambian se practican principios diferentes".

El Estado -sostiene Han-Fei-Tzu- debe ser gobernado por medio de un claro y preciso conjunto de leyes (FA) que explique lo que se debe hacer y el premio y el castigo por hacerlo o no. El gobernante tiene autoridad (SHIH) para premiar y castigar. No necesita ser sobrehumano: solo precisa conocer el arte del gobierno (SHU) para encontrar y dirigir un personal eficiente, que cumpla sus órdenes.

Aplicando las teorías legalistas se creó un Estado autoritario-militar en el noroeste de China, que pronto dominó al resto del país: fué el estado CH'IN. El exceso produjo un gobierno de hierro, de exasperado centralismo. La rebelión generalizada de la población barrió con la dinastía CH'IN; los doctrinarios del legalismo fueron muertos y sus libros fueron quemados.

La dinastía emergente (HANG), invocando el nombre del confucianismo, en realidad combinó ambas escuelas: fué un aparato estatal legalista manejado por confucianos. El Estado fué gobernado por funcionarios de carrera, que estructuraron un imperio burocrático-centralizado, manejado por personas de alta cultura literaria tradicional. La receta fué tán eficaz que duró dos mil años, hasta nuestro siglo, sobreviviendo en su aplicación bajo diversas dinastías y a traves de las más variadas vicisitudes históricas.

Durante esa larga historia, la guerra fué la principal ocupación de la nobleza china. En ese contexto nació una obra notable, que tuvo y tiene una gran influencia: EL ARTE DE LA GUERRA, de Sun-Zi (S. V-IV aC).

Nuestra cultura occidental -ya lo hemos señalado- es excesivamente eurocéntrica: Grecia, Roma, Edad Media...Pocas obras de otras culturas han logrado ejercer una influencia considerable en nuestro ámbito, y entre ellas se encuentra ésta, la más antigua obra de estrategia militar conocida, y sin duda una de las más notables. Los trece breves capítulos que la componen ocupan poco más de cien páginas, pero contienen, según autorizadas opiniones, como la de B. H. Liddel Hart, "la quintaesencia de la sabiduría sobre la conducción de la guerra".

Nada sabemos de su autor, Sun Zi, quien vivió bajo la dinastía HAN. En China y en Japón fué siempre tenido en alta estima, como puede verse por la cantidad y calidad de sus comentadores. A Occidente fué traído y traducido por el jesuíta francés J.J.M. Amiot, y publicado por primera vez en 1772. Tuvo luego una amplia difusión, multiplicándose las ediciones en francés, inglés, alemán y ruso.

Leyendo esta obra, enseguida surge el paralelo con Clausewitz, quizás el único teórico moderno que se le pueda comparar. Sin embargo, lo que Sun Zi escribió hace más de dos mil cuatrocientos años aparece hoy más claro, más profundo, más fresco. Tienen, por cierto, mucho en común: por ejemplo, ambos entienden a la guerra como emergente del orden político. "La guerra es asunto de importancia vital para el Estado -dice Sun Zi- fuente de vida y de muerte, camino que lleva a la sobrevivencia o a la aniquilación. Es indispensable estudiarla a fondo". Así comienza este tratado. Antes de pensar en la conducción de la guerra, Sun Zi establece su principio fundamental: la paz dicta su sentido a la guerra.

Antes que preocuparse por los problemas de técnica militar, que son epocales, Sun Zi se esfuerza por expresar la esencia de la estrategia militar en su relación con la política del Estado, que es lo permanente. Para Sun Zi, la guerra es una realidad inevitable, y aconseja limitar lo más posible su duración. Su tratado se refiere a la inteligencia de las relaciones de fuerza y al uso más racional (quiere decir, más económico) de las tropas. Busca conseguir la victoria por una combinación de astucia, sorpresa y desmoralización del adversario. Este último factor tiene la mayor importancia. Pocos teóricos de la guerra han enfatizado más la importancia de la guerra psicológica: el rumor, la intoxicación mental, la quintacolumna; sembrar la discordia entre el enemigo. corromper a sus cuadros jerárquicos, especialmente si son tropas mercenarias o generales de lealtad poco segura, etc.

Sun Zi considera que las guerras más mortales son las guerras de religión, las guerras civiles y las "guerras nacionales". Su idea de la guerra "política" se refiere principalmente a una guerra practicada en el seno de la misma sociedad, con medios y objetivos relativamente limitados, en el cuadro de reglas generalmente aceptadas: algo similar a los conflictos medievales europeos.

En sus principios generales para la conducción de la guerra, Sun Zi enfatiza la importancia de la moral y la cohesión de las tropas, y sobre todo de "la armonía del pueblo con sus dirigentes". Su estrategia se basa en el conocimiento del adversario, de sus concepciones y modos de obrar. "Es de la más alta importancia -dice- combatir la estrategia del enemigo". Aconseja tomar ventaja de los defectos de preparación del enemigo, evitar su fuerza y golpear su inconsistencia, hasta lograr un golpe decisivo. La guerra, cuanto más breve mejor, so pena de agotar también al vencedor. Es claro el eco que de estas concepciones pueden encontrarse, por ejemplo, en las obras de Mao sobre la guerra revolucionaria, como DE LA GUERRA REVOLUCIONARIA DE CHINA (1936) o DE LA GUERRA PROLONGADA (1938).

Sun Zi es un teórico no dogmático, consciente de la capacidad de adaptación a circunstancias imprevistas. "Así como el agua no tiene una forma estable, no existen en la guerra condiciones permanentes" -dice, y añade: "no hay que temer quebrantar las órdenes del soberano si la situación sobre el terreno lo exige". El coraje y el talento del jefe de la guerra se miden también por la capacidad de infringir las órdenes cuando se tiene la íntima convicción de poseer la llave táctica de una situación.

Lejos de alabar la guerra en sí, Sun Zi desea limitarla en el tiempo y hacerla menos costosa en medios y en hombres gracias al factor moral. Por ello desaconseja las guerras de sitio y aconseja las de movimiento, que juegan con el factor sorpresa y el punto débil del enemigo.

En esencia, el "Arte de la Guerra" es un tratado militar, que toma como postulados básicos una política prudente, un empleo mesurado de la fuerza, el uso de la inteligencia y de la astucia, combinadas con la firmeza de espíritu y la tenacidad. La obra de Sun Zi es una conceptualización genial de los conflictos militares. La guerra no es considerada en ella bajo su ángulo moral ni como un hecho accidental. Para Sun Zi, el problema de la guerra es central para el Estado, un acto consciente que puede ser analizado rigurosamente y cuyo sentido es dictado por la paz.

### El pensamiento político hindú {-}

La ley religiosa-social, o sea el DHARMA, que es algo distinto de la administración y la política, es el tema de una abundante literatura en la India. La obra más importante, al parecer, es el MANAVA DHARMASASTRA, atribuído a Manú, el primer hombre, la cual ejerció una enorme influencia jurídica, política y social en la vida del pueblo hindú. Se la ha conocido en Occidente con el nombre de CODIGO DE LAS LEYES DE MANU.

Según el MANAVA DHARMASASTRA hay cuatro fuentes de la ley: las Sagradas Escrituras, los libros legales, las costumbres de los hombres santos y el sentir íntimo del hombre sobre lo justo y lo injusto. La garantía de la ley es el castigo, graduado según la falta y según la casta del infractor.

Este es el libro que consagra el sistema de castas en la India. Los brahamanes ocupan todos los puestos dotados de ascendiente social y de poder político: sacerdote, maestro, juez, ministro, miembro de la Comisión Legislativa Permanente (DHARMA-PARISHAT). Sus delitos en general tienen penas más leves y nunca son condenados a muerte.

Los ksattriyas tienen el privilegio y el deber de hacer la guerra, con el carácter de una obligación religiosa. La guerra asumió un carácter ceremonial, con complejas reglas rituales, aunque la presencia de invasores extranjeros (que no respetaban las reglas) impidió que se transformara completamente en un rito. De todos modos, ese estilo "tradicional" y conservador de hacer la guerra aseguró el triunfo de todos los invasores que a lo largo de los siglos penetraron en el territorio hindú.

Los sudras son tratados duramente por las leyes de Manú, y se les reservan los trabajos y posiciones inferiores, pero no las actividades consideradas degradantes e "impuras", que están reservadas a los parias o "intocables", que están fuera del sistema de castas.

La India careció de una tradición unitaria y de una burocracia centralizada. Cada reinado tenía su propia organización, dentro de un modelo tradicional, del que en realidad poco se sabe. El Rey era jefe titular del Estado y también jefe del Gobierno. Era el centro de una vasta corte. Su gobierno se basaba en la sospecha sistemática, que daba trabajo a un ejército de espías y contra-espías, y hasta a una guardia de mujeres armadas, que controlaban el acceso a las habitaciones privadas. Los ministros formaban un cuerpo de consejeros y asesores que elegían a los funcionarios inferiores.

Una obra hindú que puede ser considerada de teoría política secular es el ARTHASASHA, atribuído a Kautilya, el ministro de quien se dice que fué el verdadero fundador del imperio Mauria. La forma de gobierno que allí se describe es una monarquía absoluta, en la que el poder real no está limitado por la costumbre, aunque el Rey está aconsejado por un conjunto de altos funcionarios, cabezas de la administración pública. El contacto con la opinión pública se mantenía por medio de un bien organizado sistema de espías y agentes secretos. Es un esquema político típico de pueblos dominados por invasores externos: el Estado no es una unidad sino un elemento de un conjunto, en cuyo centro está el conquistador, con su círculo de aliados ocasionales y de enemigos reales y potenciales. En ese contexto signado por la deslegitimación y la deslealtad, la política es un arte práctico, despojado de su dimensión moral. 

### El pensamiento político judío clásico {-}

El pensamiento político judío clásico está raigalmente vinculado al "libro" por antonomasia - la BIBLIA; y en particular a sus cinco primeros libros - la TORAH, como es nombrada por judíos y musulmanes, o el PENTATEUCO, según la denominación cristiana. Todas las tradiciones atribuyen su inspiración al Dios único, y su autoría material a un personaje algo histórico y algo legendario: Moisés ben Amram. El primer libro de la Torah -GENESIS- narra la creación del mundo y la genealogía de las familias humanas después de Adam y Eva, hasta la llegada de los hijos de Jacob a Egipto. Los otros cuatro libros -ÉXODO, LEVÍTICO, NÚMEROS y DEUTERONOMIO- relatan la actividad política de Moisés como profeta: organizador de la huída de Egipto, legislador de inspiración divina, jefe del campamento israelita durante los cuarenta años de la "travesía del desierto", creador de las bases ideales de la "ciudad de Dios" en la Tierra Prometida.

Las leyes de Moisés han constituido la referencia esencial de tres universos espirituales: judaísmo, cristianismo e islamismo; y la base ideal de los más diversos sistemas políticos. En el caso judío, ellos abarcan desde el gobierno militar de Josué, el régimen de los Jueces, los reinos de Saúl, David y Salomón, la conducción del retorno del cautiverio en Babilonia, el reino de los Macabeos, etc. Las leyes de Moisés son también el tema mayor de la exégesis de los Sabios, los Doctores de la Ley, luego Rabinos, en esa inmensa literatura omnicomprensiva de lo humano (y por consiguiente también política) que es el TALMUD, de Jerusalem y de Babilonia. La Torah ha servido también de motivación y bandera a todos los cuestionamientos sectarios, cismáticos o heréticos que se han alzado frente al poder ortodoxo de los Rabinos. Algo similar ha ocurrido en el ámbito cristiano y en el musulmán, de modo que a través de lecturas sucesivas y de etapas de interpretación, la Ley de Moisés, considerada como Palabra de Dios que utiliza a Moisés como portavoz, ha sido y es el fundamento ideal al cual se refieren los partidarios ortodoxos de las tres religiones monoteístas, así como también los cuestionadores de la autoridad temporal o espiritual de los cleros en el seno de cada una de las tres grandes familias religiosas.

El segundo libro de la Torah -EXODO- es el que contiene la Ley fundamental, los Diez Mandamientos; pero desde el punto de vista puramente político, los libros más densos son LEVITICO y NUMEROS, que enuncian en todos sus detalles las leyes, reglamentos, mandamientos y observancias revelados por mediación de Moisés a los israelitas. De allí surge la descripción de un sistema de gobierno y de organización social complejo y coherente, de un tipo relativamente único en esa región y en esa época: un estado sacerdotal y militar que emerge sobre un orden tribal que aún subsiste. Ese Estado-Ley legisla, prohíbe y reprime, pero oculta su monopolio de la violencia. Es Dios quien aparece castigando y exterminando a los rebeldes, y es la comunidad quien ejecuta por lapidación a los delincuentes, como contrapartida de la igualdad de todos ante el juicio de la Ley. La base de la ciudadanía no es la igualdad de condición sino la sumisión a la Ley y la participación en el consenso social.

Este poder de la Ley no reposa únicamente sobre el peculiar sistema de control social militar-policial de diseño cuadriculado (los jefes de mil, los jefes de cien, los jefes de diez) instaurado por Moisés, sino que se basa también en la existencia de una tribu-casta "consagrada al servicio de la Tienda", o sea del Arca de la Alianza, versión nómada del Templo.

Por medio del monopolio de los sacrificios (que implica también el control del consumo de carnes) y de la administración de justicia según la Ley, esa tribu-casta configura un régimen singular, fundado en una burocracia sagrada, que realiza una concepción del poder sacerdotal sobre bases religiosas. Ella opera como contrapeso de los poderes monárquicos o aristocrático-militares. El cuadro se completa con la acción de los Profetas, personas iluminadas, que hablan en nombre de la Divinidad, trasmitiendo sus mensajes en forma directa, sin intermediación de las instituciones sacerdotales establecidas; mensajes que con frecuencia presentan contenidos fuertemente críticos hacia el accionar de los gobernantes y del mismo pueblo. Se configura así una particularísima "división de los poderes" que frena las tentativas hegemónicas.

Entre los pensadores judíos importantes para la historia de las ideas políticas, quizás el más significativo sea Moisés Maimónides, cuyos escritos dejaron una impronta profunda en todo el pensamiento político posterior.

Moisés Maimónides nació en Córdoba (España) en 1135 o 1138. Estudió la Ley hebrea con su padre, y Filosofía y Ciencias Naturales con sabios musulmanes, en un período de feliz convivencia inter-religiosa, que pronto tuvo fin. Maimónides debió emigrar por la persecución religiosa desatada por los almohades, y vivió sucesivamente en Marruecos, Acre, Jerusalem y finalmente en El Cairo, donde fue el médico del visir de Saladino. Murió en dicha ciudad en 1204.

Como pensador político, Maimónides escribió:

- COMENTARIO SOBRE LA MISHNAH (1168): Escrito en árabe, es una explicación del gran código de derecho rabínico (la "Mishnah") que fué elaborado en el siglo III dC e incorporado al Talmud.

- MISHNEH TORAH (1180): Escrita en hebreo, es igualmente una tentativa de exponer las leyes talmúdicas de una manera clara y sistemática.

- GUIA DE LOS EXTRAVIADOS (1185-1190?): Obra magistral de Maimónides, escrita en árabe, examina el problema planteado por la filosofía griega a aquellos que creen en la Verdad Revelada.

Maimónides utilizó categorías conceptuales tradicionales, pero reinterpretadas de manera no tradicional, como puede verse en su redefinición de PROFETA, de la ERA DEL MESIAS y del OTRO MUNDO. Sostiene, por ejemplo, que solo un individuo intelectualmente perfecto (un filósofo, en definitiva) puede ser profeta, lo que en una óptica tradicional entrañaría una limitación a Dios en cuanto a la elección de quien desee como profeta. Otro ejemplo es el MESIAS, tradicionalmente percibido como una figura apocalíptica, propia del fin de los tiempos, y que es transfigurado por Maimónides en un jefe político que, sin cambiar nada en las leyes naturales, logrará la independencia política y la soberanía para los judíos en la tierra de Israel, lo que lo convierte en un remoto precursor del sionismo moderno. La vida en el OTRO MUNDO es vista por Maimónides como la unión del alma teorético-racional con el intelecto activo, realizable en forma individual, al margen de la redención colectiva, que era la concepción hebrea tradicional.

Maimónides utiliza fuentes religiosas tradicionales de una manera nueva. Pasa por alto las fuentes que no concuerdan con su punto de vista y acentúa la importancia de aquellas que refuerzan su posición, es decir, su propia comprensión filosófica del judaísmo. Por otra parte, desarrolla su pensamiento filosófico utilizando elementos filosóficos de origen no judío, sobre todo griegos e islámicos. Admira especialmente a Aristóteles, de quien decía que "su inteligencia representa el extremo de la inteligencia humana, excepto la de quienes han recibido inspiración divina"; y a Al-Farabi, cuyos AFORISMOS DEL POLÍTICO le hicieron afirmar que "todos sus escritos son irreprochablemente excelentes" y que "se los debe estudiar y comprender, porque es un gran hombre".

Maimónides procura siempre interpretar las informaciones bíblicas y post-bíblicas según razones naturales, consideraciones prácticas y explicaciones racionales, antes de apelar a lo milagroso. Intenta encontrar explicaciones racionales a todas las leyes del código judío, y dar razones educativas a casi todos los acontecimientos de la historia humana y natural. Por otra parte, a diferencia de pensadores árabes como Al-Farabi o Ibn-Ruchd (Averroes), que procuran elaborar sus teorías políticas en términos teóricos aplicables a todas las naciones y religiones, Maimónides mantiene su teoría política dentro del contexto del judaísmo.

El pensamiento político de Maimónides puede sintetizarse en dos áreas complementarias: una referida a la vida práctica, a la estructura político-social que recomienda para que sea adoptada por las comunidades judías; y otra referida a la estructura teórica de su pensamiento, donde se evidencian las influencias filosóficas no judías que experimentó.

Respecto del primer punto, Maimónides destaca la importancia y las responsabilidades que gravitan sobre los jefes comunitarios de todo tipo y nivel, cuyas cualidades para esas tareas se centran en la adquisición de la prudencia; y cuyas diferentes misiones o cometidos deben asegurar una división de poderes personales, que impida la emergencia de tentativas hegemónicas que irían en contra de la soberanía última de la Ley, entendida como expresión de la Voluntad Divina. En ese sentido, cabe considerar a Maimónides un lejano precursor de la "división de poderes" que varios siglos después postulara Montesquieu. El pensador judío que comentamos la fundamenta en la necesidad de preservar la primacía de la Ley contra la propensión arbitraria de los poderosos, por medio de una adecuada división de las funciones de conducción política.

En cuanto a la estructura teórica de su filosofía política, cabe mencionar los siguientes elementos: - La distinción entre la ELITE, o sea el pequeño número de los que realmente poseen la "virtud intelectual", y la MULTITUD de la gente ordinaria, que es vista como "enferma del alma", con características animalescas, cuyo sentido de vida es servir y acompañar a los sabios. Es notoria la influencia de Platón y de Al-Farabi en esta concepción de la sociedad.

- El análisis del conflicto entre el compromiso comunitario y la contemplación metafísica solitaria. Sus planteos no carecen de ambigüedad en este aspecto, pero en definitiva sus escritos y su ejemplo personal reconocen que el compromiso comunitario es parte importante de la actividad del individuo virtuoso y perfeccionado. Aún así, en páginas de cálida y espontánea humanidad, lamenta que sus múltiples ocupaciones, sus diarias tareas de médico de la Corte y sus tareas vespertinas de consejero de la comunidad judía de El Cairo, le dejen tán poco tiempo para sus escritos y sus meditaciones...

- El estudio de la fuerza y la debilidad de la Ley religiosa como encuadre de las acciones del pueblo judío. Es la Ley quien organiza la vida política del pueblo judío como un conjunto. Solo unos pocos individuos en cada generación pueden vivir según los principios de la Razón. Para todos los demás, la Religión brinda una guía irreemplazable. La soberanía última de la Ley debe ser defendida y preferida, aún en contra de la soberanía del más sabio de los gobernantes.

En síntesis, podemos percibir una "continuidad en el cambio", una actualización de la misma esencia, entre las concepciones políticas de la tradición hebrea antigua, raigalmente basadas en las palabras sagradas de la Torah, y las concepciones extrañamente modernas (en pleno siglo XIII) de este profundo pensador político judío, nutrido de cultura griega e islámica, que alza la primacía de la Ley contra la arbitrariedad de los gobernantes y propone una división de funciones de gobierno, de sabor cuasi-constitucional, para evitar las hegemonías personales de los hombres, siempre propensos a desbordar los marcos de la prudencia... 

### El pensamiento político islámico clásico {-}

El Corán es una obra de pensamiento político normativo...y es también mucho más que eso. El Corán recoge las revelaciones que Alah hizo al profeta Mahoma, principalmente por intermedio del Arcángel Gabriel, en las ciudades de La Meca y Medina, en Arabia, entre los años 610 y 632 dC según nuestro calendario.

A los ojos de los creyentes en el Islam, este mensaje cierra el ciclo de la profecía monoteísta, que en un arco ascendente va desde Adam a Noé, a Abraham, a Moisés, a David, a Jesús, para culminar en Mahoma, a partir del cual una línea recta (que a veces se corta porque los hombres son aún atraídos por el Mal) impulsa a la Historia hacia la Parusía como meta final del devenir del hombre.

La estructuración del Corán en capítulos, suras, etc., data verosímilmente del siglo X de nuestra Era, y no se corresponde con el orden en que las suras fueron reveladas. La sura 96 es considerada la primera según la tradición, y fué revelada a Mahoma cuando meditaba en la gruta del monte Hira. La tradición musulmana ha indicado al comienzo de cada sura si ella fue revelada en La Meca o en Medina.

A diferencia de la Torah hebrea, o del Antiguo y Nuevo Testamento cristianos, el Corán no es una crónica de acontecimientos, ni una recopilación de jurisprudencia, sino un conjunto integral de normas de vida (política, social, familiar, religiosa, etc.) para los musulmanes. La lucha del Profeta Mahoma por imponerse y por imponer el mensaje de Alah en el mundo árabe hizo del Corán un texto político, vale decir, le dió énfasis a la dimensión política de una concepción religiosa que tiene una vocación omniabarcativa respecto de la existencia humana, en todas sus dimensiones físicas, anímicas y espirituales.

En esa lucha por conquistar a los árabes "contra ellos mismos" la Profecía se convirtió en Código. La expansión vertiginosa del Islam sobre diversos territorios y pueblos transformó el proyecto escatológico en sistema político-jurídico. A diferencia del Cristianismo, el Islam no es "mahometanismo" sino "coranismo". El Corán no tiene, como la Torah o los Evangelios, un status ambiguo en el plano político. En el caso del Islam, su rol es bien claro: se trata de generar una "praxis", o sea de configurar actitudes mentales y sociales coherentes a partir de un texto inmodificable, cuyo carácter totalizador es indispensable a los fines de su comprensión y aceptación, y que produce muy rápidamente instituciones uniformes, basadas en prescripciones intangibles, sobre los más diversos medios geográficos y sustratos culturales.

Los occidentales en general entendemos mal al Islam, porque tendemos a "separar lo que está unido" (como nos dicen los musulmanes) y a sobrentender la autonomía relativa de lo político. El Corán no es socialista, ni democrático ni reaccionario. Es el vector espiritual a traves del cual el creyente cumple su propia ascensión en un mundo que tiene un orden y un sentido, es decir, un FIN, en su doble significado de meta u objetivo y de cierre o conclusión. Ante sus propios ojos, los pueblos islámicos forman la comunidad ("UMMA") depositaria y portadora de la última y definitiva expresión de la Voluntad Divina, comunidad que debe mostrar a la Humanidad entera el horizonte de la Salvación.

En esa comunidad, la misión de los sabios ("ulama") es instruir y guiar al pueblo: asumir la enseñanza y la dirección político-religiosa de la sociedad. Los intelectuales realizan esa misión, a veces hasta el extremo del martirio por la defensa de la estricta ortodoxia, y a veces se apartan de ella, o la interpretan de un modo muy personal, hasta llegar a "traicionarla" (al menos desde el punto de vista de esa misma ortodoxia). En el mundo cultural musulmán, Ibn Taymiyya e Ibn Khaldun son considerados arquetipos históricos de esas dos actitudes.

Ibn Taymiyya nació en Harran (Siria) en el año 1263 dC, en el seno de una familia de teólogos de la escuela hanbalita, o sea una de las cuatro escuelas que integran la ortodoxia musulmana (el "sunnismo"), la cual fué fundada por Ibn Hanbal en 855 dC. El padre de Ibn Taymiyya dirigía una "madrasa" (escuela religiosa) en Damas, cuya dirección heredó nuestro autor. Desde muy joven fue éste un teólogo y jurisconsulto notorio. Ibn Taymiyya se caracterizó por su intransigencia en materia de derecho musulmán y su constante resistencia a las autoridades que se marginaban de la ortodoxia musulmana. Como cabal hanbalita que era, su pensamiento y su acción estuvieron marcados por el respeto extremo a la tradición coránica y profética, en la que la ciencia del derecho y la ciencia teológica convergen en lo concreto de la existencia animada por una fe vivida, basada en el mantenimiento monolítico de la tradición y el respeto incondicional al texto escrito, pero también abierta a las aspiraciones del espíritu y del corazón, a los valores de la justicia, la sinceridad, la rectitud en la acción, privilegiando en definitiva el espíritu del texto frente a las interpretaciones interesadas o forzadas.

Ibn Taymiyya fue un luchador de la "gran jihad", la lucha interna contra los defectos y fallas que separan entre sí a los musulmanes. Por sus denuncias y críticas fué puesto en prisión varias veces (cinco, según sus biógrafos). Murió en prisión, en Damas, en 1328. Se comprende que esta figura sea hoy el modelo que, por su pensamiento y acción, inspira a los movimientos fundamentalistas, a los islamistas militantes, a los combatientes radicalizados que llamamos "integristas", y que sus obras no perdidas, especialmente las "Fatawa", hayan sido reiteradamente editadas después de 1970 por la Arabia Saudita.

La actualidad de Ibn Khaldun es de otra naturaleza: él es el centro de una polémica entre teólogos modernistas y tradicionales, porque este autor aparece como un singular precursor del pensamiento moderno, de la dialéctica, del positivismo (mucho antes que Hegel y Comte), del materialismo (varios siglos antes que Feuerbach y Marx) y de la Sociología moderna; autor, entre otras cosas, de una visión holística de la historia, cual si fuera un Spengler o un Toynbee extraviado por una máquina del tiempo en el siglo XIV...

Ibn Khaldun nació en Tunes, en 1332 dC, en el seno de una familia de origen sevillano. Recibió una esmerada educación por parte de grandes maestros musulmanes. Viajó largamente por el mundo musulmán de su tiempo: Fez, Granada, Biskra, El Cairo, donde murió en 1406.

Su gran obra fué indudablemente su "Historia Universal" ("Kitab al-'Ibar" - 1379) cuya Introducción, conocida en Occidente como "Prolegómenos" ("Al-Muqaddima") contiene lo esencial de su pensamiento político.

El esfuerzo intelectual de Ibn Khaldun, testigo presencial y casi premonitorio del comienzo de la decadencia árabe, luego de su vertiginosa expansión, apuntó a descifrar el sentido de la historia. El eje principal de sus observaciones es lo que podríamos llamar "la etiología de las decadencias": el estudio comparativo (porque entre muchas otras cosas, Ibn Khaldun fué un precursor del método comparado) de los síntomas y de la naturaleza de los males que ocasionan la muerte de las civilizaciones.

La detención de la expansión imperial y el inicio de la decadencia significó para muchos musulmanes de aquel tiempo una inquietud teológica, porque habían interpretado los rápidos triunfos iniciales como expresión de la ayuda que Alah presta a los verdaderos creyentes. No fué este el caso del sagaz Ibn Khaldun, verdadero precursor de la Sociología moderna, quien proponía otra explicación: "Cuando dos bandos son iguales en número y fuerza -escribía- el más familiarizado con la vida nómade obtiene la victoria". Esa sigue siendo, hasta la época actual, la gran explicación tradicional: la superioridad militar de los nómades sobre los sedentarios^[León Poliakov: HISTORIA DEL ANTISEMITISMO - Tomo II:"De Mahoma a los marranos" - Bs. As. - Proyectos Editoriales - 1988 - pg. 50.].

Ibn Khaldun superó los procedimientos tradicionales del pensamiento árabe -analógico y racional- y llegó a una concepción dinámica del desarrollo dialéctico del destino del hombre, y a plantear sobre esa base una historia retrospectivamente inteligible, racional y necesario^[F. Chatelet et al.: DICTIONNAIRE DES OEUVRES POLITIQUES - Paris-PUF- 1989.].

Ibn Khaldun tenía conciencia de haber creado una ciencia nueva -la ciencia de la sociedad como totalidad (" 'Ilm al-'Umran")- para la que había utilizado todas las ciencias conocidas en su época, desde la Matemática hasta la Economía y la Psicología, pero le confiere un sesgo completamente personal. Por ejemplo, utiliza una teoría cíclica, muy propia de la tradición árabe, que permite configurar una visión del mundo directamente inspirada en la teoría platónica de las esferas, pero Ibn Khaldun seculariza, laiciza, hasta cierto punto, "materializa" esos ciclos: dice, por ejemplo, que la ciudad, la vida urbana, pervierte a los hombres, los hace egoístas y débiles, mientras que los nómades (los "lobos", los llama) que merodean en la periferia, practican la solidaridad ("acabiyya") y son fuertes; cuando la ciudad está podrida no solamente la asaltan sino que la quieren regenerar...hasta que se pervierten a su turno y el ciclo recomienza, porque siempre hay nómades que merodean en la periferia de la civilización...

Para construir su teoría, Ibn Khaldun forjó varios conceptos: el más conocido es el ya mencionado de "acabiyya" que puede traducirse aproximadamente como "espíritu de cuerpo" o "solidaridad". También son importantes los conceptos de "umran badawi" (la civilización, que en su lenguaje siempre es urbana) y de "umran hadari" (la ruralidad o beduinidad).

Ibn Khaldun comprendió -mucho antes que Weber- la diferencia entre lo que en lenguaje weberiano se conoce como "Veraine" y "Anstalt" -o sea entre la asociación comunitaria y el establecimiento urbano- y definió a la civilización como primordialmente urbana: hay campo porque hay una ciudad, por lo menos pensada. Su esquema básico de la socialización puede quizás resumirse así: la civilización es la cohabitación equilibrada, en las metrópolis o en lugares más apartados, con la finalidad de humanizarse, agrupándose para poder satisfacer esas necesidades que, por naturaleza, exigen la cooperación para ser atendidas. Los hombres viven ese proceso -según Ibn Khaldun- en respuesta a un "llamado" ("da'wa"), concepto éste de neto origen teológico.

La estructura de los "Prolegómenos a la Historia Universal" es la siguiente: en el prefacio define a la historia como quehacer humano en el tiempo ("La historia comienza cuando los hombres advierten que no están regidos sólo por la Providencia..." decía) y echa las bases de la crítica histórica: ella debe basarse en la adecuación a lo real. En el resto de los "Prolegómenos" desarrolla sus ideas sobre esa ciencia nueva "de la sociedad como totalidad" que preconiza: el capítulo 1 trata de la sociedad humana y de la influencia del medio sobre la naturaleza humana (en un enfoque comparable con el que siglos después desarrollaría Montesquieu en su "Espíritu de las leyes") y esboza también una Etnología y una Antropología. El capítulo 2 trata de las sociedades rurales. El capítulo 3 trata de las diferentes formas de estado, de gobierno y de instituciones. El capítulo 4 trata de las sociedades urbanas, o sea de la civilización propiamente dicha. El capítulo 5 trata del conjunto de los hechos económicos (en una visión que podría calificarse de "macroeconómica") y el capítulo 6, finalmente, trata del conjunto de las manifestaciones culturales.

Ibn Khaldun sostiene, en esencia, que el "nervio secreto" de la vida humana en sociedad es la "acabiyya" , es decir, el agrupamiento solidario, beduino, tribal, no necesariamente urbano desde un comienzo. La política no empieza con la polis, sino que se extiende a formas muy variadas y frecuentemente muy anteriores a la polis.

En contra de la tesis tradicional musulmana de la necesidad de un sentido escatológico del poder político, de una raíz metafísica trascendente para el orden político, Ibn Khaldun sostiene que el poder político es únicamente inseparable de la sociabilidad, porque es sólo un hecho humano contingente, carente de una referencia necesaria a la religión. Unicamente la solidaridad y su vinculación consciente con la sociabilidad son el fundamento real de toda forma política organizada, cualquiera sea la forma que asuma. El resto es sólo una cuestión de control y represión.

Esta concepción, innegablemente materialista y racionalista, llevó a Ibn Khaldun a decir, en el siglo XIV y en el mundo musulmán, como ya vimos, que "la historia comienza cuando los pueblos advierten que no están regidos sólo por la Providencia...y que las diferencias que se advierten entre los modos de ser de las generaciones expresan las diferencias que separan sus modos de vida económica..." 

### El pensamiento político griego clásico {-}

Ya mencionamos antes nuestro "eurocentrismo cultural".Creemos, sin embargo, que no hay ningún eurocentrismo en reconocer que, en su forma más plena y sistemática, la Filosofía Política, la Ciencia Política y con ellas las primeras teorías políticas normativas puras, nacieron en la Grecia clásica. En todo lo que hemos visto hasta ahora es evidente que hay pensamiento político e incluso sabiduría política, pero también es notorio que hay mucho magma religioso-teológico en esas obras, magma del cual hay que separar el pensamiento político como se separa el metal de la roca que lo contiene, para analizarlo, y luego restituirlo a él, porque sin ese sustento carece de sentido y no resulta incluso comprensible.

En la Grecia clásica, por primera vez primó el pensamiento secular, es decir, una cierta separación de la religión y la política. No es que los griegos no fueran religiosos: tenían una gran cantidad de dioses y muchos rituales, pero sus dioses eran sólo algo más que hombres, y su culto se parecía más a un ministerio de relaciones exteriores que a una adoración estática y temerosa. "En Grecia, la Religión y la Política estaban relacionadas en una forma desconocida en otras partes -dice Hearnshaw^[F.J.C. Hearnshaw: HISTORIA DE LAS IDEAS POLITICAS - Santiago de Chile - Empresa Letras - ?]- la Política dominaba y la Religión era secundaria".

Los primeros intentos de reflexión política secular estuvieron muy influidos por esa versión de la matemática cargada de significación metafísica que caracterizó a Pitágoras y sus discípulos, que en este campo verdaderamente no obtuvieron resultados dignos de destacar.

Los primeros filósofos políticos propiamente dichos fueron los sofistas, en el siglo V aC. Fueron los intelectuales de su tiempo, altaneros y engreídos, que se enorgullecían de su emancipación respecto de la religión tradicional y de la moral convencional. Rechazaban el patriotismo y los deberes de la ciudadanía, y planteaban una libertad individual sin trabas y un libre pensamiento. Mucho antes que Maquiavelo, plantearon una completa separación de la conducta pública y la moral privada.

Los sofistas enseñaban que el Estado es de origen convencional y contractual; que las leyes expresan una relación de fuerzas desprovista de toda sacralidad, y que el derecho se identifica con el poder. Su imagen individual, de intelectuales desencantados, ciertamente lúcidos en muchas observaciones y hasta simpáticos en su individualismo anárquico y un tánto cínico, se eclipsaba ante las consecuencias prácticas graves que podía tener la generalización de sus teorías, que cuestionaban las bases implícitas de la ciudad misma y el conformismo social de la mayoría de sus habitantes.

Sus ideas, potencialmente subversivas, convocaron al campo de la controversia a un pensador incomparablemente más valioso y profundo que ellos: Sócrates (469-399 aC) quien, con su inimitable dialéctica mostró la falsedad de sus argumentos y enseñó el carácter natural y necesario del Estado, el fundamento inmutable y sagrado de la Ley, la necesaria sujeción del Poder al Derecho, la primacía de la Sociedad sobre el Individuo y el derecho social a exigir los servicios del hombre más sabio y mejor para su gobierno.

Como una cruel ironía, este hombre sabio y prudente (pero molesto en su punzante crítica a la mediocridad y corrupción de los poderosos) fue acusado de impiedad y condenado a muerte! por el ignorante y fanático "demos" de Atenas, mientras los sofistas seguían difundiendo sus ideas disolventes, en muchos casos ya convertidas en técnicas apropiadas para el éxito político momentáneo.

El asesinato de Sócrates fue una escandalosa injusticia, el prototipo del acto inicuo, contra el que debe luchar todo filósofo. Tal convicción animó la obra de Platón (427-347 aC), que fue su discípulo durante los últimos ocho años de la vida de Sócrates, y que dio a conocer y desarrolló en sus "Diálogos" las ideas de su Maestro, aunque quizás nunca sabremos realmente cuál fue el aporte de uno y otro a la construcción de esa verdadera columna vertebral de la filosofía occidental.

Los principios fundamentales de la filosofía platónica son: que el fin supremo de la existencia es la virtud, que la virtud es sinónimo de conocimiento, y que el intelecto, órgano del conocimiento, es el factor dominante en el hombre. Platón aplicó tales principios en sus tres diálogos políticos: "La República", "El Político" y "Las Leyes".

El objeto de "La República" es combatir las ideas políticas de los sofistas, y criticar las costumbres políticas de los gobiernos griegos de su tiempo -democracias o monarquías- por su falta de virtud cívica. Plantea en esta obra un ideal político demasiado abstracto y deshumanizado. En "El Político" formula un sistema más compatible con la naturaleza humana corriente: en este diálogo se inclina a pensar que el mejor gobierno posible es el del "Rey-Filósofo", que gobierna de acuerdo con las leyes. Finalmente, en "Las Leyes", Platón abandona la idea de alcanzar un ideal metafísico y concluye diciendo que en este mundo imperfecto (donde los Reyes-Filósofos son muy escasos) un Estado con división y separación de los poderes es lo mejor que prácticamente puede realizarse.

Aristóteles (384-322 aC) fue un discípulo rebelde y cuestionador (y el más capaz) de Platón, y tras la muerte de su maestro y muchos viajes, fundó en Atenas su propia escuela, el Liceo.

Su principal obra de pensamiento político, "La Política", no tiene el encanto literario de los diálogos platónicos, y al parecer proviene de apuntes de conferencias recopilados por discípulos. Esta obra continúa y acentúa decididamente la tendencia, que ya se insinuaba en el último Platón, de abandonar la vía puramente especulativa y fortalecer la participación del material empírico en la reflexión política, al punto de que Aristóteles puede ser considerado "el padre fundador de la Ciencia Política clásica".

Es difícil sintetizar la obra política de Aristóteles, pero en principio podemos decir que sus ideas básicas son: que las verdaderas bases del Estado son la Familia y la Propiedad privada; que el Estado es producto de una evolución desde la Familia, a través de la Comunidad tribal, hasta culminar en la Ciudad autónoma, de la que Atenas es el ejemplo supremo. Luego expone los rasgos más característicos de esa Ciudad-estado, y de los otros tipos de Estado existentes en su tiempo, de los que ofrece varias clasificaciones, de las cuales la más conocida es la basada en la pregunta: quién gobierna? Monarquías, aristocracias, repúblicas, cada una de las cuales tiene una forma corrupta (que se da cuando el gobernante atiende su interés particular en lugar del interés general): tiranías, oligarquías, democracias (nosotros hoy diríamos demagogias). Trata también muchos detalles de la actividad del Estado y de sus funciones. "Como Platón -dice Hearnshaw- Aristóteles ve en la educación el principal preventivo contra las revoluciones".

No creemos necesario extendernos más aquí porque todas las obras de Historia del Pensamiento Político contienen amplias referencias a estos aportes fundamentales al pensamiento político universal, y a ellas remitimos al lector interesado en profundizar el tema, no sin recomendar el invalorable contacto directo con las obras originales. Sí agregaremos aquí un comentario sobre otro trabajo, menos conocido pero a nuestro entender de gran valor como expresión del pensamiento político griego clásico, especialmente en su dimensión "internacional". No es la obra de un filósofo sino la de un historiador: se trata de la "Historia de la Guerra del Peloponeso" de Tucídides (460?-395 aC).

La constancia que ponen de manifiesto las sociedades humanas -cualquiera sea la forma de su organización política- en hacerse la guerra, asegura la actualidad permanente de la obra de Tucídides, que supo distinguir con claridad lo esencial de lo accesorio en la historia humana -especialmente en la historia de la guerra- y expresarlo en términos válidos para todos los tiempos. Dice Tucídides en las páginas introductorias de su obra: "Yo me consideraría muy satisfecho si esta obra fuera considerada útil por aquellos que quieran ver claro, tanto en los acontecimientos del pasado como en aquellos, parecidos o similares, que la naturaleza humana nos reserva en el porvenir. Más bien que una pieza literaria compuesta para el auditorio de un momento, es un capital imperecedero lo que se encontrará aquí". Esta certeza, que Tucídides tenía, del carácter imperecedero de su obra, ha encontrado su confirmación a través de los tiempos. Muchos autores célebres posteriores lo citan, desde Hobbes y Hume, pasando por Hegel y Clausewitz, hasta Erik Weil y Raymond Aron en nuestro tiempo. Siempre se consideró, y se sigue considerando, que la lectura meditada de la "Guerra del Peloponeso" es una introducción formativa totalmente válida para la reflexión política^[F. Chatelet et al.: DICTIONNAIRE DES OEUVRES POLITIQUES, Paris, PUF, 1989.].

Dos razones tiene Tucídides para pensar en el carácter perdurable de su obra: la primera es la naturaleza del conflicto de que trata, sin duda una gran guerra, por la potencia adquirida por los antagonistas y por su objetivo: la futura hegemonía sobre el mundo civilizado. La segunda es que tal guerra, por su violencia sin piedad, lleva a su más alto punto, en estado de brutal pureza, a la naturaleza esencial del hombre, su agresivo aspecto dominante, que se revela a su propia conciencia por la dureza misma de las pruebas a que se ve sometido.

El objetivo "político" de la obra de Tucídides es muy claro: se trata de aportar a quienes quieren practicar seriamente su oficio de ciudadanos, los recursos de conocimiento que les permitan ubicar con acierto su reflexión y su acción, vale decir, disponer de las categorías que les permitan conocer lo esencial de la realidad del medio en el cual deberán luchar y actuar.

En el análisis de los hechos históricos que marcaron los principales procesos de la Guerra del Peloponeso, Tucídides descubrió un concepto clave para entender todo procesos político de confrontación entre entidades estatales: el concepto de IMPERIALISMO, en su acepción puramente política. La dinámica de la formación de un centro imperial y de una periferia dominada -advirtió Tucídides- tiene una lógica interna que es independiente de las intenciones de los actores. Si hay dos centros (si el sistema es bipolar, diríamos en el lenguaje de hoy) fatalmente el mutuo temor los llevará a enfrentarse sin que sea posible volver atrás ni encontrar otra salida: "...si la muy oligárquica Esparta se hubiera encontrado en la posición de la muy democrática Atenas, hubiera actuado sin duda de la misma manera y con las mismas consecuencias", dice Tucídides.

Esta "teoría del imperialismo" se apoya en una concepción realista y "sombría" de la naturaleza humana. La guerra es para Tucídides un poderoso develador, que manifiesta en los actos colectivos algunas tendencias primordiales de nuestra naturaleza como individuos y como Humanidad: "...nuestra conducta no tiene nada que pueda sorprender...nada que no esté en el orden de las cosas humanas..." dicen los plenipotenciarios atenienses ante la Asamblea espartana en la última negociación antes del estallido de las hostilidades.

El discurso analítico de Tucídides sobre la historia de esta guerra se caracteriza por un racionalismo riguroso y totalizador. Su análisis de los hechos históricos vincula permanentemente las acciones militares con las reacciones de las Asambleas y del ánimo de los pueblos. Se entrecruzan allí las polémicas sobre estrategia, los acuerdos entre aliados y los enfrentamientos de los negociadores hostiles. La complejidad de las situaciones y la dificultad que entrañan las opciones a hacer son acertadamente expresadas recurriendo a un método que ya había sido usado por los sofistas: la yuxtaposición en una misma escena de dos discursos, que expresan las opciones extremas a que da lugar cada situación. Las acciones militares y las deliberaciones políticas se confrontan y se refuerzan en una descripción vivísima de las situaciones, en un diálogo tenso y conflictivo. El discurso del historiador conceptualiza el conflicto pero no lo resuelve ni busca reabsorberlo imaginariamente en algún "estado de equilibrio" nuevo y no conflictivo. Quizás todos estos elementos de la visión de Tucídides son lo que le da a su obra ese aire de "permanente actualidad", de modernidad, que nos sorprende a cada lectura...

### El pensamiento político romano clásico {-}

Aunque Roma conquistó y dominó a Grecia, como a todo el resto del mundo mediterráneo, en lo cultural fué muy grande la dependencia de Roma respecto de Grecia. Esto se aprecia en muchos campos, en el arte, la literatura, la religión, la filosofía. En el campo de la Ciencia Política también se ve claramente. El primer teórico político romano fué un griego, Polibio, quien vivió en Roma entre los años 167 y 151 aC.^[J.F.C. Hearnshaw: op. cit.].

Polibio (210-125 aC) fue un historiador griego, hijo del estratega aqueo Licortas. Luego de la derrota griega en la batalla de Perseo fue enviado a Roma como rehén. Allí fue pronto valorado e introducido en la mejor sociedad, llegando a desempeñarse nada menos que como consejero de Escipión el Africano durante el sitio de Cartago, interviniendo en diversas circunstancias como mediador. Su condición de testigo presencial de muchos hechos importantes de la vida romana de su tiempo estimuló sin duda su interés por la historia y la política romanas. Gran admirador de Roma, su preocupación intelectual era, al parecer, explicar el éxito imperial de Roma (originariamente una ciudad-estado en todo semejante a Esparta o Atenas) frente al lamentable fracaso de las ciudades griegas.

Estudió minuciosamente la historia romana, desde el comienzo de las Guerras Púnicas (264 aC) hasta sus días. En ese monumental trabajo dedica un notable capítulo al análisis de los principios que le dieron a la constitución romana su estabilidad y eficacia. Polibio se basó en la clásica clasificación aristotélica de los regímenes políticos: monarquías, aristocracias y repúblicas; y afirmó que las diferencias entre ellas son externas e institucionales, no de principios; y que las tres son diversos modos de resolución de conflictos de fuerzas. Basado en una buena cantidad de estudios de casos, llegó a la conclusión de que estas tres formas, en estado puro, son inestables a causa del antagonismo de las otras dos, y que tienden inclusive a sucederse en forma cíclica.

Explica el poder y la estabilidad de Roma y el éxito de su expansión imperial en base a las características estructurales de la constitución romana, que combina y armoniza las tres formas puras: el principio monárquico está representado por los Cónsules, el principio aristocrático por el Senado y el democrático por las Asambleas populares.

También Polibio expuso la primera teoría sobre lo que luego la ciencia del Derecho Constitucional llamaría "frenos y contrapesos", es decir, los mecanismos constitucionales de transacción entre fuerzas antagónicas, como es el caso del "ius agendi" y del "ius impediendi", o sea el derecho o el poder de actuar y de impedir que detentaban respectivamente los patricios y los plebeyos en la República romana.

Polibio alcanzó a ver, antes de su muerte, cómo esa estabilidad y armonía comenzaban a resquebrajarse, y se insinuaban conflictos y perturbaciones que, al no ser adecuadamente resueltos, con el paso del tiempo culminarían en la caída de la República y la instauración del Imperio.

Aproximadamente cien años después de Polibio apareció en Roma otro gran teórico político: Marco Tulio Cicerón (106-43 aC). Cicerón escribió en los tiempos en que Julio César, sobre las armas de su ejército victorioso, establecía un imperio dictatorial en Roma. Cicerón era un ardiente republicano, detestaba a César y quería restaurar el antiguo equilibrio de las instituciones. En sus obras, analiza las causas de la triste decadencia de la República. Partiendo de la teoría del equilibrio de las formas de gobierno que había diseñado Polibio, Cicerón atribuyó la crisis de su tiempo al excesivo poder alcanzado por el elemento democrático, del que lograron apropiarse demagogos como Mario y César. La obra política principal de Cicerón es "De la República"(55 aC). Este tratado político ha llegado a nosotros por extraños caminos. Fue citado por San Agustín, pero luego cayó en el olvido durante toda la Edad Media y Moderna; se extraviaron los ejemplares que probablemente habría (salvo el fragmento llamado "El sueño de Escipión", que había sido trascripto por un copista a principios de la Edad Media. Figuró, entre otras tantas, como obra perdida, hasta que reapareció en 1819 por el hallazgo de un erudito italiano, Angelo Maï, quien encontró en la Biblioteca Vaticana un palimpsesto con comentarios de los Salmos de San Agustín, que al ser raspado reveló haber sido escrito sobre una copia del texto de Cicerón...

La obra es fundamentalmente una reflexión sobre cuál es el mejor régimen político, reflexión hecha con la intención de actualizar "La República" de Platón, pero cambiando el enfoque: Platón parte de los grandes principios, como el Bien y la Justicia; Cicerón aborda la cuestión desde la técnica política, para llegar finalmente a la fundamentación metafísica del tema. Por otra parte, Cicerón sigue en buena medida el criterio de Polibio, verdadero puente entre el pensamiento griego y el romano: la forma de gobierno es vista como el factor determinante del Estado y, más allá, del mismo pueblo^[Chatelet, Duhamel y Pisier, op. cit.].

La estructura de la obra es clara: su primer tema es la forma política adecuada al Estado romano, cuya respuesta es la "solución mixta" de Polibio, que ya vimos; el segundo tema es el análisis de la experiencia histórica del pueblo romano, porque la Constitución ideal sólo es válida si tiene referencias en la vivencia concreta del pueblo. La forma de gobierno debe ser expresión adecuada de esa vivencia. Recién a esta altura de su discurso, Cicerón plantea los grandes temas platónicos: el fundamento del gobierno y de la ley: se pregunta si ese fundamento es una "ley natural" o simplemente la fuerza. Esto lo lleva a analizar la organización específica del Estado de la Roma republicana, al que considera lo más próximo posible al ideal político de la filosofía estoica. Finalmente, alcanza una culminación metafísica, al vincular las exigencias del bien público con la realización del Bien como categoría trascedente.

El punto de partida de Cicerón es una justificación de la práctica de la virtud política, presentada como una actividad digna del sabio: el ejercicio del gobierno es visto como un requisito para poner las potencialidades de la Sabiduría en acuerdo con el Mundo.

Para Cicerón, el objeto de la Ciencia Política es la "cosa pública", que se genera porque un pueblo es "una reunión de hombres fundada en un pacto de justicia y una comunidad de intereses", reunión basada en un "espíritu de asociación" que es natural, porque el hombre es un "animal político". A partir de allí, la cuestión que se plantea es una pregunta clásica en el pensamiento normativo: cuál es la mejor forma de gobierno. Gobierno de uno, de algunos, de la multitud? La respuesta de Cicerón, como la de Polibio, cien años antes, elige esa cuarta forma mixta, que surge de la mezcla equilibrada de las tres formas originarias.

Cicerón no se queda en la especulación teórica pura, y siguiendo una tradición ya sólidamente establecida, recurre a la experiencia. Reescribe la historia de Roma para configurar un esbozo de "política experimental": busca conocer los modos de marcha y las desviaciones de los Estados. Marca allí la crisis de su momento histórico afirmando que "es falso que la cosa pública no pueda ser gobernada sin recurrir a la injusticia" sino que, por el contrario, requiere "una suprema justicia".

El fundamento de lo político plantea un dilema: reposa sobre la Naturaleza o sobre una relación convencional de fuerzas? Por boca de Escipión, Cicerón se inclina por la ley natural: "Hay una Ley verdadera, la recta razón, conforme a la Naturaleza, universal, inmutable, eterna...en todas las naciones y en todos los tiempos...Dios mismo le da nacimiento, la sanciona y la promulga...y el hombre no puede desconocerla...sin renegar de su naturaleza..."dice.

Cicerón plantea como solución para su tiempo, de crisis profunda, un retorno a las costumbres y valores de la República primitiva, ya erigida en mito histórico. De aquí arranca la culminación de la obra: el famoso "Sueño de Escipión", único fragmento que fue conocido desde la Edad Media, por la trascripción que hizo el griego Macrobio en el siglo V dC.

La función de esta parábola, de este "Sueño", es describir el destino político como un ineluctable deber, ubicándolo en el orden cósmico de las cosas. A través de una poética evocación del Universo, la república política es incertada en una "República Cósmica", cadena universal en eterno movimiento, que vincula las grandes almas beneméritas de la Patria con la posteridad. Esta culminación poética no es una simple efusión sentimental: "Erige a la Política en un reflejo del orden cósmico en el hombre, con lo que la Política se vuelve así la tarea por la cual el hombre ejerce su función de participación en el Cosmos", dice P. Laurent Assoun^[Chatelet, Duhamel y Pisier, op. cit.].

Como trágico contraste existencial con sus elevadas ideas, la oposición de Cicerón a César y a Antonio (contra el que pronunció las llamadas "Filípicas", palabra que se ha incorporado al lenguaje común como discurso severamente admonitorio) le acarrearon su propia ruina y finalmente su proscripción y su muerte en Formia, donde le dieron alcance sus perseguidores. Allí hubiera podido quizás aún salvarse, pero acometido de un cansancio mortal, ante el derrumbe de sus ideales, hizo detener la litera y entregó su cuello a la espada del tribuno en medio del camino, entre el lamento de sus servidores, como un símbolo del fin de una época y del comienzo de otra.

Años después, durante el gobierno (o desgobierno) del emperador Nerón (del 54 al 68 dC), su preceptor y ministro Séneca, un filósofo estoico, encarna una nueva actitud, muy difundida luego: pese al inmenso contraste entre el ideal filosófico estoico y la realidad política de su tiempo, violenta y corrompida, Séneca y muchos otros como él apoyan al Imperio porque se sienten obligados a elegir entre dos calamidades: la tiranía o la anarquía, y entre los dos males prefieren el primero. Pero, como puede verse en sus "Cartas a Lucilius", el filósofo, ante el espectáculo de la desunión y la violencia,de la corrupción generalizada y la falta de esperanza de mejoramiento, intenta retirarse al refugio de su alma, a su "ipseidad", buscando la "posesión de sí" y esperando la muerte como emancipación, en una actitud de huída del presente, llamativamente similar a la de algunos post-modernos actuales. Pero ni su superficial adhesión al orden vigente, ni su huída al interior de sí mismo lo salvaron de verse involucrado, en el 65 dC, en la conjuración de Pisón, por lo que recibió de Nerón la orden de darse muerte. Murió, como Sócrates, acompañado de sus amigos, pero en el fastuoso ambiente que rodeó su vida, en franca contradicción con el ideario estoico que cultivaba.

### El pensamiento político medieval {-}

En los primeros siglos de nuestra Era, el pensamiento cristiano con implicancias políticas arranca de dos pilares evangélicos fundamentales: "MI REINO NO ES DE ESTE MUNDO" (San Juan, XVIII, 36) y "DAD AL CESAR LO QUE ES DEL CESAR Y A DIOS LO QUE ES DE DIOS" (San Mateo XXII, 21 y San Marcos XII,17).

Estos principios proclamaron la emancipación de la Religión respecto de la Política, separaron sus campos de acción y precisaron sus límites. "Señalaron el asentamiento de una Iglesia distinta del Estado -dice Hearnshaw- el fin de esa subordinación del culto divino a la administración civil que había sido la notable característica de la Ciudad-estado griega y romana"^[J.F.C. Hearnshaw: op. cit.].

En el desarrollo inmediatamente posterior del pensamiento político cristiano, principalmente por obra de San Pablo, se consideró la complementación de tareas entre el Estado y la Iglesia: el primero mantiene la paz social y hace cumplir las leyes; la segunda se ocupa de la salvación de los hombres. Sobre esta base, la doctrina enseñó el orígen divino de la autoridad civil: "LOS PODERES QUE EXISTEN SON ESTABLECIDOS POR DIOS" (Rom. XIII,I); "ROGAD POR LOS REYES Y POR TODOS LOS QUE POSEEN AUTORIDAD" (I Tim. II,2); "RECUERDENLES QUE SON SUBDITOS DE LA SOBERANIA Y DE LOS PODERES, PARA OBEDECER A LOS MAGISTRADOS Y PARA ESTAR PREPARADOS PARA TODA OBRA DIGNA" (Titus III,1).

En los escritos de San Pablo es también posible encontrar conceptos muy acordes con los de la filosofía estoica, como el reconocimiento de la Ley Natural, inscripta en el interior del hombre, cualquiera sea su raza o circunstancias (Rom. II, 12-15), o como la afirmación de la igualdad de todos los hombres ante la Gracia Divina, cualquiera sea su condición o jerarquía en esta tierra (Philem. 10-17).

También encontramos conceptos similares en la llamada "Primera epístola de San Pedro": "SOMETEOS A TODO MANDATO DEL HOMBRE POR AMOR A DIOS...TEMED A DIOS, HONRAD AL REY" (1 Pet. II, 13-17).

El Imperio Romano persiguió a los cristianos. Pese a su amplia capacidad para asimilar las religiones de los vencidos, se había alarmado mucho por el exclusivismo del culto cristiano (que se veía a sí mismo como "la única y verdadera fé universal") y por la consiguiente negativa de los cristianos a ofrecer sacrificios y desempeñar servicios incompatibles con sus principios. Se había alarmado mucho más aún por la creciente organización y poder de la Iglesia, su ascendiente sobre el pueblo bajo y su infiltración en círculos cercanos al poder.

Estas despiadadas persecuciones modificaron la óptica cristiana respecto del Estado romano. Ya no fue más visto como "heraldo del Evangelio" y cobraron relieve las palabras de la Revelación de San Juan: "BABILONIA...LA GRAN RAMERA...LA MADRE DE LAS PROSTITUTAS Y DE LAS ABOMINACIONES DE LA TIERRA...EBRIA DE SANGRE DE LOS SANTOS Y DE LOS MARTIRES" (Rev. XVII, 1,9).

Esas persecuciones cesaron en el año 311 dC, tras un completo fracaso en cuanto a frenar la difusión de la nueva religión, pero habiendo ocasionado entretanto sufrimientos sin cuento. En el año 313 dC, Constantino reconoce al Cristianismo como una de las religiones oficiales del Imperio, y ochenta años después, en el 392 dC, el emperador Teodosio I cerró los templos paganos y proclamó al Cristianismo como única religión oficial del Imperio.

Una curiosa consecuencia de este aparente triunfo fue la subordinación completa de la Iglesia al Imperio (o sea el llamado césaro-papismo) que eliminó temporariamente la separación entre Política y Religión. Ese movimiento de subordinación a lo secular de parte de la Iglesia fue resistido de varios modos: el monasticismo, el hermitañismo ascético, las revueltas heréticas (arianismo, donatismo, nestorianismo, etc.) y principalmente por la reflexión filosófica y la acción política de los obispos del Imperio Romano de Occidente, tras la muerte de Constantino. En el Imperio Romano de Oriente, en cambio, esa subordinación continuó durante largo tiempo.

En la Teoría Política, la consecuencia de esta situación en Occidente fue que, durante mil años, el eje de la controversia política pasó por la relación entre el soberano secular y la Iglesia dependiente o independiente de su poder, o queriendo subordinarlo al suyo.

En ese contexto emerge, como primera manifestación del debate, la formidable obra de San Agustín "La Ciudad de Dios". San Agustín reconoce la autoridad del Emperador romano, admite que ésta viene de Dios, prescribe a los súbditos el deber de obediencia y exhorta al Emperador a defender a la Iglesia contra los cismas y las herejías, pero no admite que, en cuanto Emperador, tenga alguna autoridad dentro de la Iglesia. La Fé y la Moral quedan reservadas a los Concilios y a los Obispos consagrados. Marca así nuevamente con claridad la diferencia entre la Ciudad de Dios y la ciudad terrenal.

En el pensamiento de San Agustín, estos dos conceptos tuvieron una notable evolución: al principio, el primero representa al cristianismo y el segundo al paganismo. En esta fase, San Agustín procura liberar al cristianismo de la acusación de ser responsable del saqueo de Roma por los visigodos de Alarico (410 dC) y mostrar que el paganismo no habría salvado a Roma del desastre ni aún en sus épocas de esplendor. Más tarde, la Ciudad de Dios representa a la Iglesia institucional y jerárquica, y la ciudad terrena, al mundo fuera de la Iglesia. Por último, la Ciudad de Dios designa a la "comunidad de los santos" mientras la ciudad terrena es "la sociedad de los réprobos"...

Es de hacer notar aquí que San Agustín, y otros Padres de la Iglesia de aquel tiempo, están ubicados, en forma similar a Séneca y los estoicos, ante un dualismo inquietante y aparentemente irreducible: lo espiritual y lo material, lo bueno y lo malo, la Iglesia y el Mundo, la autoridad espiritual y la autoridad secular. De allí en adelante, la historia de la Teoría Política medieval es la historia de las propuestas de resolución de este dualismo.

"La Ciudad de Dios" (413-426 dC) ha ejercido una influencia política duradera, profunda y variada, sobre muchos autores, que van desde Bossuet a Comte y a los historiadores y comentaristas del siglo XX. El entendimiento de la doctrina política de esta obra debe buscarse en el contexto de la comprensión que San Agustín tenía del misterio cristiano.

Esa doctrina surge motivada por las luchas de San Agustín contra el dualismo de los maniqueos, contra el donatismo, contra el pelagianismo, contra la acusación hecha a los cristianos de haber contribuido por su misma religión al saqueo de Roma por las huestes de Alarico, pero no es una doctrina sólo para un tiempo, sino el producto de una reflexión permanente, con vocación de perdurabilidad, sobre la violencia y la guerra, la vida y la muerte y la ubicación de los cristianos en la prueba de la historia.

Surgido en un tiempo de crisis, el pensamiento de San Agustín se forjó en la confluencia de dos tradiciones: la cultura greco-romana y las Escrituras judeo-cristianas. De la cultura griega San Agustín valora principalmente la figura de Platón y su "República". Hay una filiación intelectual de idealismo platónico en el pensamiento agustiniano, lo que, entre otras cosas, lo ha convertido con el tiempo, en el involuntario inspirador de muchas corrientes heréticas, del mismo modo que las restauraciones de la ortodoxia generalmente se inspiran en Aristóteles...Pero Agustín apela en su obra sobre todo a la cultura romana, de la que está impregnado. Conoce muy bien la historia de la "Urbs" por excelencia, y la utiliza para mostrar que los dioses paganos no podían servir al Estado, al contrario del Dios verdadero. San Agustín no le pide a Roma que renuncie a lo que la hizo grande sino que reciba finalmente los dones del Dios verdadero, tal como está prometido en las Escrituras.

En su esquema general, "La Ciudad de Dios" se presenta como un recorrido que parte de la crisis reciente (410 dC) para inducir al mundo romano a releer su historia política, para descubrir la vanidad de su "teología civil" y reconocer la necesidad de un mediador entre Dios y los hombres -Cristo- para que la "ciudad terrestre" se abra a ese camino de salvación y, al mismo tiempo, a una comprensión de su proceso histórico, que pueda esclarecer su destino político, al mismo tiempo que el destino último de los hombres y las naciones.

Según San Agustín, los hombres siempre forman parte de algún grupo, en una escala que va desde la familia hasta el Imperio, manteniendo en su seno una relación tan estrecha como "la de una letra en una frase". La existencia misma de grupos de diverso tipo supone la presencia de un acuerdo básico, una disposición social fundamental, propia del ser humano. Para San Agustín, PUEBLO es la reunión de una multitud de seres razonables, asociados "por la participación armoniosa en aquéllo que aman". Como toda sociedad, la "Civitas" requiere un consenso básico, un acuerdo que la induzca a perseguir ciertos objetivos antes que otros; un AMOR cuyo objeto (bueno o malo) evidencia la moralidad o perversidad del pueblo.

Una condición esencial de una verdadera "Res publica" es la JUSTICIA, cuyo objeto es el Derecho, el cual según San Agustín debe derivar de la Caridad. Esta idea de Justicia no está tomada sólo de la tradición latina: ella está transfigurada por la interpretación cristiana.

Dice San Agustín que "la paz de la ciudad es la concordia bien ordenada de los ciudadanos en el gobierno y en la obediencia". En su pensamiento, la PAZ es un valor central: "La paz es tan esencial a los hombres que hasta los malvados la desean". San Agustín sabe, por cierto, que hay paces injustas y admite la legitimidad de algunas guerras, pero denuncia sus atrocidades. En esos días turbulentos, el tema de la paz se plantea con fuerza, y también con el recuerdo cercano de la "pax romana", de los más bellos días del Imperio...

Pero, heredero al fin de la tradición bíblica, San Agustín entiende que la vida política está marcada por una oposición fundamental: "Dos amores han hecho dos ciudades: el amor de sí hasta el desprecio de dios, la ciudad terrestre; el amor de Dios hasta el desprecio de sí, la Ciudad Celeste. Una se glorifica en sí misma, la otra en el Señor...".

San Agustín considera que la Ciudad de Dios debe marcar con su impronta a la sociedad política, para que no triunfe en ella la ciudad terrena, la "ciudad del Diablo". Las leyes de la ciudad terrena deben ser observadas, pero en nombre de fines superiores. San Agustín reconoce que, en el mundo real, la "ciudad del Diablo" generalmente triunfa, al menos momentáneamente. La sociedad política no es neutra: después de la Caída, su campo es el campo de Lucifer. Ella subsiste, sin embargo, porque Dios, en su infinita paciencia y amor, le ofrece en forma permanente la oportunidad de convertirse en Ciudad de Dios. El pensamiento político de San Agustín desemboca así en una "teología de la historia política": Cristo, por su muerte redentora, ofrece a las ciudades terrestres la oportunidad de convertirse en ciudades de Dios.

La posteridad de la obra de San Agustín ha sido excepcional, pero su pensamiento, ha sido tergiversado o no? Hay o no una tercera ciudad, la ciudad del hombre, la ciudad de la política? El punto de vista de San Agustín sobre la relación entre lo temporal y lo espiritual, sobre la relación entre la Política y la Religión, parece rechazar todo intento de sacralizar el orden establecido. San Agustín es muy consciente de la precariedad de las cosas humanas, siempre próximas al caos, caos que la sociedad política debería, justamente, vencer.

La sociedad y la cultura: se sostienen sólo por el reconocimiento de su fin último? Cómo compatibilizar la precariedad de las construcciones políticas humanas con la vocación sobrenatural de la Humanidad? Temas actuales, preguntas profundas. La respuesta de San Agustín, generada en un tiempo de violencia y de decadencia, está signada por la esperanza cristiana y vislumbra, a través de las viscicitudes de los reinos terrestres, el advenimiento del "Reino que no tendrá fin"^[Chatelet, Duhamel y Pisier, op. cit.].

Las invasiones de los bárbaros derrumbaron al Imperio Romano de Occidente, o lo que quedaba de él (recordamos aquí el pensamiento de Toynbee según el cual ningún Imperio cae por causas externas si no ha sido corroído previamente por causas internas, por sus propias contradicciones y conflictos) pero esos bárbaros se convirtieron al Cristianismo por obra de monjes y misioneros enviados por el Papa. La unidad política imperial fue reemplazada por la unidad de la Iglesia, por encima de la fragmentación política resultante de las invasiones. Por su parte, el Imperio Romano de Oriente subsistió durante casi un milenio, ejerciendo una sujección imaginaria del Occidente.

En realidad, las relaciones entre el Papa y el César bizantino fueron siempre malas, hasta que el Papa León III, a fines del siglo VIII decidió sacudirse el yugo: declaró "destronada" a la emperatriz Irene "por sus enormes crímenes" y "trasladó" la autoridad imperial a un representante más digno: Carlomagno, Rey de los francos, a quien coronó en las Navidades del año 800 dC., ratificando así una situación existente de hecho desde bastante tiempo atrás. Este movimiento político del Papa, opuesto incluso a la estrategia política que estaba intentando llevar adelante el mismo Carlomagno -por medio de una alianza matrimonial con la emperatriz Irene- planteó en el terreno de la Teoría Política, y también en el de la disputa ideológica y práctica, el problema de los dos poderes, en su forma más compleja.

La doctrina dominante durante no menos de cinco siglos (800-1300) fue la de la supremacía papal: el Papa era superior al Emperador y éste derivaba su autoridad real de aquél. En el campo teórico, los principales campeones de la supremacía papal fueron: - San Bernardo de Clairvaux (1091-1153); - Juan de Salisbury (1110-1180), quien escribió un tratado muy notable de Ciencia Política, el "Policratus", en el que desarrolló una teoría orgánica del Estado, basada en la analogía entre la constitución orgánica del hombre y la entidad política; - Santo Tomás de Aquino (1225-1274), sin duda el más notable de los filósofos medievales, aunque la amplitud y complejidad de su pensamiento nos hace vacilar al clasificarlo aquí. Más tarde comentaremos su obra y haremos algunas consideraciones al respecto; - Egidio Romanus (1247-1316), discípulo de Santo Tomás, quien hizo más bien una tarea de divulgación.

A partir del 1300, esa doctrina dominante comienza a ser crecientemente cuestionada. La causa de los Reyes nacionales contra las pretensiones papales estuvo también a cargo de escritores notables: - Juan de París (1300?) con su"Tratado de la Potestad Real y Papal"; - Pedro Dubois (1255?-1312?) con su "Recuperación de la Tierra Santa"; - Juan Wycliffe (1320-1384) con su "Del Dominio".

Pero creemos que sobre todo hay que hacer mención de dos nombres, por ser precursores de líneas de pensamiento que serían dominantes en los tiempos modernos por venir: - Marsilio de Padua (1275?-1343?) por su obra "El Defensor de la Paz"; - Dante Alighieri (1265-1321) por su obra "De Monarquía".

Vamos ahora a ver con más detalle algunas de las principales obras de este período.

Santo Tomás de Aquino reintrodujo, después de un olvido de mil años, la "Política" de Aristóteles en la teoría política occidental. Interpretó al filósofo griego en términos de teología cristiana y efectuó una magistral fusión de Aristóteles y San Agustín.

San Agustín se ocupaba de política pero su interés iba mucho más a la "ciudad de Dios" que a los reinos terrenales, a cuyos dirigentes a veces llamaba "esos grandes bandoleros". Por su parte, las escuelas monásticas de la alta Edad Media exaltaban los deberes de la piedad para los reyes y los deberes de la fidelidad para los vasallos, pero todo ello era expresión de una política absorbida por la moral religiosa, con eclipse de la Ciencia Política. Cuando en los reinos, los señoríos y las ciudades de la Cristiandad renació el orden político, fueron pensadores como Alberto Magno y Tomás de Aquino quienes iniciaron la restauración de la filosofía natural y de las ciencias, entre ellas la Política, que Aristóteles había compilado en la Grecia clásica.

Podemos considerar que cuando Tomás de Aquino comenzó a leer y comentar la "Política" de Aristóteles a sus alumnos, renació la Ciencia Política en Europa. A partir de allí ella va a rehacerse en torno a esa obra fundamental, ya sea con ella (como en Santo Tomás y tantos otros) o en contra de ella (como en Hobbes y muchos otros pensadores modernos).

El Comentario (prefacio o "proemium") que Santo Tomás hace de la "Política" de Aristóteles, y que todavía suele encabezar algunas ediciones, es de por sí una obra maestra: ubica a la Ciencia Política en el campo del saber y define su objeto, que en su opinion son las COMUNIDADES, en las que los conciudadanos acceden al "buen vivir". El mito (que luego se difundiría tánto) del "estado de naturaleza" es exorcizado de entrada: el hombre jamás vive sólo.

Realizar esas "comunidades" es el deber del hombre. Para hacerlo cuenta con la ciencia de la política, que es a la vez especulativa (observadora de lo real) y práctica (útil para la acción). La Ciencia Política no es nunca neutra. Los politólogos actuales harían bien en aprovechar esa lección del Comentario de Santo Tomás.

Hay una obra llamada "De Regimine Principorum", cuya autoría (al menos la de las primeras páginas) sería de Santo Tomás. En tal caso esta sería su obra más específicamente política. El problema es que tal autoría está cuestionada^[Chatelet, Duhamel y Pisier, op. cit.]. De modo que vamos a buscar el pensamiento político de Santo Tomás en su obra más leída y más influyente: la "Suma Teológica", que no ofrece dudas en cuanto a su fuente de orígen. En ella, el tema político no tiene un lugar específico determinado. Está tratado en forma dispersa a lo largo de toda la obra. El lector interesado en este aspecto debe reunir los fragmentos por sí mismo y plantear las correspondientes cuestiones.

En la "Suma Teológica" la obra de Aristóteles es ampliamente comentada, pero Santo Tomás, según su costumbre, también la confronta con otros filósofos antiguos, con los Padres de la Iglesia y con las Santas Escrituras, y sus conclusiones tienen en cuenta todas esas consideraciones. Veamos algunos temas que presentan un interés actual.

En la "Suma", Santo Tomás no habla del Estado ni de los Derechos del Hombre, que son los conceptos omnipresentes en el pensamiento político moderno. En cambio, habla de "comunidades" que son de naturaleza relacional, y no han sido producidas por un pretendido "contrato social" sino por una relación entre "sustancias primeras": los individuos. Su orígen es muy claro: los bienes más importantes a que aspiran los individuos sólo pueden ser obtenidos y gozados "en común".

Así se constituyen grupos organizados, totalidades, tales como la ciudad. No se trata de un "todo contínuo" (como los organismos vivientes) ni tampoco de una fusión en un ser único. El pensamiento político de Santo Tomás no es organicista. La unidad política es otra cosa: una "unidad de orden", cuyas partes son distintas y autónomas, relacionadas sólo por la prosecución y disfrute de bienes que configuran un fin común.

El fundamento del poder es la necesidad de administrar, de dirigir, ese interés común. El bien común, el bien de todos, tiene neta preeminencia sobre los intereses particulares. Santo Tomás no tiene la menor estima por el desorden: asigna gran extensión al poder, exalta el valor de la virtud de la obediencia y considera a la sedición como uno de los pecados más graves. El oficio del Príncipe es regir, por medio de leyes, la conducta de los hombres asociados en pro del bien común. La ley positiva humana obliga a todos los ciudadanos desde su conciencia. La ley puede (en rigor, debe) castigar las trasgresiones, en forma acorde con la magnitud de las faltas, en casos extremos incluso con la muerte. El objeto de la ley es el "buen vivir": fomentar la virtud y reprimir el vicio.

Hasta aquí encontramos sólo razones en favor del ORDEN. Pero el pensamiento de Santo Tomás es complejo, dialéctico, y esas afirmaciones en favor del poder están muy matizadas: el deber de obediencia cesa frente al Príncipe injusto; la sedición deja de ser un pecado mortal y se convierte en una laudable virtud frente a los tiranos; si la ley "no dice lo justo" se desvanece su autoridad y no merece llamarse ley.

Una ley positiva, humana, es injusta si no es acorde con la Ley Eterna -ley natural- y con las Leyes divinas, expresadas en las Santas Escrituras. Esas fuentes metafísicas del Derecho y la Moral subordinan al Poder, que es esencialmente un poder legislativo.

La Ciudad es una "comunidad perfecta", última, autosuficiente: ella hace del hombre un ser "civilizado". Pero no es la única. También hay agrupamientos más extendidos, para los cuales Santo Tomás usa con frecuencia la expresión "regnum" en lugar de "civitas", como anunciando la extensión de la política a los grandes Estados modernos. En cambio, no considera "comunidades" a los Imperios, siempre hijos de la brutal fuerza militar.

La Ciudad es un agregado de familias, que son también comunidades naturales. En el pensamiento político de Santo Tomás, la familia tiene la carga del vivir, de la generación de niños, de su primera educación y de la subsistencia material. La economía, la riqueza, el bienestar, no son asunto de la Ciudad sino de las familias y de las asociaciones de las familias en el trabajo. La Ciudad tiene la carga de crear las condiciones generales donde puedan darse todas las actividades, incluso las económicas.

Esta concepción, en su conjunto, tiene desde luego un fundamento metafísico: la Comunidad más vasta y universal es la dirigida por Dios, que preside "el Bien Común del Universo". La pertenencia a esa comunidad suprema defiende al hombre de los excesos del poder público. La Iglesia Católica es, para Santo Tomás, la representante aquí abajo de esa Comunidad Global. De aquí puede quizás inferirse una posición favorable a la preeminencia papal, aunque cabe aclarar que Santo Tomás evitó siempre "sacralizar" la política (que es siempre una forma de sacralizar un statu quo determinado) o subordinar el orden secular al eclesiástico, como hicieron muchos de sus continuadores.

Fue Santo Tomás monárquico, como sostienen tantos tomistas? Cuál es para él el mejor régimen político? Respecto de la primera pregunta, Santo Tomás no aparece muy apasionado por este tema. Su temperamento lo inclinaba a respetar las instituciones establecidas y, de hecho, en la "Suma" encontramos argumentos a favor y en contra de la monarquía. El principio de unidad, el gobierno único de Dios sobre el Universo y las primeras páginas de "De Regimine Principorum" (si es que Santo Tomás las escribió -el resto sería de Ptolomeo de Lucques) abogan en favor de la monarquía. Pero también tiene -en páginas de autoría menos dudosa- argumentos en contra, que se sintetizan en la profunda idea de que los "regímenes justos" son variados y relativos a las circunstancias. En realidad, cada vez que Santo Tomás se plantea el tema del "mejor régimen", se pronuncia a favor del régimen mixto, donde uno solo reina, la élite tiene su parte en el gobierno y la elección de los gobernantes procede del pueblo.

Es en verdad difícil exagerar la importancia y la repercusión del pensamiento político de Santo Tomás. El solo hecho de retrasmitir a Occidente la "Política" de Aristóteles no sería pequeño mérito, pero Santo Tomás hizo mucho más que eso: la reelaboró en forma acorde con los valores de la civilización cristiana y la actualizó para los tiempos por venir...

La grandeza de su obra -como la de Aristóteles- tiene mucho que ver con su método dialéctico, que lo lleva a confrontar las tesis de sus predecesores sobre cada cuestión. También tiene que ver con su modestia, que lo mantiene en el nivel de las ideas generales como filósofo y como hombre de ciencia, dejando a la prudencia de los hombres de acción la tarea de dar a la Ciudad sus leyes "loco tempore convenientes" -adaptadas a las contingencias históricas.

Es un pensamiento complejo el suyo, que va y viene entre los pro y los contra de cada cuestión, lo que motivó muchas lecturas e interpretaciones de sus obras. Acababa de restaurar la Ciencia Política en Occidente cuando ya Gilles de Roma se sirvió de ella para la causa política del Papa. Marsilio de Padua y el Dante para la del Emperador y Juan de Paris para la del Rey de Francia...

Pasemos ahora al campo de los defensores de la autonomía del poder secular. Como ejemplos ilustrativos vamos a comentar las principales obras políticas de Marsilio de Padua y de Dante Alighieri.

El más notable de los últimos escritores políticos medievales (porque fue prematuramente moderno) probablemente fue Marsilio de Padua (1274-1343), hombre de compleja personalidad: médico, abogado, militar y político; eclesiástico, arzobispo de Milán, luego excomulgado y sus obras puestas en el Index, fue un hombre que se emancipó más que ningún otro de los moldes mentales de su tiempo. Enseñó, por ejemplo, la subordinación de la Iglesia al Estado, y del clero a los reyes. Enseñó también que los Pontífices y los Príncipes no poseían ninguna autoridad por derecho divino sino que todos la recibían por igual por delegación del pueblo soberano.

Su principal obra política fue "El Defensor de la Paz" (1324). Trata en ella tres temas: el Estado, la Iglesia y la relación entre ambos. Para Marsilio, el objeto del gobierno civil es la paz, y para lograrla considera que es mejor la monarquía que la república, pero también afirma que el Rey no tiene ninguna autoridad inmanente o metafísica: el poder le es conferido por el pueblo y lo debe ejercer sujeto al control popular y con las limitaciones de la ley, que procede del pueblo que lo eligió.

Por su parte, la Iglesia -sostiene Marsilio- no está compuesta sólo por el clero sino por todos los cristianos. Su autoridad no reside en los sínodos clericales ni menos en la curia papal sino en un concilio general, con representación de clero y laicos, donde los miembros más preparados (no necesariamente la mayoría) toman las decisiones. El clero debe limitarse a sus funciones espirituales y no mezclarse en asuntos temporales ni obstaculizar su actividad con riquezas mundanas. El Papa es una agente del concilio general, sin preeminencia inmanente alguna.

En cuanto a la relación entre Estado e Iglesia, Marsilio sostiene que ambos se componen de las mismas personas, aunque agrupadas de modo diferente. En el mundo venidero, el poder espiritual tendrá la preeminencia. En este mundo, el poder profano es el supremo.

Como puede verse, su pensamiento es fuertemente heterodoxo. Marsilio fue un pensador revolucionario, pero nació por lo menos dos siglos antes de tiempo. De todos modos, "El Defensor de la Paz" representa una etapa decisiva en la formación de la teoría sobre la que se edificó el Estado moderno: el principio de soberanía.

En este aspecto, Marsilio plantea dos elementos esenciales para el poder del Estado: la autonomía del poder político civil y el monismo estatal. La fundamentación de la autonomía del poder civil parte de Aristóteles: la Ciudad "es creada para vivir, existe para vivir bien", en el sentido secular del término. El bien extramundano, la vida eterna, etc., no cuentan como principio constitutivo de la Ciudad. El orígen de la Ciudad es subvenir a las necesidades materiales e intercambiar mutuamente los bienes capaces de satisfacerlas. De esta concepción, casi burguesa, de la dicha presente, se deduce el principio del gobierno. Quién debe gobernar? La autonomía de la sociedad civil tiene su correspondencia en la autonomía del poder político. El gobernante debe surgir de la sociedad misma, para coordinar las funciones que hacen al bien común terrestre. El clero no debe gobernar la ciudad terrestre, bajo grave riesgo de guerra civil.

Con respecto al monismo estatal, el razonamiento parte de afirmar la existencia de tres órdenes en la Ciudad: el Sacerdocio, encargado de la salvación eterna; la Producción y los Oficios, para satisfacer las necesidades; y la Coerción, para ejecutar las leyes y custodiar lo justo. La paz civil se logra si cada parte se limita a cumplir las tareas que le corresponden. Para evitar los conflictos, hay que considerar a esta totalidad compleja como una unidad. De la unidad del cuerpo social se deduce la unidad del mando: un solo jefe. Este es el principio del monismo estatal, que será desarrollado dos siglos y medio después por Jean Bodin. Ese jefe único debe gobernar según la ley, que tiene su causa eficiente en el pueblo, es decir, en la voluntad popular, en quien reside en última instancia, según Marsilio de Padua, la paz civil^[Chatelet, Duhamel y Pisier, op. cit.].

Pasemos ahora al caso de Dante Alighieri (1265-1321) y de su obra "De Monarchia" (1310?). Esta obra, escrita en latín, puede ser considerada como el tratado donde el pensamiento político del Dante se enuncia más explícita y completamente, más allá de las referencias ocasionales a la cosa política contenidas en "De Convivio" o en "La Divina Comedia".

"De la Monarquía" desarrolla un planteo estratégico, directamente vinculado con los objetivos de una práctica política, que tiene a su vez un basamento teórico sustentado en una visión metafísica. Expresa el conflicto, la oposición entre el Estado monárquico moderno, en busca de su soberanía, y el poder espiritual de la Iglesia, pero pretende sustentar su estrategia en principios universales rigurosamente establecidos. En pocas palabras, es el trabajo de una racionalidad que busca los fundamentos metafísicos, filosóficos y jurídicos de la posición política asumida por el autor.

"De la Monarquía", al igual que "El Defensor de la Paz" de Marsilio de Padua, respalda a la Monarquía en el conflicto que la engrenta con la Iglesia, y su trasfondo histórico es la lucha inmisericorde que libran los güelfos, fieles a la autoridad temporal del Papado, y los gibelinos, que afirman la primacía imperial.

La originalidad de la obra no reside tanto en su tema sino en la argumentación que desarrolla, en forma de tríptico.

En el primer libro, deduce "la necesidad del principio imperial" del principio último de "unidad para la paz", necesario para el bienestar del mundo en su faz secular.

El segundo libro plantea un problema de raíz histórica: si los romanos ejercieron o no "de jure" el dominio universal. Al resolver positivamente esta cuestión (lo que implica, dicho sea de paso, una revisión radical de la doctrina agustiniana planteada en "La Ciudad de Dios") Dante identifica al Derecho con la Voluntad de Dios y plantea el requerimiento de una "santificación" de la instancia imperial, creadora del orden terrestre. En resúmen, Dante concluye planteando un retorno al "mito fundador" de Roma.

El tercer libro refuta las objeciones que fueron hechas a la primacía del Emperador con argumentos sacados de las Santas Escrituras o de textos históricos. Dante niega a la Iglesia el derecho de otorgar autoridad al Emperador y funda la independencia de los poderes -el secular y el espiritual- en la dualidad propia de la naturaleza humana. El objetivo del campo secular es el bienestar terrestre, cuya obtención plantea la necesidad de un principio único dominante, para evitar las discordias "inter partes", con lo que volvemos a la idea expresada inicialmente.

El fundamento metafísico de su razonamiento es aristotélico. La Monarquía temporal es necesaria para el bienestar del mundo; la libertad de los sujetos sólo puede basarse en el poder de la instancia reguladora del conjunto social, que se hizo efectiva por primera vez en el mundo en el Imperio Romano, con Augusto y su "pax romana".

El Emperador, instancia portadora de la soberanía, es mucho más que una opción política de gobierno: es un requisito del mundo y de la naturaleza humana. El Emperador es un proveedor de paz, un modo de acceso a la prudencia y una expresión del vínculo ético del gobernante con los gobernados. Se trata de un vínculo indestructible entre la instancia soberana, que ejerce su poder dentro de los límites de su potencia, y los súbditos, que legitiman ese poder mediante su acatamiento y consenso, pero al mismo tiempo forman parte de la potencia imperial.

Entre los siglos XVI y XVIII emergerá en toda su fuerza la teoría moderna de la soberanía estatal. El Dante se anticipa a ella, pero al mismo tiempo se diferencia de ella, justamente por esa idea de una mediación ética en el vínculo entre gobernantes y gobernados. Si hemos de reconocer a la Etica algún lugar en la Política, ese lugar es justamente el vínculo necesario entre los súbditos, sujetos de la soberanía, y la instancia soberana. Se trata de una especie de necesaria "substancialización" antropológica del Bien Político. En ese sentido, la obra del Dante, aunque haya emergido como respuesta a determinadas circunstancias históricas concretas y hasta personales, es ciertamente mucho más que un "escrito de circunstancias"^[Chatelet, Duhamel y Pisier, op. cit.].

### El pensamiento político moderno {-}

El tiempo que media entre Marsilio de Padua (1274-1343) y Nicolás Maquiavelo (1469-1527) es el tiempo de una gran transición; es el tiempo de ese Renacimiento que separa (o une) los tiempos medievales de los modernos. En su transcurso, el Imperio y el Papado declinaron en su importancia política, nacieron los Estados nacionales modernos y se establecieron fuertes monarquías en España, Francia e Inglaterra, mientras Italia y Alemania permanecían divididas en pequeños principados y ciudades-estados.

La pólvora originó un nuevo "arte de la guerra"; la imprenta introdujo al mundo en lo que hoy nosotros (conscientes de su tremenda importancia a largo plazo) denominamos Galaxia Gutemberg; el descubrimiento de América y otras exploraciones ampliaron literalmente el horizonte de la visión europea del mundo; la teoría copernicana rompió los estrechos moldes mentales de la Cosmografía medieval, mientras la Reforma protestante y la Contrarreforma católica rompían por primera vez en siglos la unidad religiosa de Occidente. Estos cataclismos culturales tuvieron, por supuesto, su correlato político.

Podemos considerar a Maquiavelo como "el padre fundador" de la Ciencia Política moderna. Fue un agudo observador de las prácticas políticas habituales de su tiempo, y las consignó con precisión en sus escritos. Nada hubo en su vida que justifique la fama que ha hecho de su nombre sinónimo de inescrupuloso o inmoral. Maquiavelo era simplemente un patriota italiano que se dió cuenta de que su propio país se estaba quedando atrás de las emergentes potencias europeas, y de que en esas condiciones, su triste destino era la dependencia o la destrucción.

Cómo hacer para crear una Italia unida, capaz de resistir las agresiones externas y ocupar un lugar digno en el concierto de las naciones europeas? Este es el tema de fondo de sus tres obras políticas principales: "El Arte de la Guerra", "Discursos sobre la Primera Década de Tito Livio" y "El Príncipe".

Maquiavelo fue un estadista práctico, más que un teórico de la política, aunque tuvo una rara habilidad para expresar sus observaciones y experiencias en forma de principios generales de acción política. De todos modos, sus obras son tratados sobre el arte de gobernar y no teorías abstractas.

Para Maquiavelo, las causas del deplorables estado político de Italia eran la desunión, el desorden y el abandono; su primera consecuencia, la devastación por las tropas extranjeras. Cómo remediar ese estado de cosas? Según Maquiavelo, había dos medidas básicas a tomar: - la creación de un ejército nacional; - la formación de un Estado nacional.

Maquiavelo era republicano y pensaba que algún día Italia podría ser una república, pero esos grandes remedios sólo podían ser construidos por un monarca autocrático, un Príncipe, que actuara con gran libertad de medios, morales si puede e inmorales si debe.

Con Maquiavelo queda registrado en la teoría lo que venía dándose ampliamente en la práctica: la separación de la Etica y la Política, si la necesidad lo requiere. Ya no se habla de la "buena vida" como en los tiempos medievales sino de las condiciones de supervivencia y de las posibilidades de una construcción política relativamente estable en medio de la profunda crisis en que se debatía todo el Occidente en aquellos días. Como ya hemos visto, esas van a ser características perdurables del pensamiento político moderno.

En cualquier Historia del Pensamiento Político pueden encontrarse abundantes referencias a esta época. Aquí, por limitaciones de espacio y por ser otro el objetivo esencial de la obra, vamos a tomar como ejemplos ilustrativos sólo dos, poco conocidos y comentados en este ámbito. El primero es una propuesta de reacción positiva frente a la crisis: se trata de las "Constituciones" de San Ignacio de Loyola. El otro es un verdadero manual de arte política, comparable y a la vez diferente de las obras de Maquiavelo: se trata del "Testamento Político" del Cardenal Richelieu.

Veamos primero el caso de San Ignacio de Loyola (1491-1556) y de sus "Constituciones de la Compañía de Jesús" (1539-1556).

Si la Política, en un sentido amplio y profundo, es el arte de gobernar una sociedad humana, las "Constituciones" de San Ignacio pueden sin duda ser consideradas, al menos en una de sus dimensiones, como una obra política. En realidad, como todas las reglas monásticas, las "Constituciones" son una obra maestra del pensamiento político. Es necesario mucho genio político para trazar las condiciones de vida espiritual, material y administrativa de una comunidad en la perspectiva de una duración indefinida^[Chatelet, Duhamel y Pisier, op. cit.].

Las "Constituciones" fueron elaboradas a lo largo de 17 años, entre 1539 y 1556. San Ignacio aún trabajaba en ellas cinco meses antes de su muerte, y todo su ser está expresado en ellas. Quién era, pues, este hombre? Pocos fundadores de órdenes religiosas han sido objeto de visiones personales tan parciales, caricaturescas y malévolas: un puro militar, hábil intrigante, lo que hoy llamaríamos un pragmático total. Creemos que no vale la pena refutar hoy esos antiguos errores y calumnias. Es preferible re-descubrir al hombre leyendo los escritos que nos ha dejado.

Antes que nada, San Ignacio era un místico. Su política está impregnada de mística. Todas las etapas de su accionar están "inspiradas" a partir de esa experiencia primordial, acaecida en Manrese, en la que tuvo "la inteligencia y conocimiento de numerosas cosas tanto espirituales como referentes a la fe y a la cultura profana". En esa experiencia mística él "comprendió" cómo Dios había creado el mundo y percibió que el acto creador es un acto de amor, y que Dios sólo quiere que sus criaturas respondan a su amor y se dediquen a re-encontrarse con El en su gloria.

Esa es su intuición fundamental: la misión del hombre en la Tierra es cumplir la Voluntad de Dios: obrar para que todos los hombres amen a Dios y se hagan artesanos de su Gloria. El esquema ignaciano es, pues: el amor de Dios desciende hacia los hombres, y los hombres, por amor, remontan hacia Dios, no sin exhortar al mayor número posible de otros hombres a hacer lo mismo.

Esa visión define los objetivos esenciales de la "política" ignaciana: compartir con quienes quieran escucharlo su intuición primera, a fin de que ellos la propaguen, y que esa propagación sea continua e indefinida en sus alcances. Desde luego, no puede hacerse un ingenuo reduccionismo de la compleja política ignaciana a esa experiencia de una revelación personal, pero toda su actuación posterior encontró su inspiración y explicación profunda en la fuerza que emanó para él de la iluminación que recibió en Manrese.

Su primera tarea fue elaborar su visión, y ante el imperativo de ordenar su vida discernir cual es la voluntad de Dios respecto de él y adaptarse a ella. Ese es el objeto de los "Ejercicios Espirituales", que pronto se difundieron como práctica para quienes desearan "ver claro en sus vidas y tomar un nuevo punto de partida", más allá de ser una herramienta de la política ignaciana de reclutamiento.

La política corriente es esencialmente finalista: persigue objetivos concretos y predeterminados. Un rasgo extraño de esta política ignaciana impregnada de misticismo, es la indefinición del porvenir, reflejada en el concepto de "indiferencia" respecto del "qué hacer". La Psicología Religiosa ayuda a explicar esto: para San Ignacio y sus compañeros lo esencial es hacer la Voluntad de Dios, cualquiera sea ésta, y lo importante es ponerse en disposición de espíritu adecuada para percibirla. Toda actividad es buena, a condición de que Dios la inspire y ratifique. En caso de duda, siempre puede consultarse al Papa, Vicario de Dios en la Tierra. Esto explica la diversidad de tareas desempeñadas por la Compañía.

Dotada de consagración oficial en el seno de la Iglesia desde 1540, su política inicial consistió en no tener ninguna predeterminada sino satisfacer caso por caso las demandas que le fueran planteadas y que continuamente se acrecentaron más allá de sus posibilidades, porque estos hombres eran muy requeridos: eran letrados y conducían una vida ejemplar. Las grandes líneas de su heterogénea acción fueron: la misión evangelizadora, la reforma interna de la Iglesia (fueron los adalides de la llamada "Contrarreforma", como medio efectivo de enfrentar a los protestantes) y, en forma creciente, la educación, en una original forma mixta para novicios y laicos. En corto tiempo, como puede advertirse en la correspondencia ignaciana, la fundación y gestión de colegios se convirtió en una preocupación central de su política.

Otra línea política básica era el mantenimiento de relaciones con "los grandes de este mundo". Testimonio de ella es una abundante correspondencia con reyes y nobles, en una acción política que intenta servir a los intereses de la Iglesia y del Papado, y obtener apoyo para las obras de la Compañía. Esta acción se llevó a cabo con una clara comprensión de los beneficios que de la acción de la Compañía se derivan, o pueden derivarse, para el gobierno civil: por ejemplo, el efecto de la fundación de un Colegio el términos de desarrollo intelectual de una comunidad, de impacto sobre la opinión pública y sobre la concordia de los ciudadanos, etc.

Por supuesto, otra línea política fundamental se refería a la lucha contra los adversarios de la Iglesia: la Reforma Protestante y el Imperio Turco. Respecto de la primera, pronto se advirtió la conveniencia y la necesidad de enfrentarla en el terreno de la educación. Respecto del segundo, en cambio, San Ignacio diseñó una campaña militar que preanunció la que luego de su muerte puso fin al expansionismo turco en la batalla de Lepanto.

Las "Constituciones" de San Ignacio, políticas en cuanto se refieren al gobierno de personas, fueron y son la forja de los hombres que cumplieron y cumplen tareas en la Compañía "a la mayor gloria de Dios". Son una sabia arquitectura de disposiciones estructuradas en base a un principio fundamental, imperativo: la OBEDIENCIA. "Perinde ac cadaver" dice la fórmula latina ( a imitación del cuerpo de Cristo luego de su descendimiento de la Cruz?). Nuevamente encontramos aquí la raíz mística, que tanto diferencia la política ignaciana de otros enfoques "seculares" de la política. La obediencia al superior entronca en última instancia con la obediencia a la Voluntad de Dios: la desobediencia en cualquier escalón es una ofensa a Dios, pero esa obediencia está condicionada por principios éticos superiores y, por otra parte, el superior sabe que su orden debe ser lo más acorde posible con lo que cada hombre percibe como designio de Dios para él, aquello para lo cual es apto y sirve. Es fácil percibir la potencia política que puede generar una obediencia perfecta y voluntaria fundada en un absoluto de raíz metafísica y arraigada en una convicción interior sobre el sentido de la propia vida.

Quizás en esa extraña mezcla de disciplinada obediencia y de confiada delegación de funciones y responsabilidades en base a lo que cada uno siente como identidad propia y misión existencial, en ese enfoque participativo que por momentos parece posmoderno, se encuentre la explicación de la dimensión política de algunos extraños fenómenos históricos, como las misiones jesuíticas en América del Sur, en las que un puñado de hombres, sin posibilidad alguna de ejercer una coacción material efectiva, organizaron políticamente a varios miles de indios, en pueblos de vida y economía perfectamente articuladas sobre una enorme y dispersa extensión de territorios salvajes; estructura política que sobrevivió incluso a la expulsión de sus fundadores, ya que solo fueron abatidos por la violencia de una guerra cruel y despiadada.

Pasemos ahora al caso de Armand-Jean du Plessis, cardenal de Richelieu (1585-1642) y su "Testamento Político" (1632-1639 aprox.).

Richelieu, obispo de Lyon en 1606, en 1614 pasó a formar parte de los Estados Generales. Apoyó a la Regente María de Medici, lo que le valió integrar el Consejo Real en 1616. Acompañó en su destierro a la Regente y participó de las negociaciones de reconciliación de ésta con el Rey Luis XIII, lo que le valió el capelo cardenalicio y la reincorporación al Consejo (1624), del que asumió la presidencia, lo que terminó convirtiéndolo en árbitro de la política francesa en nombre del Rey. Participó con amplio sentido político en las guerras de religión y creó las bases de la centralización política y administrativa de Francia, fortaleciendo la autoridad monárquica en nombre de la razón de Estado. Su sucesor fue el cardenal Mazzarino.

De todas las obras atribuidas al cardenal Richelieu ("Memorias", "Máximas Estatales"), el "Testamento Político" es la más elaborada en cuanto a reflexiones sobre el gobierno del Estado. Aunque su autenticidad fue cuestionada casi desde su aparición, y es indudable que una gran parte fue redactada por colaboradores (como el célebre "P. Joseph") tampoco puede dudarse de que el trabajo de los secretarios fue dirigido por Richelieu y que el "Testamento Político" expresa fielmente su pensamiento.

En su dedicatoria al Rey, Richelieu explica sus intenciones al escribirlo: dejar al Rey un conjunto de consejos prácticos, en el que pudiera inspirarse para asegurar la continuidad de una política y una obra gubernamental que corría el riesgo de quedar inconclusa por causa de la crónica enfermedad del cardenal.

La obra presenta una forma muy estructurada: dos partes, de ocho y diez capítulos respectivamente, divididos a su vez en secciones. El tema mayor de la obra es el Estado.

La primera parte, luego de una introducción histórica ("una sucinta narración de las grandes acciones del Rey") trata de la estructura del Estado, los órdenes que lo componen y los órganos que lo dirigen. La segunda parte trata de la manera de dirigir el Estado, los principios fundamentales que deben observarse en su gobierno. Es, pues, un manual de arte política, comparable (si bien con muchas diferencias de criterio) al "Príncipe" de Maquiavelo.

Con respecto a la estructura del Estado, Richelieu conserva esa concepción tripartita de la sociedad, de origen tradicional, que fue sistematizada por el jurista Charles Loyseau a principios del siglo XVII: los "sujetos del Rey" se agrupan en tres estados u órdenes; el clero, la nobleza y el "tercer estado", de desigual tamaño y de desigual (e inversa) importancia política. El clero es el primer orden del Reino, y Richelieu (en contra de lo que a veces suele creerse de él) se muestra en este aspecto como un "hombre de Iglesia", que busca preservarla de los excesos del poder estatal y al mismo tiempo regenerar al orden eclesiástico por medio de su adhesión a los principios de la Contrarreforma y de la restauración del poder episcopal. Aplica en esto un galicanismo moderado.

A la nobleza le dedica muchas alabanzas, como la de que constituye "uno de los principales nervios del Estado, capaz de contribuir mucho a su conservación y su restablecimiento", pero sin ocultar, por otra parte, su profunda desconfianza hacia un orden que produce peligrosos enemigos de la centralización del poder estatal: busca satisfacer sus demandas, pero a cambio de su estrecha sumisión al Estado. Richelieu fue quizás el más consciente propugnador de esa política centralizadora y unitaria que buscó fortalecer el poder real vinculándolo con la naciente burguesía y reduciendo a los señores feudales, a los nobles, a la condición de cortesanos, llenos de privilegios y placeres pero desprovistos de todo poder verdadero.

Al tercer estado le dedica un breve capítulo, referido sobre todo a sus estratos superiores: los oficiales de justicia y de finanzas, capítulo en el cual propone medidas para combatir la corrupción en esos niveles. Del pueblo, elemento residual del tercer estado, no hay en su obra más que breves referencias, impregnadas de cierto desprecio y dudas sobre su capacidad de sujetarse a la leyes por la razón, pero recomienda que los impuestos que gravitan sobre el pueblo sean moderados, en nombre de la justicia y del interés bien entendido del mismo Estado.

Su visión conservadora y organicista lleva a Richelieu a plantear un equilibrio entre los órdenes, fundado en una jerarquía de honores entre ellos. A la cabeza del Estado están el Rey y sus ministros, cuyo rol es exaltado. Da la impresión de que, en su concepción, la verdadera tarea del Rey es elegir buenos ministros, y que éstos son los que verdaderamente gobiernan. El Rey debe saber elegir como colaboradores a hombres probos, consagrados a los asuntos del Estado, que le sepan hablan con franqueza, indiferentes a la calumnia, desapegados de intereses y pasiones y sobre todo, de las mujeres. Recomienda para esas funciones a los eclesiásticos, ya que al carecer de esposa e hijos sienten menos que otros el deseo de hacer prevalecer sus intereses particulares. A sus consejeros competentes y devotos, el Rey ha de sostenerlos en su confianza contra las intrigas de los envidiosos y los descontentos. Su "teoría del ministerio" es en realidad una fundamentación racional del sistema que él mismo creó en la práctica: un Consejo de pocos miembros (cuatro, en su caso) uno de los cuales tenga total primacía para asegurar la unidad del mando "porque nada es más peligroso en un Estado que diversas autoridades iguales en la administración de los negocios".

El arte de conducir al Estado tiene reglas precisas, que Richelieu desarrolla largamente en la segunda parte de su "Testamento": * Respetar la Voluntad Divina, que es donde se encuentra el fundamento de la autoridad real. Cumplir sus deberes con la Iglesia, dar ejemplo de piedad, favorecer las conversiones voluntarias, no blasfemar; tales son los consejos que Richelieu da al Rey. Por otra parte, excluye el uso de la fuerza para obtener la abjuración de los protestantes; * En una actitud "dividida", típica del Humanismo, Richelieu sostiene que, una vez rendido a Dios y a su Iglesia el homenaje debido, se es libre de hacer política sólo con la guía de la filosofía antigua y del sentido común. El objetivo de su acción es asegurar la salud y fuerza de su Estado: es, en definitiva, la razón de Estado, que consiste antes que nada en dirigir al Estado por la razón: tener dominio de sí, firmeza, discreción, para aplicar la fuerza que sea necesaria para vencer las resistencias internas y externas a la acción ordenadora del Estado; * El arte de dirigir a los hombres necesita recurrir al uso de recompensas y castigos: para Richelieu son más importantes los segundos que las primeras. En política no hay lugar para la caridad o la piedad cristianas. El Poder es siempre el objeto y el medio del Estado y el Poder se debilita si se recurre a la conmiseración. El poder depende de la reputación del Príncipe en la opinión pública, de la fuerza de los ejércitos y la seguridad de las fronteras, y de la economía entendida como fundamento material del poder estatal, para lo cual aconseja el fomento del comercio exterior.

Esta obra fue publicada tardíamente, cuando el apogeo del absolutismo monárquico ya había producido una reacción pro-liberal. Es una obra que expresa, teórica y prácticamente, esa pasión casi mística por el Estado, que es el fundamento emocional del absolutismo y que lleva a concebir un Estado que trasciende en forma absoluta los intereses concretos de los grupos humanos que lo componen y expresa, o pretende expresar solamente el interés supremo de la Nación, al que todo ha de subordinarse. En ese sentido puede ser entendida como una visión precursora de las ideologías nacionalistas que en el siglo XX concibieron a la Nación, al Estado o a la Patria como una entelequia de naturaleza metafísica, desconectada de la concreta manifestación sociológica y antropológica de su encarnación histórica real^[Chatelet, Duhamel y Pisier, op. cit.].

## Tercera parte {-}

### Teorías políticas normativas contemporáneas {-}

Las obras políticas que vamos a intentar describir aquí abarcan un largo e intenso período de tiempo, que va desde fines del siglo XVII hasta nuestros días. Siguiendo en parte a J.J. Chevalier, hemos dividido ese tiempo en cuatro subperíodos, por razones de claridad expositiva y aceptando las limitaciones del esquematismo que tienen siempre tales divisiones: -el asalto al absolutismo (1690-1789); - las consecuencias de la revolución francesa (1789-1848); - los socialismos y los nacionalismos (1849-1927) - las teorías actuales (1928 en adelante).

El asalto al absolutismo.

El primer momento (1690-1789) expresa la reacción antiabsolutista, ideológicamente relacionada con la consolidación de la burguesía capitalista como clase dominante, que ya no se muestra dispuesta a actuar como aliado secundario de la monarquía en la conformación de un Estado centralizado, sino que, cumplido ese objetivo, aspira a un rol más protagónico y a poner en vigencia un ideario y una institucionalización política más acordes con su dinámica social. Esa reacción es fundamentalmente la obra del pensamiento racionalista liberal. Los grandes temas subyacentes en estas obras son, en nuestra opinión: - la búsqueda de un equilibrio entre el Poder y la Libertad; - el encauzamiento de la participación política acrecentada Sin pretender suministrar un listado exhaustivo de obras de este período, creemos sin embargo que entre las principales deben ser mencionadas al menos las siguientes:

- Cesare Beccaria: DE LOS DELITOS Y DE LAS PENAS (1764);
- Jeremy Bentham: INTRODUCCIÓN A LOS PRINCIPIOS DE LA MORAL Y DE LA LEGISLACIÓN (1789);
- Jean-Jacques Burlamaqui: PRINCIPIOS DE DERECHO POLÍTICO (1751);
- David Hume: DEL CONTRATO ORIGINAL (1748) y DEL ORIGEN DEL GOBIERNO (1774);
- Simon-Nicolas-Henry Linguet: TEORÍA DE LAS LEYES CIVILES O PRINCIPIOS FUNDAMENTALES DE LA SOCIEDAD (1767);
- John Locke: DOS TRATADOS DEL GOBIERNO CIVIL (1690);
- Jean-Louis Lolme: CONSTITUCIÓN DE LA INGLATERRA O ESTADO DEL GOBIERNO INGLES (1771);
- Charles-Louis de Secondat, barón de Montesquieu: EL ESPÍRITU DE LAS LEYES (1748);
- Thomas Paine: LOS DERECHOS DEL HOMBRE (1791-1792);
- Jean-Jacques Rousseau: EL CONTRATO SOCIAL (1762);
- Emmanuel Joseph Sièyes: QUE ES EL TERCER ESTADO (1789).

De este conjunto de obras vamos a ver con más detalle la que a nuestro juicio puede ser considerada la más completa y representativa del período, y quizás la que más persistente influencia ha ejercido en el pensamiento político europeo y americano: se trata de "Dos Tratados sobre el Gobierno Civil" de John Locke.

John Locke nació en 1632. Estudió en Oxford, donde alcanzó el grado de "master" en 1658. Se conserva memoria de su desagrado por el árido método escolástico imperante en su tiempo, pues "le intersaban más los hechos reales que las abstracciones y las cuestiones sin utilidad". En su carácter se destacaban dos notas: la simpatía por la libertad individual y un sosegado utilitarismo. Conoció el exilio y el retorno triunfante, tras la "Glorius Revolution". Murió en 1704.

Su obra es una de las más vigorosas críticas a la monarquía absoluta, cuyo rechazo está fundado sobre la idea de la necesaria subordinación de la actividad de los gobernantes al consentimiento popular.

Locke es un de los teóricos clásicos del liberalismo político. Propone una articulación rigurosa de los temas liberales fundamentales: la igualdad natural de los hombres, la defensa del sistema representativo, la exigencia de una limitación de la soberanía estatal, limitación requerida por la defensa de los derechos subjetivos de los individuos. Buscó un remedio a la tiranía en la división de los poderes del Estado, anticipándose en esto a Montesquieu.

De sus "Dos Tratados...", el primero es de carácter polémico y puede decirse que no conserva mayor interés ni actualidad para nosotros, hoy. Se trata de una refutación de los argumentos desarrollados en otra obra, el "Patriarcha" de R. Filmer, quien pretendía demostrar el derecho de los príncipes al gobierno absoluto, asimilando la soberanía política al dominio primitivo de Adán sobre el mundo entero, dominio que, recibido directamente de manos de Dios, habría sido trasmitido a los monarcas a través de la Historia...

El segundo tratado apunta, por el contrario, a establecer positivamente "el origen, los límites y los fines verdaderos del poder civil". Esta obra es la que hoy generalmente se publica^[John Locke: ENSAYO SOBRE EL GOBIERNO CIVIL, Madrid, Aguilar, 1981.] y se lee, pero en el pensamiento de Locke las dos obras forman un todo deductivamente entrelazado. En una síntesis muy apretada, la filosofía política de Locke es la siguiente: El gobierno debe ejercerse con el consentimiento de los gobernados. El gobierno es una creación del pueblo, mantenida por el pueblo para asegurar su propio bien. Según Locke, esta teoría se basa en la vigencia de dos conceptos muy vinculados: la Ley de la Naturaleza y el Contrato Social.

En el "estado de naturaleza" los hombres eran libres, pero como "libertad no es licencia", no tenían derecho a hacer cualquier cosa sino a actuar en modo acorde con una "ley" de la Naturaleza: la RAZÓN, que indica que, si los hombres son libres e iguales, nadie puede dañar a otro, o convertirlo en instrumento de los propios fines. El estado de naturaleza no era un estado de guerra de todos contra todos -sostiene Locke, contrariando en esto a Hobbes- sino un estado que sería perfecto si los hombres se comportaran racionalmente, pero no sucede así. La guerra y la violencia son siempre posibles y plantean la necesidad de un gobierno, el cual se forma por el sometimiento voluntario de las libertades individuales a un poder superior, cuya tarea es protegerlas. Surge así el "contrato social", que se establece entre el pueblo y su gobernante.

El contrato social contiene dos ideas íntimamente unidas: el contrato de gobierno y el contrato de sociedad. Locke (al igual que Rousseau y que Hobbes) parte de este último. Cuando ya se ha organizado la comunidad, ésta decide confiar a un gobierno la protección y defensa de sus libertades y derechos, pero conservando la posibilidad de retirarle su confianza si su accionar no le conviene. En el fondo, lo que Locke busca es fundamentar filosóficamente un régimen de Monarquía constitucional, con un Parlamento que encarne la representación popular y que respete y haga respetar las libertades públicas. 

### Las consecuencias de la Revolución Francesa {-}

El segundo momento (1790-1848) es relacionado por J.J. Chevalier con las consecuencias de la Revolución Francesa porque, si bien el Absolutismo ha sido postrado y la Revolución se ha cumplido, no es un momento de plenitud sino de enfrentamiento con una realidad que en gran parte está aún por construir. Decía entonces Napoleón: "Se ha destruido todo; se trata de recrear. Hay un gobierno, poderes; pero, qué es todo el resto de la Nación? Granos de arena".

Precisamente porque la Revolución ha triunfado es concebible la emergencia de una pasión contrarevolucionaria. Su principal vocero fue Edmund Burke, con sus "Reflexiones sobre la Revolución de Francia" (1790). Es justamente porque ha triunfado el jacobinismo, con sus augustas abstracciones (la Nación, el Pueblo) que los pueblos vencidos responden con la emergencia de un nacionalismo concreto, apasionado y fuerte. Este sentimiento es cabalmente expresado por los "Discursos a la Nación Alemana" (1807-1808) de Johann G. Fichte. La Revolución estaba animada de un espíritu igualitario pero terminó siendo burguesa, como un momento de ese largo proceso en el que la pasión igualitaria se enfrenta con la pasión de libertad en el corazón del hombre. Ese es justamente el tema que, con singular maestría, afronta el jóven Alexis de Tocqueville en su "Democracia en América" (1835-1840).

Aparte de las obras mencionadas, creemos que en una lista de obras importantes de este período hay que mencionar por lo menos las siguientes:

- Gracchus Babeuf: COMPENDIO DEL GRAN MANIFIESTO...PARA RESTABLECER LA IGUALDAD DE HECHO" (1793);
- Pierre-Simon Ballanche: ENSAYO SOBRE LAS INSTITUCIONES SOCIALES EN SU RELACIÓN CON LAS IDEAS NUEVAS (1818);
- Louis Blanc: ORGANIZACIÓN DEL TRABAJO (1840);
- Louis de Bonald: LEGISLACIÓN POSITIVA CONSIDERADA EN LOS ÚLTIMOS TIEMPOS POR LAS SOLAS LUCES DE LA RAZON (1802);
- Francois-René Chateaubriand: LA MONARQUÍA SEGÚN LA CARTA (1816);
- Karl von Klausewitz: DE LA GUERRA (1816-1831);
- Auguste Comte: PLAN DE TRABAJOS HISTÓRICOS NECESARIOS PARA REORGANIZAR LA SOCIEDAD (1822);
- Benjamin Constant: LOS PRINCIPIOS POLÍTICOS APLICABLES A TODOS LOS GOBIERNOS (1806);
- Johann Fichte: LOS FUNDAMENTOS DEL DERECHO NATURAL (1796);
- Charles Fourier: TEORÍA DE LOS CUATRO MOVIMIENTOS Y DE LOS DESTINOS GENERALES (1808);
- Francois Guizot: DE LOS MEDIOS DEL GOBIERNO Y DE LA OPOSICIÓN (1821);
- Georg W.F. Hegel: PRINCIPIOS DE LA FILOSOFÍA DEL DERECHO (1821);
- Felicite de Lamennais: PALABRAS DE UN CREYENTE (1834);
- Pierre Leroux: DE LA HUMANIDAD (1840);
- Jules Michelet: EL PUEBLO (1846);
- Robert Owen: UNA NUEVA VISIÓN DE LA SOCIEDAD (1813-1814);
- August Rehberg: INVESTIGACIONES SOBRE LA REVOLUCIÓN FRANCESA (1793);
- Charles Renouvier: MANUAL REPUBLICANO DEL HOMBRE Y DEL CIUDADANO (1848);
- Claude-Henri Saint-Simon: EL ORGANIZADOR (1819);
- Max Stirner: EL ÚNICO Y SU PROPIEDAD (1845).

De este conjunto de obras vamos a repasar los principales contenidos de una obra que nos parece muy expresiva de los valores de esta época, signada por la herencia (positiva y negativa) de la Revolución Francesa y las condiciones históricas de la Modernidad. No tan conocida ni difundida como los trabajos de Comte o de Tocqueville, tiene a nuestro juicio un alto valor representativo del espíritu de su tiempo: se trata de "El Organizador" de Saint-Simon.

Claude-Henri de Rouvroy, conde de Saint-Simon (1760-1825) nació en Paris, en el seno de una familia noble, de poderosa influencia en la Corte de Luis XVI, y presunto descendiente de Carlomagno. Recibió una educación sumaria y descuidada, y se inició pronto (1776) en la carrera de las armas. Combatió en América, como Lafayette, bajo las órdenes de Washington y retornó a Francia en 1783. En 1790 renunció a sus títulos nobiliarios, pese a lo cual a duras penas logró salvar su vida durante la Revolución Francesa. Después de encarar diversas empresas, desde 1800 en adelante se consagró al estudio de las ciencias, gastando en ello su patrimonio. A lo largo de muchos años publicó gran número de obras sobre temas muy diversos, que van desde la pedagogía hasta la historia, pasando por la industria, la economía y la política. Con el tiempo, y después de muchas viscicitudes personales y de los grupos que formó, algunos de sus seguidores crearon en torno a su figura y sus ideas una atmósfera francamente mesiánica. Murió en 1825.

Mensajero del futuro, exegeta revelador del sentido del pasado, Saint-Simon ha sido considerado fundador del que luego los marxistas llamarían "socialismo utópico". Como un apóstol ateo de una religión nueva, de inspiración newtoniana, invención puramente humana dotada de una doble función de agregación y de mediación, Saint-Simon quiso mostrar que el progreso de la humanidad no se había detenido con los cambios producidos por la Revolución Francesa y que aún los hombres tenían frente de sí todo un mundo nuevo que conquistar^[Saint-Simon: OEUVRES, Paris, Anthropos, 1966.].

Ese "deseo de otra revolución", expresado bajo formas utópicas o científicas, inspirado en el "deseo de dicha para los hombres" (expresión de resonancias milenaristas) condujo a Saint-Simon a preguntarse sobre las condiciones del ser-en-sociedad del hombre en el contexto de la Modernidad. Su respuesta plantea la necesidad de superar el egoísmo y lograr una real vinculación entre los hombres para realizar el gran objetivo social: la producción, es decir, "la satisfacción de las necesidades de todos". Sobre la base de un planteo de neta inspiración positivista ("la capacidad científica positiva -decía- debe reemplazar al poder espiritual", y también: "debe lograrse la preponderancia de las capacidades sobre los poderes") encuentra la gran respuesta en la producción de bienes por el trabajo.

"La verdadera sociedad cristiana -sostenía- es aquella donde cada uno produce alguna cosa que les falta a otros...El interés de la unión es el interés de las alegrías de la vida; el medio de unión es el trabajo".

En definitiva, propuso una nueva organización de la Humanidad fundada sobre la industria. La industria reúne a la sociedad en torno a un fin común y a una identidad práctica. En ese modelo, la "política positiva" se vuelve "ciencia de la producción". El dominio de los hombres debe ser mínimo: una mínima función de policía; las relaciones entre los hombres deben ser primordialmente relaciones de coordinación. El "deseo de dominación" que los hombres experimentan debe ser encauzado, no sobre los otros hombres, sino sobre la Naturaleza, para producir los bienes que permitan "mejorar la suerte de la última clase social y volver dichosos a todos los hombres". 

### Los socialismos y los nacionalismos {-}

El tercer momento (1849-1927) es caracterizado por J.J. Chevalier por la emergencia de los socialismos y los nacionalismos. En este libro, el marxismo y todos sus derivados está ampliamente tratado en otro capítulo (ver Cap. 4) por lo que no mencionaremos aquí las obras de esa corriente. Aparte de ellas, una lista de obras importantes de este período debe a nuestro juicio mencionar al menos las siguientes:

- Emile Chartier(Alain):ELEMENTOS DE UNA DOCTRINA RADICAL (1925);
- Maurice Barrès: LOS DESARRAIGADOS (1897);
- Charles Darwin: EL ORIGEN DE LAS ESPECIES (1859);
- Adolf Hitler: MI LUCHA (1925)
- Jean Jaurès: HISTORIA SOCIALISTA DE LA REVOLUCIÓN FRANCESA (1901-1904);
- Gustave Le Bon: PSICOLOGÍA DE LAS MULTITUDES (1895);
- Paul Leroy-Beaulieu: EL ESTADO MODERNO Y SUS FUNCIONES (1889);
- Charles Maurras: ENCUESTA SOBRE LA MONARQUÍA (1900-1909) y KIEL Y TANGER (1910);
- Pierre-Joseph Proudhon: DE LA CAPACIDAD POLÍTICA DE LAS CLASES OBRERAS (1865);
-Georges Sorel: REFLEXIONES SOBRE LA VIOLENCIA (1908) y MATERIALES PARA UNA TEORÍA DEL PROLETARIADO (1919);
- Oswald Spengler: LA DECADENCIA DE OCCIDENTE (1918-1919).

De este período, tan abundante en obras fundamentales y polémicas, hemos elegido, para describir sus contenidos, una que en cierta medida sintetiza las dos ideas principales emergentes en este período: el socialismo y el nacionalismo. Se trata de "Los desarraigados" de Maurice Barrès.

Maurice Barrès (1862-1923) fué un escritor francés, proveniente de una familia de la alta burguesía. Su obra literaria de juventud ("Le culte du moi", "Un homme libre") lo muestran en una posición egoísta y hedonista, políticamente orientada hacia un soberbio aristocratismo. Luego evolucionó hacia una toma de conciencia socialmente solidaria, de tipo fuertemente nacionalista, que se expresa cabalmente en la trilogía que, bajo el título general de "La Novela de la Energía Nacional", contiene a "Los Desarraigados", "El Llamado al Soldado" y "Sus Figuras". También publicó una recopilación de ensayos bajo el título "Escenas y Doctrinas del Nacionalismo". Con el tiempo, su nacionalismo se hizo acentuadamente conservador, y adoptó actitudes antiparlamentarias y antisemitas, que lo llevaron, por ejemplo, a mantener una posición reaccionaria frente al "caso Dreyfus".

"Los Desarraigados" es una novela. No se presenta en absoluto como una obra de doctrina política. Al presentar la vida de siete jóvenes llegados a Paris desde su Lorena natal, en la búsqueda de grandes destinos, con el telón de fondo de los hechos nacionales ocurridos desde 1880, la obra sobrepasa ampliamente la intención novelística y desarrolla una visión de la historia nacional, de los principios y valores consagrados, referidos al orden y al devenir social, y al individuo en su papel respecto de la comunidad donde nació^[Zeev Sternhell: MAURICE BARRES ET LE NATIONALISME FRANCAIS, Paris, A. Colin, 1972.].

Barrès escribe esta obra en un momento singular de la historia francesa, en el que parece cobrar realidad el sueño de un "socialismo nacional" antiparlamentario y anticapitalista a la vez; un momento en el que parece posible la alianza política de los últimos tradicionalistas y monárquicos con socialistas proudhonianos y antiguos anarquistas.

En ese ambiente, Barrès es también sensible a las influencias del darwinismo social y de doctrinas inspiradas en un determinismo casi "fisiológico", que lo llevan a considerar socialmente viable un patriotismo fervoroso, nutrido con conceptos racionales y una cierta moral social.

Barrès define al nacionalismo como "la aceptación de un determinismo". Es el reconocimiento de la gravitación del pasado sobre el presente, la sumisión a la ley sagrada de las filiaciones, la obediencia a las grandes voces "de la tierra y de los muertos". Para Barrès, la expansión del individuo está vinculada al mantenimiento de la "sustancia nacional" que asegura las condiciones sociales de su desarrollo individual.

El nacionalismo de Barrès presenta dos fases: una faz contestataria, plebeya y socializante, animada de un cierto "romanticismo de la acción" antiburguesa y anticonformista; la otra faz es conservadora: apoya la preservación de la comunidad nacional apelando a todas las fuerzas del orden y de la jerarquía social, de la educación, la religión y las armas. En cuanto a la relación con la historia, Barrès piensa que todas las adquisiciones del pasado deben ser tomadas en cuenta: que se deben aceptar las cosas "tal como están". De allí su aceptación de las ideas de la Revolución Francesa y de la tradición republicana^[Chatelet, Duhamel y Pisier, op. cit.].

### Las teorías actuales {-}

El cuarto momento (desde 1928 hasta la actualidad) presenta muy variadas líneas de pensamiento, y es difícil conferirles un rasgo característico. Quizás puedan señalarse dos ejes dominantes en la preocupación de muchas de estas teorías normativas:

- la libertad individual y grupal frente al poder estatal;
- la democracia frente al totalitarismo.

La producción es vastísima, y son bastante borrosos los límites entre teorías normativas y teorías que reconocen fundamentos metodológicos empírico-analíticos o crítico-dialécticos. Toda nómina de obras sería incompleta o cuestionable. De todos modos, creemos que no pueden dejar de mencionarse las siguientes:

- Theodor W. Adorno: MINIMA MORALIA (1944-1947);
- Hanna Arendt: LOS ORÍGENES DEL TOTALITARISMO (1951);
- Raymond Aron: DEMOCRACIA Y TOTALITARISMO (1958) y PAZ Y GUERRA ENTRE LAS NACIONES (1962);
- Walter Benjamin: TESIS SOBRE EL CONCEPTO DE HISTORIA (1940);
- Alain de Benoist: DEMOCRACIA: EL PROBLEMA (1985);
- Leon Blum: A ESCALA HUMANA (1945);
- Albert Camus: EL HOMBRE REBELDE (1951);
- Pierre Clastres: LA SOCIEDAD CONTRA EL ESTADO (1974);
- Frantz Fanon: LOS CONDENADOS DE LA TIERRA (1961);
- Michel Foucault: VIGILAR Y CASTIGAR (1975);
- Bertrand de Jouvenel: EL PODER (1945);
- Herbert Marcuse: EROS Y CIVILIZACIÓN (1953) y LA NOCIÓN DE PROGRESO A LA LUZ DEL PSICOANÁLISIS (1968);
- Jacques Maritain: EL HOMBRE Y EL ESTADO (1953);
- Maurice Merleau-Ponty: HUMANISMO Y TERROR (1947);
- José Ortega y Gasset: LA REBELIÓN DE LAS MASAS (1930);
- Alfred Rosenberg: EL MITO DEL SIGLO XX;
- Jean-Paul Sartre: CRITICA DE LA RAZÓN DIALÉCTICA (1960);
- Karl Schmitt: TEORÍA DE LA CONSTITUCIÓN (1928);
- Erik Weil: FILOSOFÍA POLÍTICA (1956).

Esta larga lista no impresiona tanto como la cantidad de autores importantes que han quedado afuera, desde Voegelin, Eucken y Hattich hasta Spiro y Dante Germino, etc. Realmente, estas últimas seis décadas, que han sido las más fecundas en obras empíricas y crítico-dialécticas, también lo han sido en obras normativas.

Cómo hacer para pintar un panorama sin mutilaciones? Imposible. De todos modos, varios de estos autores han sido mencionados en otras partes de esta obra: así, T. Adorno (pág. 181), Hanna Arendt (pág. 341), W. Benjamin (pág. 181), H. Marcuse (pág. 182). De los restantes elegimos aquí dos para desarrollar algo sus contenidos, por entender que son representativos de las líneas dominantes en el pensamiento político normativo actual: Alain de Benoist y Bertrand de Jouvenel.

Alain de Benoist es un joven pensador de la Nueva Derecha francesa. Su libro "Democracia: el problema" parte de un análisis histórico de la democracia desde los griegos y los escandinavos. Hace una defensa crítica de la democracia y un análisis de la contradicción existente entre soberanía popular y pluralismo, para desembocar en una visión de la crisis actual de la democracia y en una propuesta de "democracia orgánica", construída no sobre el valor LIBERTAD (como las democracias liberales) ni sobre el valor IGUALDAD (como las democracias populares) sino sobre el valor FRATERNIDAD, se entiende que sin excluir a los otros valores^[Alain de Benoist: DEMOCRATIE: LE PROBLEME, Paris, Le Labyrin- the, 1985.].

La esencia del pensamiento de Alain de Benoist sobre la democracia parece estar expresada, a nuestro juicio, en las "Diez Tesis" que, a modo de postfacio cierran la obra: -"La mejor aproximación al concepto de democracia es la histórica: saber en primer lugar qué significaba la democracia para los que la inventaron. La libertad de las democracias antiguas es una libertad-participación, en la que el interés común y el conformismo priman sobre los intereses particulares. La principal diferencia entre las democracias antiguas y las modernas está en que las primeras ignoran el individualismo igualitario que fundamenta a las segundas".

- "Liberalismo y democracia no son sinónimos. La democracia es una "cracia", un gobierno, un poder; el liberalismo es una ideología de la limitación de todo poder político".

- "La democracia no es antagonista de la idea de un poder fuerte, o de las nociones de autoridad, selección o élite. La regla de la mayoría no está destinada a decir la verdad; es sólo un medio para elegir entre posibles".

- "La idoneidad política para gobernar no está en relación con el saber técnico o científico sino con la capacidad de decisión. El 'gobierno de los expertos' generalmente produce resultados catastróficos".

- "Los derechos políticos no derivan de 'derechos inalienables de la persona humana' sino de la condición de ciudadano. El principio democrático fundamental es: un ciudadano, un voto".

- "La noción clave del régimen democrático es la de participación. Es la participación del pueblo en las instituciones la que hace la democracia. El máximo de democracia es el máximo de participación".

- "Se recurre al principio de mayoría porque el principio de unanimidad (supuesto teórico de la 'voluntad general') es irrealizable. La mayoría es una técnica que permite reconocer el valor de la minoría (que puede ser mayoría mañana). El pluralismo tiene su límite en el bien común".

- "Las actuales democracias, que son poliarquías electivas, son una decadencia del ideal democrático, corrompido por la prepotencia del dinero y el efecto de la masa. La información está condicionada y estandarizada, la opinión está formada por factores heterónomos, los programas y los discursos políticos tienden a hacerse homogéneos, lo que hace indistintas las opciones. El resultado es la apatía política, que se opone a la participación y, por lo tanto, a la democracia".

- "La calidad de ciudadano no se agota en el acto de votar. Hay que explorar posibilidades que vinculen más directamente al pueblo con sus gobernantes y extiendan la participación. Una democracia orgánica puede desarrollarse en torno a la idea de fraternidad".

- "La democracia es el poder del pueblo; donde no hay pueblo no puede haber democracia. Todo sistema que debilite la conciencia de pertenencia a esa entidad orgánica que es el pueblo, debe ser considerado como un sistema no democrático".

Bertrand de Jouvenel (n. 1903 ) es un economista y ensayista francés, cuyos análisis se refieren principalmente a los orígenes y consecuencias del progreso tecnológico, investigando si nuestras sociedades hacen o no el mejor uso posible del aumento de volumen de consumo resultante de ese progreso. También ha incursionado con mucha penetración y ágil manejo de una gran erudición histórica, en el campo de la reflexión política normativa. Sus principales obras son: "La Economía Dirigida" (1929), "La crisis del capitalismo americano" (1933), "El Poder" (1945), "Etica de la Redistribución" (1955), "Arcadia, Ensayo sobre el Vivir Mejor" (1968), "Teoría Pura de la Política" (1963).

De esta amplia producción, vamos a ver con algún detalle los contenidos principales de "El Poder"^[Bertrand de Jouvenel: EL PODER, Madrid, Ed. Nacional, 1974, segunda edición.]. Esta obra tiene como contenido principal la lucha entre el poder y la libertad individual, que se disputan el predominio del espacio político. La conclusión es pesimista para la libertad individual. Según Bertrand de Jouvenel hay dos tipos de libertad: la libertad-participación, que es la posibilidad que tiene el ciudadano de participar en los órganos del poder y de contribuir a tomar decisiones, y la libertad-resistencia, que es la posibilidad de reservarse una zona de actuación al margen de la intervención estatal. Este último tipo de libertad es el que de Jouvenel valora más porque lo considera una auténtica manifestación de la libertad política.

Los hombres se clasifican -según de Jouvenel- en securitarios, que son la mayoría que busca seguridad antes que nada y está dispuesta a pagarla con libertad, y libertarios, que son una minoría, los pocos que conquistan y defienden su autonomía y asumen los riesgos de su libertad.

Esa libertad es frágil. Requiere muchas condiciones que rara vez se dan juntas: una minoría respaldada por una masa; una élite dotada de alto sentido moral: autodisciplina, función social asumida y reconocida; un cierto equilibrio de fortunas, que haga tolerable la situación de los inferiores. Los hombres libres son aristócratas. Los hombres comunes no son libres.

La democracia -sostiene de Jouvenel- no es respetuosa de las libertades individuales. Tiende a invadir el terreno de las libertades con el respaldo del apoyo popular. En la sociedad contemporánea no hay verdadera libertad: no hay élites libertarias; sólo hay una aristocracia sin honor que rehuye el riesgo y la responsabilidad. El poder ha crecido de un modo indiscriminado en todas las sociedades modernas, cualquiera sea su régimen político.

Bertrand de Jouvenel pretende ser objetivo, y sin duda es sincero, pero sus análisis están impregnados de juicios de valor muy subjetivos. Tiene una abierta simpatía por los regímenes aristocráticos, en los que una minoría, apoyada por la masa, limita el crecimiento del poder. Simpatiza con la libertad individual, entendida como señorío inmediato sobre sus actos (los comportamientos del "viejo aristócrata") y desprecia en forma mal disimulada al burgués que lo reemplazó.

Bertrand de Jouvenel casi no le da importancia a la libertad-participación, obsesionado como está por el señorío inmediato del hombre sobre sí mismo; y pasa por alto que las libertades-participación son la condición básica para el mantenimiento de las libertades-resistencia, salvo para una ínfima minoría de personas. Su planteo es anti-comunitario. A nivel general de la sociedad, las libertades-resistencia han de realizarse (si vamos a considerar viable esa posibilidad) sin mengua para la sobrevivencia y bienestar de los grupos. El individuo común, encuadrado en el mejor de los casos en organizaciones productivas, puede ser algo más libre si se atenúan los controles que pesan sobre él y se incrementa su participación, responsabilidad e iniciativa. Pero de Jouvenel considera que la máxima posibilidad de incrementar la libertad está en la automación de los procesos productivos y el aumento del tiempo libre. Esa libertad sería individual y no comunitaria, y en la actual organización conduciría, no al ocio fecundo sino al envilecimiento del desempleo. Creemos que la principal crítica que puede hacerse a Bertrand de Jouvenel es que su condición de liberal elitista lo lleva a considerar como ideal sólo al modelo de la sociedad aristocrática, sin preguntarse si existirán o no otras posibilidades de realizar la libertad-resistencia de un modo más igualitario.

Luis García San Miguel, al prologar la edición castellana de "El Poder" plantea en este sentido la posibilidad de adoptar un modelo de "sociedad autogestionada" , que mantiene al Estado constreñido a un rol mínimo indispensable porque las empresas y las organizaciones intermedias de la sociedad disponen de amplia autonomía frente al Estado y son controladas por los que trabajan en ellas en un régimen de democracia directa.

En un modelo así, las competencias estatales quedarían reducidas al mínimo necesario para mantener la cohesión del conjunto social, mientras la mayoría de las funciones sociales serían desempeñadas por la sociedad misma. Una sociedad así -sostiene García San Miguel- podría realizar una buena combinación dialéctica del ideal socialista de la IGUALDAD, el ideal democrático de la PARTICIPACIÓN, el ideal liberal de la LIBERTAD INDIVIDUAL y del ideal anarquista de la REDUCCIÓN DEL PODER ESTATAL al mínimo indispensable.

Curiosamente, Bertrand de Jouvenel escribía estas cosas cuando la marcha del mundo parecía orientarse, según la visión predominante en aquellos años, hacia formas socializantes, de incremento de la intervención estatal, no sólo en los países del "socialismo real" sino en los países democráticos occidentales, los países del "welfare state", de la "svolta a sinistra" etc.

Nada parecía anunciar concretamente, en aquellos años, la emergencia del neo-conservadorismo o neo-liberalismo, que hemos vivido recientemente, con sus demandas de "Estado mínimo", libertad a la iniciativa individual de la opresiva protección estatal, privatización de los servicios públicos, etc.; corrientes que cambiaron el mapa político de Occidente y derrumbaron los regímenes del socialismo real. Esas corrientes son formas políticas, prácticas e ideológicas, evidentemente afines en muchos aspectos al pensamiento de Bertrand de Jouvenel, aunque cabe mencionar que su aristocrático individualismo tiene un sesgo de nobleza que no se confunde con el crudo pragmatismo crematístico que hoy cunde por doquier.

## Cuarta parte {-}

### Enfoques metodológicos usuales {-}

La extensión temporal (no menos de 2500 años) y espacial (desde China hasta América, pasando por Europa) de la producción politológica normativa, torna imposible todo intento de sistematización detallada del tema metodológico, que aparece además en este caso notablemente "personalizado" en cada autor. Es posible, en cambio, dar algunas ideas o pautas generales sobre los criterios metodológicos más frecuentes.

Ya dijimos que las teorías políticas normativas se ubican en un ámbito de fuerte vocación filosófica, en un área intermedia entre la Ciencia Política y la Filosofía Política. De la primera conservan el fuerte impulso de "entender" y de "comprender" la realidad basándose en ella misma, vale decir, en el contenido empírico de las observaciones. De la segunda conservan la vocación de conceptualización omniabarcativa y de evaluación axiológica en términos perdurables.

En el terreno puramente metodológico, esa doble vertiente también se hace sentir. Hay observación sistemática y acumulación y procesamiento de datos empíricos, y hay también análisis racional y deductivo. Cabe destacar el frecuente uso del método filosófico dialéctico, en las distintas formas en que fue empleado por Platón, Aristóteles, Santo Tomás, Hegel, Marx...

También es digno de destacar el frecuente empleo del método histórico. La Historia es una gran "proveedora de materiales" para la Ciencia Política en general, y para las teorías normativas en particular. No es casual que muchos teóricos de esta corriente sean eminentes historiadores, o al menos personas de reconocida versación histórica, y que el principal aporte de esta corriente al "corpus" politológico esté en la Historia de las Ideas Políticas.

En los escritos de autores normativos es frecuente el empleo de analogías y metáforas. Este recurso tiene un interesante valor pedagógico, pero el excesivo empleo del método analógico, y sobre todo el impulso de llevar la analogía más lejos de lo prudente, es indudablemente riesgoso desde el punto de vista epistemológico, y constituye quizás uno de los puntos más débiles de estas teorías.

Es frecuente en esta corriente teórica el uso de un tratamiento metodológico similar al utilizado en Derecho, Terapéutica y Educación, es decir, en ciencias prácticas, que parten del planteo de problemas individualizados para tratar de resolverlos apelando a principios generales y a antecedentes (como la jurisprudencia).

Los autores normativistas suelen ser partidarios de estudios casuísticos y de monografías prescriptivas. Algunos emplean el método tópico, que parte de la consideración de problemas particulares, evaluados con criterios de comprensión, para remontarse a la enunciación de principios o ideas generales.

Frecuentemente, los autores normativistas contemporáneos recurren a la teoría política clásica (Aristóteles, sobre todo) en busca de fundamentación para sus conclusiones actuales. Son, por otra parte, partidarios de la "política pura" y se oponen por lo general a todo reduccionismo de la política a otras variables (clases, modos de producción, factores geográficos, etc.).

Por último, cabe mencionar dos preocupaciones frecuentes en estos autores: por una parte, el valor de la Ciencia Política como fuente de educación política, les hace incluir en sus presentaciones diversas variantes del método pedagógico. Por otra parte, la conciencia del valor de la Ciencia Política para la administración de los bienes públicos los lleva con frecuencia a descuidar otros temas, como el de la participación política y el de la movilización social, lo que favorece la adopción de un pragmatismo metodológico. 