`r if (knitr:::is_html_output()) '# Referencias bibliográficas {-}'`

```{r include=FALSE}
# generate a BibTeX database automatically for some R packages
  knitr::write_bib(c(.packages(), 'bookdown', 'knitr', 'rmarkdown'), 
                   'packages.bib', width = 500)

# some adjustments
library(dplyr)
l <- gsub(pattern = "note = ", replacement = "version = ", x = readLines("packages.bib")) %>% gsub(pattern = "R package version ", replacement = "")

l[grep("title = ", l)] <- gsub("\\{", "\\{\\{", l[grep("title = ", l)]) %>% gsub(pattern = "\\}", replacement = "\\}\\}")

writeLines(l, con = "packages.bib")
```

- ADORNO, Theodor W. "LA PERSONALIDAD AUTORITARIA", Paidós, Bs.As., 1969.
- ALIGHIERI, Dante "DE LA MONARQUIA", Losada, Bs.As.
- ALBERIONI et al. "L'ATTIVISTA DI PARTITO", Bolonia, 1967.
- ALMOND, G. y COLEMAN "THE POLITICS OF THE DEVELOPING AREAS", Princeton
University Press, 1960.
- ALMOND, G.A. y VERBA, Sidney "THE CIVIC CULTURE", Princeton University Press, 1963.
- ALMOND, G.A. y POWELL, G.B. "POLITICA COMPARADA", Paidós, Bs.As., 1972.
- ALTHUSSER, Louis "PARA LEER EL CAPITAL", Siglo XXI, México, 1969.
- AMIN, Samir "SOBRE EL DESARROLLO DESIGUAL DE LAS FORMACIONES SOCIALES",
Anagrama, Barcelona, 1976.
- AMIN, Samir "L'ACCUMULATION A L'ECHELLE MONDIALE", Editions Anthropos, París, 
1970.
- ANDERSON, Perry "CONSIDERACIONES SOBRE EL MARXISMO OCCIDENTAL", Siglo XXI,
México, 1990.
- APONTE, Antonio "LA ECONOMIA DE LOS PAISES SOCIALISTAS", Salvat ed., Barcelona, 
1973.
- ARENDT, Hannah "LOS ORIGENES DEL TOTALITARISMO", Alianza ed., Madrid, 1981-1982, 
2 vol.
- APTER, David E. "POLITICA DE LA MODERNIZACION", Paidós, Bs.As., 1972.
- ARISTOTELES "LA POLITICA", Editora Nacional, Madrid, 1977.
- ARNOLETTO, Eduardo J. "APROXIMACION A LA CIENCIA POLITICA", Artesol ed., Córdoba, 
1989.
- ARON, Raymond "EL OPIO DE LOS INTELECTUALES", Siglo XX, Bs.As., 1968.
- ARON, Raymond "DEMOCRACIA Y TOTALITARISMO", Seix, Barcelona, 1971.
- ARON, Raymond "PAZ Y GUERRA ENTRE LAS NACIONES", Alianza ed., Madrid, 1984.
- ARON, Raymond "REPUBLIQUE IMPERIALE: LES ETATS-UNIS DANS LE MONDE (1945-
1972)", Calmann-Lévy, París, 1973.
- "BREVE DICCIONARIO POLITICO", Ed. Progreso, Moscú, 1983.
- BALANDIER, George "ANTROPOLOGIA POLITICA", Península, Barcelona, 1969.- BARAN, Paul y SWEEZY, Paul "EL CAPITALISMO MONOPOLISTA. UN ENSAYO SOBRE LA
SOCIEDAD INDUSTRIAL AMERICANA", Siglo XXI, México, 1968. 
- BARRACLOUGH, Geofrey "UNE INTRODUCTION A L'HISTOIRE CONTEMPORAINE", Ed.
Stock, París, 1964. 
- BELL, Daniel "FIN DE LAS IDEOLOGIAS", Tecnos, Madrid, 1964. 
- BELL, Daniel "THE END OF IDEOLOGY: ON THE EXHAUSTION OF POLITICAL IDEAS IN
THE FIFTIES", New York, 1960. 
- BENDIX, R. "NATION-BUILDING AND CITIZENSHIP", John Wiley, New York, 1964. 
- BERTALANFFY, Ludwig von "TEORIA GENERAL DE LOS SISTEMAS", FCE, México, 1981. 
- BENOIST, Alain de "DEMOCRATIE: LE PROBLEME", Le Labyrinthe, París, 1985. 
- BEYME, Klaus von "TEORIAS POLITICAS CONTEMPORANEAS - UNA INTRODUCCION",
Instituto de Estudios Políticos, Madrid, 1977. 
- BOBBIO, N. et al. "DICCIONARIO DE POLITICA", Siglo XXI, México, 1986. 
- BOBBIO, Norberto "SAGGI SULLA SCIENZA POLITICA IN ITALIA", Bari, 1969. 
- BOBBIO, Norberto "IL FUTURO DELLA DEMOCRAZIA. UNA DIFESA DELLE REGOLE DEL
GIOCO", Einaudi ed., Torino, 1984. 
- LE BON, Gustave "PSICOLOGIA DE LAS MULTITUDES", Ed. Albatros, Bs.As., 1978. 
- BRZEZINSKI, Zbigniew "IDEOLOGIA Y PODER EN LA POLITICA SOVIETICA", Paidós, 
Bs.As., 1968. 
- BRAILLARD, Philippe "THEORIE DES SYSTEMES ET RELATIONS INTERNA-TIONALES",
Ed. Bruylant, Bruselas, 1977. 
- BRAILLARD, P. y DE SENARCLENS, P. "EL IMPERIALISMO", FCE, México, 1982. 
- BRUNSCHWIG, H. "LE PARTAGE DE L'AFRIQUE NOIRE", Flammarion, París, 1971. 
- CARDOZO, F.H. y FALETTO, E. "DEPENDENCIA Y DESARROLLO EN AMERICA LATINA,
Siglo XXI, México, 1969. 
- CARTWRIGHT, Dorwin y ZANDER, Alvin "GROUP DYNAMICS: RESEARCH AND THEORY",
Ed. Harper and Row, 1962. 
- CASSIRER, Ernest "EL MITO DEL ESTADO", FCE, México, 1968. CESAREO, Vincenzo et al.
"LA CULTURA DELL'ITALIA CONTEMPORANEA. TRASFORMAZIONE DEI MODELLI DI
COMPORTAMENTO E IDENTITA SOCIALE", Ed. Fondazione Giovanni Agnelli, Torino, 1990. 
- CHATELET, F., DUHAMEL, O. y PISIER, E. "DICTIONNAIRE DES OEUVRES POLITIQUES", 
P.U.F., París, 1989.- CHEVALIER, J.J. "LOS GRANDES TEXTOS POLITICOS - DESDE MAQUIAVELO A
NUESTROS DIAS", Aguilar, Madrid, 1979. 
- COPLIN, W.D. "INTRODUCTION TO INTERNATIONAL POLITICS. A THEORETICAL
OVERVIEW, Chicago ,1971. 
- CROZIER, Michel "LE PHENOMENE BUREAUCRATIQUE", Seuil, París, 1964. 
- DENQUIN, Jean-Marie "SCIENCE POLITIQUE", P.U.F., París, 1991. 
- DEUTSCH, K.W. "NATIONALISM AND SOCIAL COMMUNICATION. AN INQUIRY INTO
THE FOUNDATIONS OF NATIONALITY", M.I.T. Press, Mass., 1953. 
- DEUTSCH, K. et al. "POLITICAL COMMUNITY AND THE NORTH ATLANTIC AREA.
INTERNATIONAL ORGANIZATION IN THE LIGHT OF HISTORICAL EXPERIENCE",
Princeton, 1957. 
- DEUTSCH, Karl "POLITICA Y GOBIERNO", FCE, México, 1976. 
- DEUTSCH, Karl "LOS NERVIOS DEL GOBIERNO", FCE, México, 1985. 
- DEUTSCH, Morton y KRAUSS, Robert "THEORIES IN SOCIAL PSYCHOLOGY", Basic Books,
Inc., 1965. 
- DIAMANT, A. "THE NATURE OF POLITICAL DEVELOPMENT" en Finkle y Gable
"POLITICAL DEVELOPMENT AND SOCIAL CHANGE", John Wiley, New York, 1966. 
- DJILAS, Milovan "LA NUEVA CLASE", Sudamericana, Bs.As., 1965. 
- DRAPER, T. "ABUSE OF POWER", Secker and Warburg, London, 1966. 
- DURKHEIM, E. "DE LA DIVISION DEL TRABAJO SOCIAL, Schapire, Bs.As, 1967. 
- ------------ "EL SUICIDIO", Schapire, Bs.As., 1965.
- ------------ "LAS FORMAS ELEMENTALES DE LA VIDA RELIGIOSA", Schapire, Bs.As., 1968. 
- EASTON ,D. y DENNIS, J. "CHILDREN IN THE POLITICAL SYSTEM", New York, 1969. 
- EASTON, David "ESQUEMA PARA EL ANALISIS POLITICO, Amorrortu, Bs.As., 1969. 
- ECKSTEIN, H. y APTER, D. "COMPARATIVE POLITICS. A READER", New York, 1963. 
- ECKSTEIN, H. "DIVISION AND COHESION IN DEMOCRACY - A STUDY OF NORWAY",
Princeton University Press, 1966. 
- EISENSTADT, S.N. "MODERNIZACION, MOVIMIENTOS DE PROTESTA Y CAMBIO
SOCIAL", Amorrortu, Bs.As., 1969. 
- EMMANUEL, Arghiri "L'ECHANGE INEGAL. ESSAI SUR LES ANTAGONISMES DANS LES
RAPPORTS ECONOMIQUES INTERNATIONAUX, Maspero, París, 1969. 
- FEJTÖ, François "LA SOCIAL-DEMOCRATIE QUAND MEME", Ed. Robert Laffont, París, 1980. - FESTINGER, Leo "A THEORY OF COGNITIVE DISSONANCE", Row, Peterson and Co., 1957. 
- FRANK, André Gunder "CAPITALISMO Y SUBDESARROLLO EN AMERICA LATINA", Siglo 
XXI, México, 1970. 
- FRENCH, John R.P. Jr. "A FORMAL THEORY OF SOCIAL POWER" en Cartwright y Zander:
"GROUPS DINAMICS: RESEARCH AND THEORY", Ed. Harper and Row, 1962. 
- FREUD, Sigmund "OBRAS COMPLETAS" , Tomos II y III, Ed. Biblioteca Nueva, Madrid, 1973. 
- FRIEDRICH, Carl "EL HOMBRE Y EL GOBIERNO: UNA TEORIA EMPIRICA DE LA
POLITICA", Tecnos, Madrid, 1968. 
- FRIEDRICH, C. y BRZEZINSKI, Z. "DICTADURA TOTALITARIA Y AUTOCRACIA", Libera, 
Bs.As., 1975. 
- FULBRIGHT, J.W. "THE ARROGANCE OF POWER", Vintage Books, New York, 1966. 
- FURTADO, Celso "DESARROLLO Y SUBDESARROLLO", Eudeba, Bs.As., 1965. 
- GALLAGER, John y ROBINSON, Ronald "AFRICA AND THE VICTORIANS. THE OFFICIAL 
MIND OF IMPERIALISM", Ed. Macmillan, London, 1961. 
- GARCIA PELAYO, Manuel "MITOS Y SIMBOLOS POLITICOS", Taurus, Madrid, 1964. 
- GENIAGE, Jean "L'EXPANSION COLONIALE DE LA FRANCE SOUS LA IIIe REPUBLIQUE
(1871-1914)", Payot, París, 1968. 
- GERMANI, Gino "POLITICA Y SOCIEDAD EN UNA EPOCA DE TRANSICION", Paidós, 
Bs.As., 1965. 
- GOLEMBIEWSKI, Robert "BEHAVIOR AND ORGANIZATION: ORGANIZATION AND
METHODS AND THE SMALL GROUP", Rand McNally and Co., 1962. 
- GORI, U., BRUSCHI, A., ATTINA, F. "RELAZIONI INTERNAZIONALI. METODI E TECNICHE
DI ANALISI", Milán, 1974. 
- GRAMSCI, Antonio "NOTAS SOBRE MAQUIAVELO, LA POLITICA Y EL ESTADO", Juan 
Pablos, México, 1975. 
- GURVITCH, Georges "TRATADO DE SOCIOLOGIA", Kapeluz, BS.As., 1963. 
- ----------------- "LES CADRES SOCIAUX DE LA CONNAISSANCE", PUF, París, 1966. 
- HABERMAS, Jürgen "TEORIA Y PRAXIS", Sur, Bs.As., 1967. 
- ---------------- "TEORIA E PRASSI NELLA SOCIETA TECNOLOGICA, Bari, 1969. 
- HARGROVE, E.C. "PRESIDENTIAL LEADERSHIP - PERSONALITY AND POLITICAL
STYLE", New York/London, 1966. - HAURIOU, A. "DERECHO CONSTITUCIONAL E INSTITUCIONES POLITICAS", Ed. Ariel, 
Barcelona, 1971. 
- HEARNSHAW, F.J.C. "HISTORIA DE LAS IDEAS POLITICAS", Empresa Letras, Santiago de 
Chile, . 
- HILFERDING, Rudolf "LE CAPITAL FINANCIER. ETUDE SUR LE DEVELOPMENT RECENT
DU CAPITALISME", Ed. du Minuit, París, 1970. 
- HOBSON, J.A. "ESTUDIOS DEL IMPERIALISMO", Alianza, Madrid, 1981. 
- HOFFMAN, Stanley "GULLIVER EMPETRÉ. ESSAI SUR LA POLITIQUE ETRANGERE DES
ETATS-UNIS", Seuil, París, 1971. 
- HOLT, R.T. y TURNER E. "THE METHODOLOGY OF COMPARATIVE RESEARCH", New 
York, 1970. 
- HOMANS, George C. "SOCIAL BEHAVIOR: ITS ELEMENTARY FORMS", Harcourt, Brace and
Word Inc., 1961. 
- HORKHEIMER, Max y ADORNO, Theodor "DIALECTICA DEL ILUMINISMO", Sur, Bs.As., 
1969. 
- HOVLAND, Car I. et al. "COMMUNICATION AND PERSUATION: PSYCOLOGICAL STUDIES 
OF OPINION CHANGE", Yale University Press, 1953. 
- HULL, Clark L. "A BEHAVIOR SYSTEM", Yale University Press, 1952. 
- HUNTINGTON, S.P. y MOORE, C.H. "AUTHORITARIAN POLITICS IN MODERN SOCIETY", 
New York, 1970. 
- HUNTINGTON, S.P. "EL ORDEN POLITICO EN LAS SOCIEDADES EN CAMBIO", Paidós, 
Bs.As., 1972. 
- JAGUARIBE H. et al. "LA DEPENDENCIA POLITICO-ECONOMICA DE AMERICA LATINA",
Siglo XXI, México, 1971. 
- JAGUARIBE-FURTADO-FALETTO-DITELLA-ESPARTACO-SUNKEL- CARDOSO "LA
DOMINACION DE AMERICA LATINA", Amorrortu, Bs.As., 1972. 
- JAGUARIBE, Helio "SOCIEDAD, CAMBIO Y SISTEMA POLITICO", Paidós, Bs.As., 1972. 
- ---------------- "DESARROLLO POLITICO - SENTIDO Y CONDICIONES", Paidós, Bs.As., 1972. 
- ---------------- "AMERICA LATINA - REFORMA O REVOLUCION", Paidós, Bs.As., 1972. 
- ---------------- "O NOVO CENARIO INTERNACIONAL", Ed. Guanabara, Río de Janeiro, 1986. 
- JALEÉ, Pierre "L'IMPERIALISME EN 1970", Maspero, París, 1973. 
- JAMES. Emile "HISTORIA DEL PENSAMIENTO ECONOMICO", Aguilar, Madrid, 1974. - JOUVENEL, Bertrand de "EL PODER", Ed. Nacional, Madrid, 1974.
- 2a ed. KAPLAN, M.A. "SYSTEM AND PROCES IN INTERNATIONAL POLITICS", New York, 
1957. 
- KEOHANE, R.O. y NYE, J.S. "TRANSNATIONAL RELATIONS IN WORLD POLITICS",
Harvard University Press, 1972. 
- KNOLL, E. y McFADEN, J. "AMERICAN MILITARISM - 1970", The Viking Press, New York, 
1969. 
- KORNHAUSER, William "ASPECTOS POLITICOS DE LA SOCIEDAD DE MASAS", Amorrortu, 
Bs.As., 1969. 
- LAGROYE, Jacques "SOCIOLOGIE POLITIQUE", Presses de la F.N. des Sc. Po. & Dalloz, París, 
1991. 
- LANE, R. "POLITICAL IDEOLOGY", New York, 1962. 
- LAPLANCHE, J. y PONTALIS, J.B. "DICCIONARIO DE PSICOANALISIS", Ed. Labor, 
Barcelona, 1974. 
- LASSWELL, Harold D. "PSYCHOPATHOLOGY AND POLITICS", Viking Press Inc., 1962.
- LERNER, D. "THE PASSING OF TRADITIONAL SOCIETY. MODERNIZING THE MIDDLE
EAST, New York, 1958. 
- LEWIN, Kurt "FIELD THEORY IN SOCIAL SCIENCE", Dorwin Cartwright (Harper and Bros.), 
1951. 
- LIJPHART, A. "THE POLITICS OF ACCOMODATION. PLURALISM AND DEMOCRACY IN
THE NETHERLANDS", Berkeley, Los Angeles, 1968. 
- LIPSET, Seymour Martin "EL HOMBRE POLITICO. LAS BASES SOCIALES DE LA POLITICA",
Eudeba ed., Bs.As., 1977. 
- LISKA, George "IMPERIAL AMERICA. THE INTERNATIONAL POLITICS OF PRIMACY",
John Hopkins Press, Baltimore, 1967. 
- LOCKE, John "ENSAYO SOBRE EL GOBIERNO CIVIL", Aguilar, Madrid, 1981. 
- LOPEZ, Mario Justo "INTRODUCCION A LOS ESTUDIOS POLITICOS", Tomos I y II, Kapeluz, 
Bs.As., 1975. 
- LUKACS, György "EL ASALTO A LA RAZON", Grijalbo, México, 1976. 
- LUXEMBURG, Rosa "LA ACUMULACION DEL CAPITAL", Grijalbo, México, 1967. 
- MAIMONIDES, M. "THE GUIDE OF THE PERPLEXED", University of Chica-go Press, Chicago, 
1963. - MANNHEIM, Karl "IDEOLOGIA Y UTOPIA", Aguilar, Madrid, 1973. 
- MAQUIAVELO, Nicolás "EL PRINCIPE", Alianza ed., Madrid, 1981. 
- ------------------- "DISCURSOS SOBRE LA PRIMERA DECADA DE TITO LIVIO", en "Obras",
Vergara, Barcelona, 1965. 
- MARCH, James G. y SIMON, Herbert A. "ORGANIZATIONS", John Wiley and Sons, 1962. 
- MARX, Karl "LA IDEOLOGIA ALEMANA", Grijalbo, México, 1969.
- MARX, Karl "ELEMENTOS FUNDAMENTALES PARA LA CRITICA DE LA ECONO- MIA
POLITICA", Siglo XXI, Madrid, 1972. 
- ---------- "TEORIAS SOBRE LA PLUSVALIA", FCE, México, 1982. 
- MARCUSE, Herbert "EL FIN DE LA UTOPIA", Siglo XXI, México, 1968. 
- ---------------- "EL HOMBRE UNIDIMENSIONAL", Mortiz, México, 1970.
- MEEHAN, E.J. "PENSAMIENTO POLITICO CONTEMPORANEO", Rev. de Occidente, Madrid, 
1973. 
- MERTON, Robert K. "TEORIA Y ESTRUCTURAS SOCIALES", FCE, México, 1964. 
- MICHELS, Robert "LOS PARTIDOS POLITICOS", Amorrortu, Bs.As., 1969 
- MILBRATH, Lester W. "POLITICAL PARTICIPATION", Rand Mc Nally and Co., 1965. 
- MOONEY, Alfredo y ARNOLETTO, Eduardo "CUESTIONES FUNDAMENTALES DE CIENCIA
POLITICA", Alveroni ed., Córdoba, 1993. 
- MORGENTHAU, Hans "POLITICS AMONG NATIONS. THE STRUGGLE FOR POWER AND
PEACE", Knopf, New York, 1955. 
- MORLINO, L. Comp. "GUIDE AGLI STUDI DI SCIENZE SOCIALI IN ITALIA - SCIENZA
POLITICA", Ed. Fond. G. Agnelli, Torino, 1989. 
- MORO, Tomás "UTOPIA", Bruguera, Barcelona, 1973. 
- ORGANSKI, A.F.K. "THE STAGES OF POLITICAL DEVELOPMENT", A. Knopf, New York, 
1965. 
- OSSOWSKI, Stanislaw "ESTRUCTURA DE CLASE Y CONCIENCIA SOCIAL", Península, 
Barcelona, 1971. 
- PARETO, Vilfredo "FORMA Y EQUILIBRIO SOCIALES", Rev. de Occidente, Madrid, 1966.
- PARETI, Luigi et al. "HISTORIA DE LA HUMANIDAD - DESARROLLO CULTURAL Y
CIENTIFICO", Tomo II (UNESCO), Ed. Sudamericana, Bs.As., 1969. 
- PARTRIDGE, P.H. "CONSENT AND CONSENSUS", Londres, 1971. 
- PARSONS, Talcott "EL SISTEMA SOCIAL", Rev. de Occidente, Madrid, 1976. - ---------------- "ENSAYOS DE TEORIA SOCIOLOGICA", Paidós, Bs.As., 1970. 
- ---------------- "EL SISTEMA DE LAS SOCIEDADES MODERNAS", Trillas México, 1974. 
- PITKIN, H. "THE CONCEPT OF REPRESENTATION", Berkeley, 1967. 
- PINTO, A. "POLITICA Y DESARROLLO", Ed. Universitaria, Santiago de Chile, 1972. 
- PLATON "LA REPUBLICA", UNAM, México, 1971. 
- ------ "LAS LEYES", Inst. de Est. Políticos, Madrid, 1960. 
- ------ "EL POLITICO", Inst. de Est. Políticos, Madrid, 1955. 
- PUTNAM, R.D. "THE BELIEF OF POLITICIANS: IDEOLOGY, CONFLICT AND
DEMOCRACY IN BRITAIN AND ITALY, London, 1973. 
- PYE, L.W. "COMMUNICATIONS AND POLITICAL DEVELOPMENT", Princeton, 1963. 
- --------- "POLITICS, PERSONALITY AND NATION-BUIDING. BURMS'S SEARCH FOR
IDENTITY", Yale University Press, New Haven, 1966. 
- --------- "ASPECTS OF POLITICAL DEVELOPMENT", Little Brown, Boston, 1966. 
- PYE, L.W. y VERBA, S. "POLITICAL CULTURE AND POLITICAL DEVELOP-MENT",
Princeton University Press, 1969.
- RIBEIRO, Darsy "EL DILEMA DE AMERICA LATINA", Siglo XXI, México, 1971. 
- RICHARDSON, Lewis "ARMS AND INSECURITY", Quadrangle Press, Chicago, 1960. 
- ROBINSON, R. "THE NON-EUROPEAN FOUNDATIONS OF EUROPEAN IMPERIALISM:
SKETCH FOR A THEORY OF COLLABORATION", Longman, London, 1972. 
- ROUQUIÉ, Alain "EXTREMO OCCIDENTE. INTRODUCCION A AMERICA LATINA", Emecé,
Bs.As., 1991. 
- ROSTOW, Walt "LAS ETAPAS DEL CRECIMIENTO ECONOMICO", FCE, México, 1961. 
- ROSTOW, W.W. "POLITICS AND THE STAGES OF GROWTH", Cambridge, 1971. 
- ROSENAU, J.N. "THE SCIENTIFIC STUDY OF FOREIGN POLICY", New York, 1971. 
- RUNCIMAN, W.G. "SOCIOLOGY IN ITS PLACE", Cambridge, 1970. 
- RUYER, Raymond "L'UTOPIE ET LES UTOPIES", PUF, París, 1950. 
- SABINE, G.H. "HISTORIA DE LA TEORIA POLITICA", FCE, México, 1984. 
- SANTOS, Theodoro dos "LA NUOVA DIPENDENZA", Milán, 1971. 
- SARTORI, G. "SISTEMI RAPPRESENTATIVI" en "DEMOCRAZIA E DEFINIZIO- NI", Bolonia, 
1969. 
- ----------- "LA POLITICA - LOGICA Y METODO EN LAS CIENCIAS SOCIA- LES", FCE, 
México, 1984. - SCHLESINGER, A.M. "THE IMPERIAL PRESIDENCY", Popular Library, New York, 1974. 
- SCHUMPETER, Joseph "CAPITALISMO, SOCIALISMO Y DEMOCRACIA", Agui- lar, México, 
1961.
- ------------------ "IMPERIALISMO Y CLASES SOCIALES", Tecnos, Ma- drid, 1965. 
- SCHMITT, Carl "LEGALIDAD Y LEGITIMIDAD", Aguilar, Madrid, . SAINT-SIMON
"OEUVRES", Anthropos, París, 1966. 
- SIMON, Herbert A. "MODELS OF MAN: SOCIAL AND RATIONAL", Wiley, New York, 1957. 
- SKINNER, B.F. "SCIENCE AND HUMAN BEHAVIOR", Free Press, New York, 1953. 
- SOREL, Jean "REFLEXIONES SOBRE LA VIOLENCIA", Alianza, Madrid, 1976. 
- SUNKEL, O. y PAZ, P. "EL DESARROLLO LATINOAMERICANO Y LA TEORIA DEL
DESARROLLO", Siglo XXI, México, 1970. 
- SWEEZY, Paul "ÉLITE DE PODER O CLASE DIRIGENTE?", Jorge Alvarez, Bs.As., . TUCKER,
Robert "NATION OR EMPIRE? DEBATE OVER AMERICAN FOREIGN POLICY", J. Hopkins
Press, Baltimore, 1968. 
- TZU, Sun "L'ART DE LA GUERRE", Flammarion, París, 1972. 
- URBANI, G. "LA POLITICA COMPARATA", Bolonia, 1972. 
- VERBA, Sidney "SMALL GROUPS AND POLITICAL BEHAVIOR", Princeton University Press, 
1961. 
- VOEGELIN, Eric "NUEVA CIENCIA DE LA POLITICA", Rialp, Madrid, 1968. 
- VRANICKI, P., SUPEK, R. et al. "EL SOCIALISMO YUGOESLAVO ACTUAL", Grijalbo ed., 
México, 1975. 
- WEBER, Max "EL POLITICO Y EL CIENTIFICO", Alianza, Madrid, 1967.
- ---------- "ECONOMIA Y SOCIEDAD", FCE, México, 1964. 
- YARMOLINSKY, Adam "THE MILITARY ESTABLISHMENT. ITS IMPACT ON AMERICAN
SOCIETY", Harper & Row, New York, 1971.
- ZEITLIN, Irving "IDEOLOGIA Y TEORIA SOCIOLOGICA", Amorrortu ed., Bs.As., 1973